const VIDEOFEED = [
{
"id": "7671257829717626134",
"side": "ja",
"title": "Bubbi: börnin eiga skilið bjarta framtíð",
"summary": "Bubbi Morthens segist ætla að segja já fyrir börnin sín sem eigi rétt á fallegri framtíð.",
"account": "sja",
"url": "https://www.tiktok.com/@jatiladsja/video/7671257829717626134",
"views": 56100,
"argKey": "taekifaeri",
"argTitle": "Tækifæri unga fólksins",
"argIcon": "🎓"
},
{
"id": "7662453125797874967",
"side": "nei",
"title": "Við ráðum okkar eigin málum",
"summary": "Viðmælandi vill ekki flytja hluta fullveldisins til Brussel, segir lífskjör betri á Íslandi en í Evrópu og að krónan sé ekki orsök hárrar verðbólgu og vaxta.",
"account": "aframisland",
"url": "https://www.tiktok.com/@afram.island/video/7662453125797874967",
"views": 2980,
"argKey": "fullveldi",
"argTitle": "Fullveldisframsal",
"argIcon": "🏛️"
},
{
"id": "7657943541020183811",
"side": "ja",
"title": "Gengismunurinn étur peningana þína",
"summary": "Sýnt er hvernig þúsundkall rýrnar um 500 krónur við það eitt að skipta krónum í evrur og til baka vegna gengismunar.",
"account": "sja",
"url": "https://www.tiktok.com/@jatiladsja/video/7657943541020183811",
"views": 46800,
"argKey": "vextir",
"argTitle": "Lægri vextir og stöðugur gjaldmiðill",
"argIcon": "💶"
},
{
"id": "7659785189211655446",
"side": "nei",
"title": "Ríkustu þjóðir Evrópu utan ESB",
"summary": "Því er haldið fram að Ísland hafi farið úr fátækt í fremstu röð utan ESB og að þrjár af fimm ríkustu þjóðum Evrópu — Noregur, Sviss og Ísland — standi utan sambandsins og án evru.",
"account": "aframisland",
"url": "https://www.tiktok.com/@afram.island/video/7659785189211655446",
"views": 36200,
"argKey": "efnahagur",
"argTitle": "Íslandi vegnar betur utan ESB",
"argIcon": "📈"
},
{
"id": "7675175197682601239",
"side": "ja",
"title": "Upplýsingar fást bara með jái",
"summary": "Vegfarendur segjast kjósa já því ákvörðun verði ekki tekin nema með upplýsingum sem fáist aðeins með því að klára viðræður.",
"account": "sja",
"url": "https://www.tiktok.com/@jatiladsja/video/7675175197682601239",
"views": 32900,
"argKey": "kikja",
"argTitle": "Kosið um viðræður — sjáum samninginn",
"argIcon": "📄"
},
{
"id": "7659951824610266390",
"side": "nei",
"title": "Guðni Ágústsson: Verjum frelsið",
"summary": "Guðni Ágústsson segir verið að plata fólk með tali um að kíkja í pakkann; Íslandi sé langbest borgið sem sjálfstæðri þjóð og EES-samningurinn sé það besta úr Evrópusamstarfinu.",
"account": "aframisland",
"url": "https://www.tiktok.com/@afram.island/video/7659951824610266390",
"views": 11500,
"argKey": "adlogun",
"argTitle": "Viðræður eru aðlögun, ekki skoðun",
"argIcon": "📦"
},
{
"id": "7667913892995157270",
"side": "ja",
"title": "Hvernig hefurðu efni á að búa hér?",
"summary": "Vegfarendur lýsa háu verðlagi, sjö þúsund króna hamborgurum og telja engu að tapa á að skoða hvað aðild fæli í sér.",
"account": "sja",
"url": "https://www.tiktok.com/@jatiladsja/video/7667913892995157270",
"views": 31100,
"argKey": "kjor",
"argTitle": "Lægra verðlag og betri lífskjör",
"argIcon": "🛒"
},
{
"id": "7667924268507860246",
"side": "nei",
"title": "Skuldavandi Evrópu lendir á unga fólkinu",
"summary": "Anton Berg segir Frakkland hafa verið rekið með halla frá 1974 og Ítalíu og Spán nær samfellt í hálfa öld; með sameiginlegum skuldabréfum ESB lendi uppsafnaður skuldavandi stórríkjanna á komandi kynslóðum Íslendinga.",
"account": "aframisland",
"url": "https://www.tiktok.com/@afram.island/video/7667924268507860246",
"views": 6059,
"argKey": "efnahagur",
"argTitle": "Íslandi vegnar betur utan ESB",
"argIcon": "📈"
},
{
"id": "7674993405574860054",
"side": "ja",
"title": "Trúi á samtalið þótt markmiðin séu óskýr",
"summary": "Viðmælandi segist kjósa já því hann trúi á samtalið; fáránlegt væri að hlaupa frá borðinu og eiga ekki valmöguleikann þótt samningsmarkmiðin mættu vera skýrari.",
"account": "sja",
"url": "https://www.tiktok.com/@jatiladsja/video/7674993405574860054",
"views": 28800,
"argKey": "kikja",
"argTitle": "Kosið um viðræður — sjáum samninginn",
"argIcon": "📄"
},
{
"id": "7662744343182118166",
"side": "nei",
"title": "Fyrrverandi ESA-starfsmaður segir nei",
"summary": "Viðmælandi sem starfaði hjá ESA í Brussel segir dómsvald og löggjafarvald eiga að vera áfram hjá Íslendingum og lítur á atkvæðagreiðsluna sem fyrsta skrefið í átt að inngöngu í sambandið.",
"account": "aframisland",
"url": "https://www.tiktok.com/@afram.island/video/7662744343182118166",
"views": 3323,
"argKey": "fullveldi",
"argTitle": "Fullveldisframsal",
"argIcon": "🏛️"
},
{
"id": "7670892247927278870",
"side": "ja",
"title": "Já opnar tækifærin, nei lokar þeim",
"summary": "Vegfarendur nefna bjarta framtíð unga fólksins, efni á húsnæði, stöðugleika og að engu sé að tapa á aðildarviðræðum.",
"account": "evropuhreyfingin",
"url": "https://www.tiktok.com/@evropuhreyfingin/video/7670892247927278870",
"views": 27000,
"argKey": "taekifaeri",
"argTitle": "Tækifæri unga fólksins",
"argIcon": "🎓"
},
{
"id": "7663465724912045314",
"side": "nei",
"title": "Villi: Þetta er allt hægt hér heima",
"summary": "Villi segir verðtryggingu, vaxtaokur og fjármálakerfið mannanna verk sem íslenskir stjórnmálamenn geti lagað sjálfir án þess að framselja fullveldi til Brussel.",
"account": "aframisland",
"url": "https://www.tiktok.com/@afram.island/video/7663465724912045314",
"views": 1807,
"argKey": "fullveldi",
"argTitle": "Fullveldisframsal",
"argIcon": "🏛️"
},
{
"id": "7656464304027258134",
"side": "ja",
"title": "Upplýst ákvörðun fyrir komandi kynslóðir",
"summary": "Viðmælendur segja óábyrgt að fleygja tækifærum á glæ; með jái fáist að sjá hvað er í boði fyrir komandi kynslóðir.",
"account": "sja",
"url": "https://www.tiktok.com/@jatiladsja/video/7656464304027258134",
"views": 23900,
"argKey": "kikja",
"argTitle": "Kosið um viðræður — sjáum samninginn",
"argIcon": "📄"
},
{
"id": "7662744458651241750",
"side": "nei",
"title": "Ekki hægri-vinstri mál",
"summary": "Viðmælandi segir aðildarviðræður og inngöngu ekki aðskilda hluti; innganga þýði framsal löggjafarvalds, missi sjálfstæðrar peningastefnu og óskiptra yfirráða yfir auðlindum.",
"account": "aframisland",
"url": "https://www.tiktok.com/@afram.island/video/7662744458651241750",
"views": 2528,
"argKey": "adlogun",
"argTitle": "Viðræður eru aðlögun, ekki skoðun",
"argIcon": "📦"
},
{
"id": "7670577467458981142",
"side": "ja",
"title": "Andstæðingar geta líka sagt já",
"summary": "Bent á að jafnvel andstæðingar aðildar geti kosið já því kosningin snúist um aðildarviðræður, ekki endanlega aðild.",
"account": "evropuhreyfingin",
"url": "https://www.tiktok.com/@evropuhreyfingin/video/7670577467458981142",
"views": 23100,
"argKey": "kikja",
"argTitle": "Kosið um viðræður — sjáum samninginn",
"argIcon": "📄"
},
{
"id": "7662747505381133590",
"side": "nei",
"title": "Já þýðir umsókn um inngöngu",
"summary": "Viðmælandi segir vald eiga að vera sem næst fólkinu; já-atkvæði setji af stað umsóknarferli sem hljóti að fela í sér inngöngu og hann hafi ekki trú á undanþágum.",
"account": "aframisland",
"url": "https://www.tiktok.com/@afram.island/video/7662747505381133590",
"views": 19800,
"argKey": "spurning",
"argTitle": "Spurningin er villandi",
"argIcon": "❓"
},
{
"id": "7667586790752029974",
"side": "ja",
"title": "Stefnumót kostar en viska er máttur",
"summary": "Viðræðum líkt við stefnumót: kostnaðurinn sé ekki á glæ kastað því upplýsingarnar styrki stöðu Íslands og betra sé að skilja en að rífast.",
"account": "sja",
"url": "https://www.tiktok.com/@jatiladsja/video/7667586790752029974",
"views": 20400,
"argKey": "kikja",
"argTitle": "Kosið um viðræður — sjáum samninginn",
"argIcon": "📄"
},
{
"id": "7662453485853576470",
"side": "nei",
"title": "Fókusinn á að vera hér heima",
"summary": "Því er haldið fram að verið sé að biðja um umboð í margra ára, dýrt og tímafrekt ferli sem taki orku og fjármagn frá lífskjörum og efnahagsmálum heima fyrir.",
"account": "aframisland",
"url": "https://www.tiktok.com/@afram.island/video/7662453485853576470",
"views": 2948,
"argKey": "umbod",
"argTitle": "Ekkert umboð — svikin loforð",
"argIcon": "🗳️"
},
{
"id": "7675664550884085014",
"side": "ja",
"title": "Vaxtahækkun kostar þig 108 þúsund á ári",
"summary": "Vaxtahækkun í átta prósent sögð kosta heimili með 50 milljóna lán 9.000 krónur aukalega á mánuði; með evru fengist stöðugra og fyrirsjáanlegra efnahagslíf.",
"account": "evropuhreyfingin",
"url": "https://www.tiktok.com/@evropuhreyfingin/video/7675664550884085014",
"views": 16700,
"argKey": "vextir",
"argTitle": "Lægri vextir og stöðugur gjaldmiðill",
"argIcon": "💶"
},
{
"id": "7663506036854148374",
"side": "nei",
"title": "Villi: Kjark til eigin ákvarðana",
"summary": "Villi segir verðtryggingu, vaxtaokur og fjármálakerfið mannanna verk sem laga megi heima fyrir; stjórnmálamenn eigi ekki að láta þjóðina standa frammi fyrir framsali fullveldis til Brussel.",
"account": "aframisland",
"url": "https://www.tiktok.com/@afram.island/video/7663506036854148374",
"views": 1236,
"argKey": "fullveldi",
"argTitle": "Fullveldisframsal",
"argIcon": "🏛️"
},
{
"id": "7665329075925306646",
"side": "ja",
"title": "Króna eða evra?",
"summary": "Bent á að þeir sem noti evru borgi lægri vexti og að upplýsingarnar sem þurfi til ákvörðunar fáist aðeins með fullkláruðum samningi.",
"account": "sja",
"url": "https://www.tiktok.com/@jatiladsja/video/7665329075925306646",
"views": 16400,
"argKey": "vextir",
"argTitle": "Lægri vextir og stöðugur gjaldmiðill",
"argIcon": "💶"
},
{
"id": "7676015013470981398",
"side": "nei",
"title": "Georg: Reglubyrði hamlar nýsköpun",
"summary": "Georg, sem kveðst alþjóðasinni, telur ESB á rangri leið vegna regluvæðingar sem íþyngi nýsköpun; orkan eigi nú að fara í að ná niður verðbólgu og vöxtum og nýta gervigreind til verðmætasköpunar heima fyrir.",
"account": "aframisland",
"url": "https://www.tiktok.com/@afram.island/video/7676015013470981398",
"views": 877,
"argKey": "efnahagur",
"argTitle": "Íslandi vegnar betur utan ESB",
"argIcon": "📈"
},
{
"id": "7667326418098900246",
"side": "ja",
"title": "Lærum af Brexit — unga fólkið mæti",
"summary": "Rifjað upp að ungt fólk í Bretlandi var andvígt Brexit en mætti ekki á kjörstað; unga fólkið eigi að ráða framtíð sinni og mæta 29. ágúst.",
"account": "sja",
"url": "https://www.tiktok.com/@jatiladsja/video/7667326418098900246",
"views": 16400,
"argKey": "lydraedi",
"argTitle": "Þjóðin ráði ferðinni",
"argIcon": "🗳️"
},
{
"id": "7663503227169574166",
"side": "nei",
"title": "Chat Control: ESB vaktar skilaboðin",
"summary": "Því er haldið fram að ný ESB-löggjöf (Chat Control) heimili skönnun einkaskilaboða án dómsúrskurðar og að meirihluti atkvæða á Evrópuþinginu hafi verið hunsaður við afgreiðsluna.",
"account": "aframisland",
"url": "https://www.tiktok.com/@afram.island/video/7663503227169574166",
"views": 18400,
"argKey": "umbod",
"argTitle": "Ekkert umboð — svikin loforð",
"argIcon": "🗳️"
},
{
"id": "7668712372680379670",
"side": "ja",
"title": "ESB ver vinnandi fólk betur",
"summary": "Steinar Harðarson segir nánast allar framfarir í vinnuvernd hafa komið með tilskipunum ESB sem fjalli um öryggi og heilbrigði vinnandi fólks.",
"account": "evropuhreyfingin",
"url": "https://www.tiktok.com/@evropuhreyfingin/video/7668712372680379670",
"views": 16200,
"argKey": "kjor",
"argTitle": "Lægra verðlag og betri lífskjör",
"argIcon": "🛒"
},
{
"id": "7673439483164970262",
"side": "nei",
"title": "Ungt fólk borgar skuldir Evrópu",
"summary": "Því er haldið fram að Evrópa eldist og skuldir vaxi; lífeyrir sé víðast greiddur af skattgreiðendum dagsins ólíkt íslenska sjóðasöfnunarkerfinu, og þrýstingur á sameiginleg útgjöld ESB lendi á komandi kynslóðum.",
"account": "aframisland",
"url": "https://www.tiktok.com/@afram.island/video/7673439483164970262",
"views": 14800,
"argKey": "efnahagur",
"argTitle": "Íslandi vegnar betur utan ESB",
"argIcon": "📈"
},
{
"id": "7673869747431181590",
"side": "ja",
"title": "Má bjóða þér að koma inn og skoða?",
"summary": "Búðarlíking: stórar ákvarðanir séu erfiðar en enn erfiðari ef maður neitar að skoða það sem er í boði.",
"account": "sja",
"url": "https://www.tiktok.com/@jatiladsja/video/7673869747431181590",
"views": 16000,
"argKey": "kikja",
"argTitle": "Kosið um viðræður — sjáum samninginn",
"argIcon": "📄"
},
{
"id": "7664323552769772822",
"side": "nei",
"title": "Lærum af umsókninni 2009",
"summary": "Viðmælandi segir umsóknina 2009 hafa verið sótta með veiku lýðræðislegu umboði og gleypt orku stjórnkerfisins svo stjórnin féll; hann óttast að sama ferli endurtaki sig skref fyrir skref.",
"account": "aframisland",
"url": "https://www.tiktok.com/@afram.island/video/7664323552769772822",
"views": 5413,
"argKey": "umbod",
"argTitle": "Ekkert umboð — svikin loforð",
"argIcon": "🗳️"
},
{
"id": "7667531995718618370",
"side": "ja",
"title": "Allt upp á borðið fyrir upplýsta ákvörðun",
"summary": "Vegfarendur segjast vilja fá allt upp á borðið og taka upplýsta ákvörðun um aðild þegar samningur liggur fyrir.",
"account": "sja",
"url": "https://www.tiktok.com/@jatiladsja/video/7667531995718618370",
"views": 15400,
"argKey": "kikja",
"argTitle": "Kosið um viðræður — sjáum samninginn",
"argIcon": "📄"
},
{
"id": "7675644452425288982",
"side": "nei",
"title": "Arna: Engin óvissuferð til Brussel",
"summary": "Arna Páls vill ekki margra ára óvissuferð til Brussel; ríkisstjórnin eigi að sinna verkefnunum sem hún var kosin til að sinna — lækka vexti, ná niður verðbólgu og styrkja menntakerfið.",
"account": "aframisland",
"url": "https://www.tiktok.com/@afram.island/video/7675644452425288982",
"views": 2710,
"argKey": "umbod",
"argTitle": "Ekkert umboð — svikin loforð",
"argIcon": "🗳️"
},
{
"id": "7674992747379445014",
"side": "ja",
"title": "Sparsöm og hlakka til lægri vaxta",
"summary": "Par lýsir því hvernig það hefur efni á að búa á Íslandi og hlakkar til að borga lægri vexti.",
"account": "sja",
"url": "https://www.tiktok.com/@jatiladsja/video/7674992747379445014",
"views": 15000,
"argKey": "vextir",
"argTitle": "Lægri vextir og stöðugur gjaldmiðill",
"argIcon": "💶"
},
{
"id": "7666390297672289538",
"side": "nei",
"title": "Kerecis varð stórt því Ísland er lítið",
"summary": "Guðmundur Fertram segir Kerecis ekki hefðu orðið stærra eða betra fyrirtæki innan ESB; það hafi orðið alþjóðlegt einmitt vegna smæðar Íslands.",
"account": "aframisland",
"url": "https://www.tiktok.com/@afram.island/video/7666390297672289538",
"views": 2646,
"argKey": "efnahagur",
"argTitle": "Íslandi vegnar betur utan ESB",
"argIcon": "📈"
},
{
"id": "7674605302200765718",
"side": "ja",
"title": "Borgarðu sömu mjólkina þrisvar?",
"summary": "Verðtryggingin sögð sér-íslenskt afbrigði þar sem verðbólga bætist á höfuðstólinn; í evrulöndum sé verðbólga lægri og verðtrygging nánast óþekkt.",
"account": "sja",
"url": "https://www.tiktok.com/@jatiladsja/video/7674605302200765718",
"views": 13400,
"argKey": "vextir",
"argTitle": "Lægri vextir og stöðugur gjaldmiðill",
"argIcon": "💶"
},
{
"id": "7666764425356971286",
"side": "nei",
"title": "Smæð Íslands er samkeppnisforskot",
"summary": "Guðmundur Fertram segir það aldrei hafa reynst ókost að vera Íslendingur; smæðin sé samkeppnisforskot sem ekki eigi að afsala til Evrópusambandsins.",
"account": "aframisland",
"url": "https://www.tiktok.com/@afram.island/video/7666764425356971286",
"views": 2683,
"argKey": "efnahagur",
"argTitle": "Íslandi vegnar betur utan ESB",
"argIcon": "📈"
},
{
"id": "7662769792398445846",
"side": "ja",
"title": "370 þúsund manns án sætis við borðið",
"summary": "Á tímum innrásar Rússlands og fráhvarfs Bandaríkjanna standi Evrópa saman en fámenn þjóð eins og Ísland sitji ekki einu sinni við borðið.",
"account": "sja",
"url": "https://www.tiktok.com/@jatiladsja/video/7662769792398445846",
"views": 12900,
"argKey": "oryggi",
"argTitle": "Öryggi og skjól á óvissutímum",
"argIcon": "🛡️"
},
{
"id": "7671357271875538198",
"side": "nei",
"title": "EES: Fáum mest, gefum minnst",
"summary": "Því er haldið fram að Ísland sé alls ekki eitt á báti: EES-samningurinn veiti aðgang að innri markaðnum án þess að fórna fríverslunarsamningum, auðlindum og sjálfstjórn, en innganga þýddi 0,1% vægi og að reglugerðir frá Brussel tækju sjálfkrafa gildi.",
"account": "aframisland",
"url": "https://www.tiktok.com/@afram.island/video/7671357271875538198",
"views": 26100,
"argKey": "ees",
"argTitle": "EES dugar Íslandi vel",
"argIcon": "🤝"
},
{
"id": "7655362105553571094",
"side": "ja",
"title": "Ekki segja nei við óskrifuðum samningi",
"summary": "Ungt fólk á stofnfundi SJÁ segir ESB stórt tækifæri og vill taka upplýsta ákvörðun þegar samningur liggur fyrir í stað þess að hafna honum óséðum.",
"account": "sja",
"url": "https://www.tiktok.com/@jatiladsja/video/7655362105553571094",
"views": 11400,
"argKey": "kikja",
"argTitle": "Kosið um viðræður — sjáum samninginn",
"argIcon": "📄"
},
{
"id": "7666766074729270550",
"side": "nei",
"title": "Frumkvöðull: Tækifæri í smæðinni",
"summary": "Fyrirtækjastofnandi segir hagsmunum Íslendinga betur borgið utan sambandsins út frá viðskipta- og rekstrarsjónarmiðum; smæð landsins skapi nálægð og tækifæri í nýsköpun.",
"account": "aframisland",
"url": "https://www.tiktok.com/@afram.island/video/7666766074729270550",
"views": 8439,
"argKey": "efnahagur",
"argTitle": "Íslandi vegnar betur utan ESB",
"argIcon": "📈"
},
{
"id": "7659376066426932502",
"side": "ja",
"title": "Veit Sigmundur Davíð betur en Danir?",
"summary": "Vitnað er í kannanir þar sem 75–91% Dana, Íra og Svía telja sig betur setta innan ESB og spurt hvort Sigmundur Davíð viti betur en íbúarnir sjálfir.",
"account": "sja",
"url": "https://www.tiktok.com/@jatiladsja/video/7659376066426932502",
"views": 10600,
"argKey": "kjor",
"argTitle": "Lægra verðlag og betri lífskjör",
"argIcon": "🛒"
},
{
"id": "7675335871519853846",
"side": "nei",
"title": "Bjarnheiður: Eftir hverju sækjumst við?",
"summary": "Bjarnheiður Hallsdóttir segir Ísland fremst meðal Evrópuþjóða á mælikvörðum hagsældar, velsældar, jafnréttis og mannréttinda; aðildarvegferðin yrði þungbær, dýr og tímafrek og ESB leysi ekki tímabundin vandamál íslensks hagkerfis.",
"account": "aframisland",
"url": "https://www.tiktok.com/@afram.island/video/7675335871519853846",
"views": 1410,
"argKey": "efnahagur",
"argTitle": "Íslandi vegnar betur utan ESB",
"argIcon": "📈"
},
{
"id": "7674993327992753430",
"side": "ja",
"title": "Ódýrara að lifa í Hollandi en Íslandi",
"summary": "Maður búsettur í Hollandi lýsir því að þar taki enginn bílalán og að hærri tekjur þurfi á Íslandi fyrir sama lífsstandard.",
"account": "sja",
"url": "https://www.tiktok.com/@jatiladsja/video/7674993327992753430",
"views": 9386,
"argKey": "kjor",
"argTitle": "Lægra verðlag og betri lífskjör",
"argIcon": "🛒"
},
{
"id": "7666393760049253654",
"side": "nei",
"title": "Bóndi: Landbúnaði betur borgið utan ESB",
"summary": "Oddný Steina, bóndi og ráðunautur, segir landbúnað og matvælaframleiðslu á Íslandi betur borgið utan ESB og vill að Íslendingar framleiði mat sinn áfram.",
"account": "aframisland",
"url": "https://www.tiktok.com/@afram.island/video/7666393760049253654",
"views": 2520,
"argKey": "landbunadur",
"argTitle": "Landbúnaður í hættu",
"argIcon": "🚜"
},
{
"id": "7673898331961134358",
"side": "ja",
"title": "Við deilum gildum með Evrópu",
"summary": "Sólveig Arnarsdóttir segist hafa áttað sig í Berlín á mikilvægi þess að styrkja böndin við Evrópu því Íslendingar deili gildum með álfunni.",
"account": "evropuhreyfingin",
"url": "https://www.tiktok.com/@evropuhreyfingin/video/7673898331961134358",
"views": 9225,
"argKey": "gildi",
"argTitle": "Sameiginleg evrópsk gildi",
"argIcon": "🕊️"
},
{
"id": "7659552682511731990",
"side": "nei",
"title": "Til hvers var þá barist?",
"summary": "Brot af upphafsfundi Áfram Íslands þar sem spurt er í nafni horfinna kynslóða til hvers sjálfstæðisbaráttan hafi verið ef fullveldið verði framselt.",
"account": "aframisland",
"url": "https://www.tiktok.com/@afram.island/video/7659552682511731990",
"views": 11000,
"argKey": "fullveldi",
"argTitle": "Fullveldisframsal",
"argIcon": "🏛️"
},
{
"id": "7676070333169913110",
"side": "ja",
"title": "Spurningakeppni: já 29. ágúst",
"summary": "Létt spurningakeppni; lægri vöxtum sagt já takk, verðtrygging sögð ísköld og viðmælandi ætlar að segja já 29. ágúst.",
"account": "sja",
"url": "https://www.tiktok.com/@jatiladsja/video/7676070333169913110",
"views": 8144,
"argKey": "vextir",
"argTitle": "Lægri vextir og stöðugur gjaldmiðill",
"argIcon": "💶"
},
{
"id": "7672127514038340886",
"side": "nei",
"title": "Regluverk ESB fælir frumkvöðla burt",
"summary": "Því er haldið fram að evrópsk fyrirtæki hefji vegferð sína í Bandaríkjunum eða Asíu vegna íþyngjandi regluverks Evrópu sem haldi aftur af sköpun og frelsi frumkvöðla.",
"account": "aframisland",
"url": "https://www.tiktok.com/@afram.island/video/7672127514038340886",
"views": 3180,
"argKey": "efnahagur",
"argTitle": "Íslandi vegnar betur utan ESB",
"argIcon": "📈"
},
{
"id": "7674559683239218454",
"side": "ja",
"title": "Ákvarðanir sem börnin lifa lengst með",
"summary": "Barn vill ekki opna pakka og bent á að fullorðnir taki nú ákvarðanir sem móta framtíð þeirra sem yngri eru og þurfa að lifa lengst með þeim.",
"account": "sja",
"url": "https://www.tiktok.com/@jatiladsja/video/7674559683239218454",
"views": 7965,
"argKey": "kikja",
"argTitle": "Kosið um viðræður — sjáum samninginn",
"argIcon": "📄"
},
{
"id": "7672489051928153366",
"side": "nei",
"title": "Ísland séð með augum ungs fólks í ESB",
"summary": "Bent er á lágt atvinnuleysi, eina hæstu landsframleiðslu á mann í heimi og að fleiri ungir eignist húsnæði á Íslandi en víðast í Evrópu; árangurinn skýrist af því að Íslendingar hafi sjálfir tekið ákvarðanir sem henta Íslandi.",
"account": "aframisland",
"url": "https://www.tiktok.com/@afram.island/video/7672489051928153366",
"views": 8062,
"argKey": "efnahagur",
"argTitle": "Íslandi vegnar betur utan ESB",
"argIcon": "📈"
},
{
"id": "7661989806225820950",
"side": "ja",
"title": "100–150 þúsund krónum meira á mánuði",
"summary": "Fullyrt að íslensk heimili greiði 100–150 þúsund krónum meira á mánuði af húsnæðisláni en sambærileg evrópsk fjölskylda og því vilji sögumaður sjá samninginn.",
"account": "sja",
"url": "https://www.tiktok.com/@jatiladsja/video/7661989806225820950",
"views": 7653,
"argKey": "vextir",
"argTitle": "Lægri vextir og stöðugur gjaldmiðill",
"argIcon": "💶"
},
{
"id": "7674598302486236438",
"side": "nei",
"title": "Hvaða framtíð er verið að bjóða?",
"summary": "Bent er á að kaupmáttur ungs fólks á Íslandi sé 35% meiri en jafnaldra í ESB, atvinnuleysi lægra og fasteignakaup fyrr á ævinni; framtíð unga fólksins sé betur borgið undir eigin stjórn en hjá embættismönnum í Brussel.",
"account": "aframisland",
"url": "https://www.tiktok.com/@afram.island/video/7674598302486236438",
"views": 12600,
"argKey": "efnahagur",
"argTitle": "Íslandi vegnar betur utan ESB",
"argIcon": "📈"
},
{
"id": "7660170050233535766",
"side": "ja",
"title": "Mun Ísland hætta að vera Ísland?",
"summary": "Bent er á að Finnland, Ítalía og Danmörk haldi menningu sinni innan ESB og Ísland gæti því áfram verið stolt af sinni.",
"account": "sja",
"url": "https://www.tiktok.com/@jatiladsja/video/7660170050233535766",
"views": 7571,
"argKey": "hraedslu",
"argTitle": "Svar við hræðsluáróðri",
"argIcon": "📢"
},
{
"id": "7671445345691356438",
"side": "nei",
"title": "ESB ákveður hver má veiða",
"summary": "Því er haldið fram að ESB ákveði hver megi draga fisk úr sjó og geti hvenær sem er breytt reglum um úthlutun veiðiheimilda; vestur-evrópskar þjóðir hafi alda veiðireynslu á Íslandsmiðum og gætu því sótt sér aflaheimildir við Ísland.",
"account": "heimssyn",
"url": "https://www.tiktok.com/@heimssyn/video/7671445345691356438",
"views": 2309,
"argKey": "sjavarutvegur",
"argTitle": "Yfirráð yfir sjávarútvegi til Brussel",
"argIcon": "🎣"
},
{
"id": "7660171315877301526",
"side": "ja",
"title": "Hvað eiga Pútín og Halla sameiginlegt?",
"summary": "Farið er yfir Evrópukort og bent á að utan ESB-tengsla standi aðeins Hvíta-Rússland, Rússland og Ísland; Ísland eigi samleið með lýðræðisríkjum Evrópu.",
"account": "sja",
"url": "https://www.tiktok.com/@jatiladsja/video/7660171315877301526",
"views": 7035,
"argKey": "gildi",
"argTitle": "Sameiginleg evrópsk gildi",
"argIcon": "🕊️"
},
{
"id": "7662742094678904067",
"side": "nei",
"title": "Regluverkið myndi þyngjast enn meir",
"summary": "Ungur kjósandi segir íþyngjandi regluverk berast frá ESB gegnum EES og að það myndi aukast enn frekar við inngöngu; berjast þurfi fyrir sama málstað og sjálfstæðiskynslóðirnar.",
"account": "aframisland",
"url": "https://www.tiktok.com/@afram.island/video/7662742094678904067",
"views": 6401,
"argKey": "fullveldi",
"argTitle": "Fullveldisframsal",
"argIcon": "🏛️"
},
{
"id": "7654565445189815555",
"side": "ja",
"title": "Raddir af stofnfundi: af hverju já",
"summary": "Viðmælendur á stofnfundi SJÁ vilja sjá samning, láta þjóðina ráða framtíðinni og telja ESB fela í sér tækifæri fyrir ungt fólk.",
"account": "sja",
"url": "https://www.tiktok.com/@jatiladsja/video/7654565445189815555",
"views": 6813,
"argKey": "kikja",
"argTitle": "Kosið um viðræður — sjáum samninginn",
"argIcon": "📄"
},
{
"id": "7675508260417408278",
"side": "nei",
"title": "Ungt fólk: Betri staða á Íslandi",
"summary": "Ungir viðmælendur segja stöðu ungs fólks á Íslandi mun betri en í Evrópu og framtíðina betur borgið í eigin höndum; Íslandi hafi gengið vel síðustu 80 ár.",
"account": "aframisland",
"url": "https://www.tiktok.com/@afram.island/video/7675508260417408278",
"views": 9830,
"argKey": "efnahagur",
"argTitle": "Íslandi vegnar betur utan ESB",
"argIcon": "📈"
},
{
"id": "7672130164423183619",
"side": "ja",
"title": "Stöðugleiki, tækifæri og staðreyndir á borðið",
"summary": "Viðmælendur á Akureyri vilja vita hvort aðild auki stöðugleika í bankakerfinu, fá staðreyndir á borðið og grípa tækifæri í samstöðu Evrópuþjóða.",
"account": "sja",
"url": "https://www.tiktok.com/@jatiladsja/video/7672130164423183619",
"views": 6328,
"argKey": "kikja",
"argTitle": "Kosið um viðræður — sjáum samninginn",
"argIcon": "📄"
},
{
"id": "7675863248389836034",
"side": "nei",
"title": "Hilmar Veigar: Hnignun ESB í tölum",
"summary": "Hilmar Veigar Pétursson rekur að ESB hafi fallið úr stærsta hagkerfi heims 2014 niður fyrir Bandaríkin og Kína; framleiðni á vinnustund hafi vaxið um 7% á áratug á móti 18% í Bandaríkjunum og 12% á Íslandi og hlutdeild ESB í 100 stærstu fyrirtækjum heims fallið úr 20% í 8%.",
"account": "aframisland",
"url": "https://www.tiktok.com/@afram.island/video/7675863248389836034",
"views": 3383,
"argKey": "efnahagur",
"argTitle": "Íslandi vegnar betur utan ESB",
"argIcon": "📈"
},
{
"id": "7661990096576679191",
"side": "ja",
"title": "Er Ísland að missa fullveldið?",
"summary": "Leiðréttur sagður misskilningur: 29. ágúst sé aðeins ákveðið hvort ræða eigi við ESB og ekkert fullveldi tapist við það.",
"account": "sja",
"url": "https://www.tiktok.com/@jatiladsja/video/7661990096576679191",
"views": 5264,
"argKey": "hraedslu",
"argTitle": "Svar við hræðsluáróðri",
"argIcon": "📢"
},
{
"id": "7677244556454219030",
"side": "nei",
"title": "Bingó: er þetta ekki nóg?",
"summary": "Farið yfir lista gegn aðild í bingóstíl: chat control-eftirlit, 0,08% atkvæðavægi, sameiginleg sjávarútvegsstefna, tollabandalag og 15 milljarða árleg útgjöld.",
"account": "aframisland",
"url": "https://www.tiktok.com/@afram.island/video/7677244556454219030",
"views": 268,
"argKey": "ahrifaleysi",
"argTitle": "Hverfandi vægi smáríkis",
"argIcon": "🤏"
},
{
"id": "7666090618019613954",
"side": "ja",
"title": "Hver er kostnaðurinn við að breyta engu?",
"summary": "Kostnaði við að klára viðræður er stillt upp á móti því að borga af fasteignalánum á hæstu vöxtum Evrópu ævilangt.",
"account": "sja",
"url": "https://www.tiktok.com/@jatiladsja/video/7666090618019613954",
"views": 4949,
"argKey": "vextir",
"argTitle": "Lægri vextir og stöðugur gjaldmiðill",
"argIcon": "💶"
},
{
"id": "7676015144165477634",
"side": "nei",
"title": "Guðmundur: Tökum enga áhættu",
"summary": "Guðmundur segir Íslendingum hafa gengið ævintýralega vel sem sjálfstæðri þjóð, bæði í hagsæld og réttindum, og vill ekki taka neina áhættu með því fyrir inngöngu í ESB.",
"account": "aframisland",
"url": "https://www.tiktok.com/@afram.island/video/7676015144165477634",
"views": 1096,
"argKey": "efnahagur",
"argTitle": "Íslandi vegnar betur utan ESB",
"argIcon": "📈"
},
{
"id": "7656066080955321622",
"side": "ja",
"title": "Vil sjá samning og sterkari gjaldmiðil",
"summary": "Viðmælendur vilja fá samning á borðið áður en afstaða er tekin og einn vill sterkari gjaldmiðil sem hrynur ekki í stað krónunnar.",
"account": "sja",
"url": "https://www.tiktok.com/@jatiladsja/video/7656066080955321622",
"views": 4884,
"argKey": "kikja",
"argTitle": "Kosið um viðræður — sjáum samninginn",
"argIcon": "📄"
},
{
"id": "7676190550101347606",
"side": "nei",
"title": "Draghi-skýrslan dregur upp dökka mynd",
"summary": "Draghi-skýrslan um samkeppnishæfni Evrópu sögð sýna að álfan dragist aftur úr og flókið regluverk hamli fyrirtækjum; rangur tími fyrir Ísland að binda sig fastar við kerfið.",
"account": "aframisland",
"url": "https://www.tiktok.com/@afram.island/video/7676190550101347606",
"views": 1947,
"argKey": "efnahagur",
"argTitle": "Íslandi vegnar betur utan ESB",
"argIcon": "📈"
},
{
"id": "7660171516000341250",
"side": "ja",
"title": "Búa hjá foreldrum til þrítugs?",
"summary": "Ungt fólk komist ekki inn á fasteignamarkaðinn og spurt er hvort lægri vextir séu mögulegir; þess vegna vilji sögumaður sjá samninginn.",
"account": "sja",
"url": "https://www.tiktok.com/@jatiladsja/video/7660171516000341250",
"views": 4663,
"argKey": "vextir",
"argTitle": "Lægri vextir og stöðugur gjaldmiðill",
"argIcon": "💶"
},
{
"id": "7676422473881095446",
"side": "nei",
"title": "Ísak: stöndum okkur betur utan ESB",
"summary": "Ísak bendir á að Ísland sé efst í mælikvörðum um lífskjör og efnahagsmál og spyr hvers vegna ætti að ganga í ESB þegar landið standi sig betur en aðildarríkin.",
"account": "aframisland",
"url": "https://www.tiktok.com/@afram.island/video/7676422473881095446",
"views": 1911,
"argKey": "efnahagur",
"argTitle": "Íslandi vegnar betur utan ESB",
"argIcon": "📈"
},
{
"id": "7676065516049566978",
"side": "ja",
"title": "Spurningakeppni: lægri vextir, já takk",
"summary": "Létt spurningakeppni þar sem lægri vöxtum er fagnað og verðtrygging sögð köld; já í ágúst þýði ekki inngöngu í ESB heldur aðeins að skoða möguleikana.",
"account": "sja",
"url": "https://www.tiktok.com/@jatiladsja/video/7676065516049566978",
"views": 4553,
"argKey": "vextir",
"argTitle": "Lægri vextir og stöðugur gjaldmiðill",
"argIcon": "💶"
},
{
"id": "7676492455822314774",
"side": "nei",
"title": "Georg: ESB á rangri leið",
"summary": "Georg segist alþjóðasinni en telji ESB á rangri leið, sérstaklega vegna regluverksbyrðar á nýsköpun.",
"account": "aframisland",
"url": "https://www.tiktok.com/@afram.island/video/7676492455822314774",
"views": 1152,
"argKey": "efnahagur",
"argTitle": "Íslandi vegnar betur utan ESB",
"argIcon": "📈"
},
{
"id": "7675297992273939715",
"side": "ja",
"title": "Yfirráð yfir auðlindinni yrðu tryggð",
"summary": "Spiluð eldri ummæli um að í umsókn kæmi fram að Ísland gengi ekki í sambandið nema yfirráð yfir auðlindinni yrðu tryggð með skýrum hætti.",
"account": "sja",
"url": "https://www.tiktok.com/@jatiladsja/video/7675297992273939715",
"views": 4075,
"argKey": "serlausnir",
"argTitle": "Sérlausnir raunhæfar — kvótinn íslenskur",
"argIcon": "🐟"
},
{
"id": "7662744621553814806",
"side": "nei",
"title": "Íslendingar ráði yfir Íslandi",
"summary": "Ung kona segir kosninguna snúast um að vernda fullveldið, krónuna og gjaldmiðilinn; 27 þjóðir hafi gengið í gegnum aðildarferlið og engin fengið sérstakan samning.",
"account": "aframisland",
"url": "https://www.tiktok.com/@afram.island/video/7662744621553814806",
"views": 5939,
"argKey": "fullveldi",
"argTitle": "Fullveldisframsal",
"argIcon": "🏛️"
},
{
"id": "7675426028856069398",
"side": "ja",
"title": "Snærós: lygar og hálfsannleikur nei-hliðarinnar",
"summary": "Snærós Sindradóttir segir nei-hliðina ljúga um að kosið sé um aðild, um kostnað Íslands og áhrifaleysi, og horfa aldrei á heildarávinning þjóðarinnar.",
"account": "evropuhreyfingin",
"url": "https://www.tiktok.com/@evropuhreyfingin/video/7675426028856069398",
"views": 3749,
"argKey": "hraedslu",
"argTitle": "Svar við hræðsluáróðri",
"argIcon": "📢"
},
{
"id": "7671687286064434454",
"side": "nei",
"title": "800 milljarðar evra í hernaðaruppbyggingu",
"summary": "Bent er á Readiness 2030 áætlun ESB upp á 800 milljarða evra í varnarmál; með aðild þyrfti Ísland að taka þátt í sameiginlegum fjárlögum sambandsins og greiða fyrir vopnakaup.",
"account": "aframisland",
"url": "https://www.tiktok.com/@afram.island/video/7671687286064434454",
"views": 6261,
"argKey": "hervaeding",
"argTitle": "Hervæðing ESB",
"argIcon": "☮️"
},
{
"id": "7659377265158917378",
"side": "ja",
"title": "Tollafgreiðslan er vesen fyrir alla",
"summary": "Sögð saga af flutningamanni sem vill ekki tollabandalag því tollafgreiðsla sé tekjulind; sögumanni finnst það ekki góð ástæða til að viðhalda veseni fyrir aðra.",
"account": "sja",
"url": "https://www.tiktok.com/@jatiladsja/video/7659377265158917378",
"views": 3747,
"argKey": "tollfrelsi",
"argTitle": "Tollfrelsi og fullvinnsla heima",
"argIcon": "🏭"
},
{
"id": "7667161381535223062",
"side": "nei",
"title": "Bóndi: Verndum landbúnaðinn",
"summary": "Margrét Hrund, bóndi, segist ætla að segja nei til að vernda íslenskan landbúnað og hvetur til samstöðu um hann.",
"account": "aframisland",
"url": "https://www.tiktok.com/@afram.island/video/7667161381535223062",
"views": 8829,
"argKey": "landbunadur",
"argTitle": "Landbúnaður í hættu",
"argIcon": "🚜"
},
{
"id": "7675174586291424534",
"side": "ja",
"title": "Finnskir bændur fá grunnstuðning frá ESB",
"summary": "Leiðrétt sú fullyrðing að Finnar borgi bændum sínum sjálfir: grunnstuðningur upp á 875 milljónir evra komi frá ESB og stuðningur við íslenska bændur gæti einnig komið frá Evrópu.",
"account": "sja",
"url": "https://www.tiktok.com/@jatiladsja/video/7675174586291424534",
"views": 3560,
"argKey": "hraedslu",
"argTitle": "Svar við hræðsluáróðri",
"argIcon": "📢"
},
{
"id": "7672064724321783062",
"side": "nei",
"title": "Þrjár ástæður til að segja nei",
"summary": "Þrjár ástæður eru gefnar: Íslandi hafi aldrei gengið betur en sem fullvalda þjóð, vald eigi að vera nálægt borgurunum en ekki hjá 450 milljóna sambandi, og íslenskur landbúnaður stæðist ekki samkeppni með tilheyrandi áhættu fyrir fæðuöryggi.",
"account": "aframisland",
"url": "https://www.tiktok.com/@afram.island/video/7672064724321783062",
"views": 28900,
"argKey": "fullveldi",
"argTitle": "Fullveldisframsal",
"argIcon": "🏛️"
},
{
"id": "7671970128216575254",
"side": "ja",
"title": "NATO ver ekki netkapla og orkuöryggi",
"summary": "Varnarsamningurinn og NATO dugi við innrás en öryggi snúist í dag einnig um orku-, net- og innviðaöryggi þar sem full aðild að ESB myndi auka öryggi Íslands.",
"account": "evropuhreyfingin",
"url": "https://www.tiktok.com/@evropuhreyfingin/video/7671970128216575254",
"views": 3371,
"argKey": "oryggi",
"argTitle": "Öryggi og skjól á óvissutímum",
"argIcon": "🛡️"
},
{
"id": "7673045694944431382",
"side": "nei",
"title": "Herlaus þjóð, ekki hervæðing",
"summary": "Sunna Björg segir Ísland stolta herlausa þjóð sem eigi að beita sér fyrir friði á alþjóðavettvangi en ekki taka þátt í aukinni hervæðingu.",
"account": "aframisland",
"url": "https://www.tiktok.com/@afram.island/video/7673045694944431382",
"views": 2285,
"argKey": "hervaeding",
"argTitle": "Hervæðing ESB",
"argIcon": "☮️"
},
{
"id": "7675174221017894166",
"side": "ja",
"title": "En hvað með fiskinn okkar?",
"summary": "Vísað í ummæli sjávarútvegsstjóra ESB í Financial Times um svigrúm til sérlausna fyrir Ísland og fordæmi Möltu með 25 mílna svæði.",
"account": "sja",
"url": "https://www.tiktok.com/@jatiladsja/video/7675174221017894166",
"views": 3310,
"argKey": "serlausnir",
"argTitle": "Sérlausnir raunhæfar — kvótinn íslenskur",
"argIcon": "🐟"
},
{
"id": "7674259051055697174",
"side": "nei",
"title": "Hvað er líklegt í samningaviðræðum?",
"summary": "Rökstutt er að ólíklegt sé að fátækari aðildarríki sætti sig við að ein ríkasta þjóð Evrópu taki meira úr sjóðum ESB en hún greiðir, og að 27 þjóðir með 450 milljónir íbúa veiti 400.000 manna þjóð varanlegar undanþágur frá reglum sínum.",
"account": "aframisland",
"url": "https://www.tiktok.com/@afram.island/video/7674259051055697174",
"views": 7204,
"argKey": "undanthagur",
"argTitle": "Engar varanlegar undanþágur",
"argIcon": "🚫"
},
{
"id": "7672898909391326486",
"side": "ja",
"title": "A-liðið í samninganefnd Íslands",
"summary": "Treyst er á að ríkisstjórnin skipi bestu mögulegu samningamenn, líka erlenda ef þarf, fari málið lengra.",
"account": "sja",
"url": "https://www.tiktok.com/@jatiladsja/video/7672898909391326486",
"views": 2856,
"argKey": "serlausnir",
"argTitle": "Sérlausnir raunhæfar — kvótinn íslenskur",
"argIcon": "🐟"
},
{
"id": "7672406521677909270",
"side": "nei",
"title": "Land auðlinda og hreinnar náttúru",
"summary": "Viðmælandi segir Ísland land auðlinda og hreinnar náttúru með landbúnað í fremstu röð; nýta eigi tækifærin á eigin forsendum og njóta ávinningsins af þeim.",
"account": "aframisland",
"url": "https://www.tiktok.com/@afram.island/video/7672406521677909270",
"views": 4322,
"argKey": "fullveldi",
"argTitle": "Fullveldisframsal",
"argIcon": "🏛️"
},
{
"id": "7654938291543985411",
"side": "ja",
"title": "Kristrún: sjáum samninginn og tækifærin",
"summary": "Kristrún Frostadóttir forsætisráðherra segist ætla að kjósa já; ákvörðunin sé þjóðarinnar og þeir sem vilji aukna samkeppni, gengisstöðugleika og lægri tolla ættu að vilja sjá samninginn.",
"account": "evropuhreyfingin",
"url": "https://www.tiktok.com/@evropuhreyfingin/video/7654938291543985411",
"views": 2762,
"argKey": "kikja",
"argTitle": "Kosið um viðræður — sjáum samninginn",
"argIcon": "📄"
},
{
"id": "7674762323612962070",
"side": "nei",
"title": "Veistu hvað ESB-aðild kostar?",
"summary": "Vegfarendur eru spurðir hvað aðild að ESB kosti á ári; fæstir vita svarið, sem sagt er vera um 50 milljarðar króna á ári.",
"account": "aframisland",
"url": "https://www.tiktok.com/@afram.island/video/7674762323612962070",
"views": 49800,
"argKey": "kostnadur",
"argTitle": "Mikill beinn kostnaður",
"argIcon": "💸"
},
{
"id": "7652329105341402390",
"side": "ja",
"title": "Sjálfstæð þjóð situr við borðið",
"summary": "Þjóðhátíðarkveðja: sjálfstæð þjóð sitji við borðið þar sem ákvarðanir um hana eru teknar.",
"account": "evropuhreyfingin",
"url": "https://www.tiktok.com/@evropuhreyfingin/video/7652329105341402390",
"views": 2567,
"argKey": "ahrif",
"argTitle": "Sæti við borðið í stað EES-áhrifaleysis",
"argIcon": "🪑"
},
{
"id": "7662747631868808470",
"side": "nei",
"title": "0,1% vægi í ráðherraráðinu",
"summary": "Fundargestur vísar í ræðu Ólafs Ragnars Grímssonar: fullveldið úr sjálfstæðisbaráttunni yrði framselt til 70.000 embættis- og hagsmunavarða í Brussel og Ísland fengi aðeins 0,1% atkvæðavægi í ráðherraráðinu.",
"account": "aframisland",
"url": "https://www.tiktok.com/@afram.island/video/7662747631868808470",
"views": 16300,
"argKey": "fullveldi",
"argTitle": "Fullveldisframsal",
"argIcon": "🏛️"
},
{
"id": "7676459949051956502",
"side": "ja",
"title": "Fullveldið styrkist með sæti við borðið",
"summary": "Fullveldi sagt tvenns konar: Ísland ráði áfram sínum innri málum en fylgi í dag regluverki ESB án áhrifa; með aðild fengist sæti við borðið og fullveldið ykist.",
"account": "evropuhreyfingin",
"url": "https://www.tiktok.com/@evropuhreyfingin/video/7676459949051956502",
"views": 2423,
"argKey": "ahrif",
"argTitle": "Sæti við borðið í stað EES-áhrifaleysis",
"argIcon": "🪑"
},
{
"id": "7675393474169998614",
"side": "nei",
"title": "Bjarnheiður: EES-kostir án ægivalds",
"summary": "Bjarnheiður segir EES-samninginn færa Íslandi gríðarlega kosti; með inngöngu í ESB gæti lokast á aðra viðskiptasamninga og landið kæmist undir ægivald sambandsins í stað þess að stjórna auðlindum sínum sjálft.",
"account": "aframisland",
"url": "https://www.tiktok.com/@afram.island/video/7675393474169998614",
"views": 1246,
"argKey": "ees",
"argTitle": "EES dugar Íslandi vel",
"argIcon": "🤝"
},
{
"id": "7676070874637700374",
"side": "ja",
"title": "Bull að fullveldið tapist",
"summary": "Fullyrðing um fullveldistap sögð bull; 27 ESB-þjóðir hafi ekki misst fullveldi sitt og með aðild fengi Ísland loks fulltrúa í stað þess að taka við EES-reglum án áhrifa.",
"account": "sja",
"url": "https://www.tiktok.com/@jatiladsja/video/7676070874637700374",
"views": 1149,
"argKey": "hraedslu",
"argTitle": "Svar við hræðsluáróðri",
"argIcon": "📢"
},
{
"id": "7667159897917656342",
"side": "nei",
"title": "Sviss beygir sig ekki fyrir neinum",
"summary": "Því er haldið fram að þjóðum farnist best sem leiti ekki í skjól hinna stóru; Sviss haldi sjálfstæði sínu og fari sínu fram utan bandalaga.",
"account": "aframisland",
"url": "https://www.tiktok.com/@afram.island/video/7667159897917656342",
"views": 7914,
"argKey": "nagrannar",
"argTitle": "Ekkert nágrannaland í ESB",
"argIcon": "🧭"
},
{
"id": "7677242348153130262",
"side": "ja",
"title": "Lárus Welding: mikið upside, ekkert downside",
"summary": "Lárus Welding segir já-kostinn hafa miklu meira upside en downside; Ísland eigi að vera með í samtalinu í ljósi stöðu heimsmála og samningur færi hvort sem er aftur til þjóðarinnar.",
"account": "sja",
"url": "https://www.tiktok.com/@jatiladsja/video/7677242348153130262",
"views": 676,
"argKey": "kikja",
"argTitle": "Kosið um viðræður — sjáum samninginn",
"argIcon": "📄"
},
{
"id": "7659941218507345174",
"side": "nei",
"title": "Ungt fólk: Hagsmunum betur borgið utan ESB",
"summary": "Ungur viðmælandi segir EES-samninginn veita aðgang að innri markaðnum með helstu kostum aðildar án gallanna og að kosningin snúist um framtíð unga fólksins.",
"account": "aframisland",
"url": "https://www.tiktok.com/@afram.island/video/7659941218507345174",
"views": 8013,
"argKey": "ees",
"argTitle": "EES dugar Íslandi vel",
"argIcon": "🤝"
},
{
"id": "7674993889694059798",
"side": "ja",
"title": "Aðildarviðræður eða Eurovision — hvort er dýrara?",
"summary": "Kostnaður við aðildarviðræður, 1,9 milljarður, settur í samhengi við pizzur, Eurovision og önnur útgjöld; góður samningur vari að eilífu.",
"account": "evropuhreyfingin",
"url": "https://www.tiktok.com/@evropuhreyfingin/video/7674993889694059798",
"views": 14500,
"argKey": "kikja",
"argTitle": "Kosið um viðræður — sjáum samninginn",
"argIcon": "📄"
},
{
"id": "7660171617468730646",
"side": "ja",
"title": "Myndirðu segja nei við Kylie Jenner?",
"summary": "Stefnumótalíking: 29. ágúst sé ekki verið að giftast ESB heldur aðeins að kynnast og skoða hvað gæti orðið.",
"account": "sja",
"url": "https://www.tiktok.com/@jatiladsja/video/7660171617468730646",
"views": 14100,
"argKey": "kikja",
"argTitle": "Kosið um viðræður — sjáum samninginn",
"argIcon": "📄"
},
{
"id": "7674605475031239958",
"side": "ja",
"title": "Norðmenn fengu samning og sögðu nei",
"summary": "Bent á að Norðmenn hafi tvisvar fellt aðildarsamning í þjóðaratkvæði án afleiðinga; já 29. ágúst þýði ekki aðild heldur að þjóðin kjósi aftur um sjálfan samninginn.",
"account": "sja",
"url": "https://www.tiktok.com/@jatiladsja/video/7674605475031239958",
"views": 13600,
"argKey": "kikja",
"argTitle": "Kosið um viðræður — sjáum samninginn",
"argIcon": "📄"
},
{
"id": "7667912143718599958",
"side": "ja",
"title": "Þú mátar peysuna áður en þú kaupir",
"summary": "Kosningin 29. ágúst snúist um að fá samning á borðið, lesa hann og taka upplýsta ákvörðun.",
"account": "sja",
"url": "https://www.tiktok.com/@jatiladsja/video/7667912143718599958",
"views": 9938,
"argKey": "kikja",
"argTitle": "Kosið um viðræður — sjáum samninginn",
"argIcon": "📄"
},
{
"id": "7675313034969009430",
"side": "ja",
"title": "Af hverju ekki að reyna og skoða?",
"summary": "Veiðilíking: sá sem þorir ekki að kasta fær aldrei fisk; reyna, skoða, spyrja og ákveða svo.",
"account": "sja",
"url": "https://www.tiktok.com/@jatiladsja/video/7675313034969009430",
"views": 9439,
"argKey": "kikja",
"argTitle": "Kosið um viðræður — sjáum samninginn",
"argIcon": "📄"
},
{
"id": "7674988704733154563",
"side": "ja",
"title": "Erfitt að velja án þess að skoða",
"summary": "Veitingalíking: ekki þurfi að ákveða neitt strax, aðeins að skoða valkostina sem eru í boði.",
"account": "sja",
"url": "https://www.tiktok.com/@jatiladsja/video/7674988704733154563",
"views": 8958,
"argKey": "kikja",
"argTitle": "Kosið um viðræður — sjáum samninginn",
"argIcon": "📄"
},
{
"id": "7661281508295986454",
"side": "ja",
"title": "Myndirðu ekki opna happatreyjuna?",
"summary": "Líking um happatreyju: enginn hendir pakka óopnuðum og því eigi að opna og skoða hvað kemur upp úr honum.",
"account": "sja",
"url": "https://www.tiktok.com/@jatiladsja/video/7661281508295986454",
"views": 8897,
"argKey": "kikja",
"argTitle": "Kosið um viðræður — sjáum samninginn",
"argIcon": "📄"
},
{
"id": "7654914276515138838",
"side": "ja",
"title": "Segjum já og sjáum hvað kemur út",
"summary": "Viðmælendur segja að aldrei fáist úr því skorið hvernig aðild liti út nema klára viðræður; galið sé að loka glugganum sem nú standi opinn.",
"account": "sja",
"url": "https://www.tiktok.com/@jatiladsja/video/7654914276515138838",
"views": 8561,
"argKey": "kikja",
"argTitle": "Kosið um viðræður — sjáum samninginn",
"argIcon": "📄"
},
{
"id": "7655693715071126806",
"side": "ja",
"title": "Ég vil sjá hvað er í boði",
"summary": "Viðmælendur segjast ætla að kjósa já til að sjá hvað er í boði og taka upplýsta ákvörðun út frá því.",
"account": "sja",
"url": "https://www.tiktok.com/@jatiladsja/video/7655693715071126806",
"views": 8063,
"argKey": "kikja",
"argTitle": "Kosið um viðræður — sjáum samninginn",
"argIcon": "📄"
},
{
"id": "7671734303268736258",
"side": "ja",
"title": "Akureyri: já til að sjá samninginn",
"summary": "Viðmælendur á viðburði SJÁ á Akureyri vilja sjá samninginn í stað þess að segja nei við einhverju sem enginn veit hvað er.",
"account": "sja",
"url": "https://www.tiktok.com/@jatiladsja/video/7671734303268736258",
"views": 8059,
"argKey": "kikja",
"argTitle": "Kosið um viðræður — sjáum samninginn",
"argIcon": "📄"
},
{
"id": "7675746321218718998",
"side": "ja",
"title": "Kaus já í Kringlunni",
"summary": "Gamansaga af manni sem kaus utan kjörfundar í Kringlunni því hann vill sjá og kíkja á samninginn.",
"account": "sja",
"url": "https://www.tiktok.com/@jatiladsja/video/7675746321218718998",
"views": 7707,
"argKey": "kikja",
"argTitle": "Kosið um viðræður — sjáum samninginn",
"argIcon": "📄"
},
{
"id": "7672393856037555478",
"side": "ja",
"title": "Kveðum drauginn niður í eitt skipti",
"summary": "Villi vandræðaskáld segir að ESB-draugurinn verði aldrei kveðinn niður nema þjóðin fái að vita hvað er í boði og taki svo afstöðu.",
"account": "sja",
"url": "https://www.tiktok.com/@jatiladsja/video/7672393856037555478",
"views": 6773,
"argKey": "kikja",
"argTitle": "Kosið um viðræður — sjáum samninginn",
"argIcon": "📄"
},
{
"id": "7668646652328135958",
"side": "ja",
"title": "Engin stór ákvörðun án upplýsinga",
"summary": "Sögumaður tæki aldrei mikilvæga ákvörðun um vinnu, nám eða íbúð án upplýsinga og 29. ágúst sé kosið um að fá samning á borðið.",
"account": "sja",
"url": "https://www.tiktok.com/@jatiladsja/video/7668646652328135958",
"views": 6763,
"argKey": "kikja",
"argTitle": "Kosið um viðræður — sjáum samninginn",
"argIcon": "📄"
},
{
"id": "7676790323875564822",
"side": "ja",
"title": "Fótboltasamningur útskýrir já-ið",
"summary": "Fyrrverandi atvinnumaður líkir atkvæðagreiðslunni við tilboð frá Hammarby 1995: já þýði aðeins að heyra hvað býðst, fullbúinn samningur fari svo aftur í þjóðaratkvæðagreiðslu.",
"account": "sja",
"url": "https://www.tiktok.com/@jatiladsja/video/7676790323875564822",
"views": 4586,
"argKey": "kikja",
"argTitle": "Kosið um viðræður — sjáum samninginn",
"argIcon": "📄"
},
{
"id": "7665328778377284886",
"side": "ja",
"title": "Kosning unga fólksins um framtíð Íslands",
"summary": "Ungt fólk hvatt til að mæta á kjörstað; eina leiðin til að fá upplýsingarnar sé að kjósa já, fá samninginn og meta kosti og galla.",
"account": "sja",
"url": "https://www.tiktok.com/@jatiladsja/video/7665328778377284886",
"views": 4486,
"argKey": "kikja",
"argTitle": "Kosið um viðræður — sjáum samninginn",
"argIcon": "📄"
},
{
"id": "7675174901036207382",
"side": "ja",
"title": "Ungt fólk, mætum og kjósum",
"summary": "Ungt fólk hvatt til að mæta á kjörstað 29. ágúst; kosningin snúist um næstu 30–40 ár, húsnæðismál og framtíð þeirra sem lengst lifa með niðurstöðunni.",
"account": "sja",
"url": "https://www.tiktok.com/@jatiladsja/video/7675174901036207382",
"views": 4399,
"argKey": "lydraedi",
"argTitle": "Þjóðin ráði ferðinni",
"argIcon": "🗳️"
},
{
"id": "7674605156620619030",
"side": "ja",
"title": "Minnsti gjaldmiðill heims ber áhættuálag",
"summary": "Útskýrt að vextir og verð séu hærri á Íslandi því bankar leggi áhættuálag á minnsta sjálfstæða gjaldmiðil heims — álag sem enginn kaus.",
"account": "sja",
"url": "https://www.tiktok.com/@jatiladsja/video/7674605156620619030",
"views": 3954,
"argKey": "vextir",
"argTitle": "Lægri vextir og stöðugur gjaldmiðill",
"argIcon": "💶"
},
{
"id": "7667915213399788822",
"side": "ja",
"title": "Utankjörfundaratkvæðagreiðsla er hafin",
"summary": "Bent á að hægt sé að kjósa utan kjörfundar strax í dag og hvatt til að segja já til að sjá samning.",
"account": "sja",
"url": "https://www.tiktok.com/@jatiladsja/video/7667915213399788822",
"views": 3851,
"argKey": "kikja",
"argTitle": "Kosið um viðræður — sjáum samninginn",
"argIcon": "📄"
},
{
"id": "7656800291576139030",
"side": "ja",
"title": "Forvitni er grundvöllur framfara",
"summary": "Viðmælendur segja forvitni mannkost, vilja sjá lokasamning og tækifæri unga fólksins — og hrópa húrra fyrir lægri vöxtum.",
"account": "sja",
"url": "https://www.tiktok.com/@jatiladsja/video/7656800291576139030",
"views": 3694,
"argKey": "kikja",
"argTitle": "Kosið um viðræður — sjáum samninginn",
"argIcon": "📄"
},
{
"id": "7660171018144615702",
"side": "ja",
"title": "Kosið um viðræður, ekki aðild",
"summary": "Útskýrt er að atkvæðagreiðslan snúist um að hefja viðræður; náist samningur verði kosið aftur um hann sjálfan.",
"account": "sja",
"url": "https://www.tiktok.com/@jatiladsja/video/7660171018144615702",
"views": 3140,
"argKey": "kikja",
"argTitle": "Kosið um viðræður — sjáum samninginn",
"argIcon": "📄"
},
{
"id": "7676070372554312982",
"side": "ja",
"title": "Bull að atvinnuleysi aukist",
"summary": "Fullyrðing um aukið atvinnuleysi við inngöngu sögð bull; lönd eins og Lettland, Litáen, Pólland og Írland hafi upplifað minna atvinnuleysi eftir inngöngu í ESB.",
"account": "sja",
"url": "https://www.tiktok.com/@jatiladsja/video/7676070372554312982",
"views": 3035,
"argKey": "hraedslu",
"argTitle": "Svar við hræðsluáróðri",
"argIcon": "📢"
},
{
"id": "7660085595561020694",
"side": "ja",
"title": "Er þín skoðun byggð á skoðun?",
"summary": "Guðni Th. segir að á undan skoðun ætti að koma skoðun málsins; of algengt sé að fólk myndi sér skoðun án þess að kynna sér málin.",
"account": "evropuhreyfingin",
"url": "https://www.tiktok.com/@evropuhreyfingin/video/7660085595561020694",
"views": 2533,
"argKey": "kikja",
"argTitle": "Kosið um viðræður — sjáum samninginn",
"argIcon": "📄"
},
{
"id": "7653467162643893526",
"side": "ja",
"title": "Samningsmarkmið Íslands lesin upp",
"summary": "Lesin upp ítarleg samningsmarkmið um yfirráð yfir orku- og fiskveiðiauðlindum, vernd landbúnaðar, byggðafjármagn og áfram herlaust land.",
"account": "evropuhreyfingin",
"url": "https://www.tiktok.com/@evropuhreyfingin/video/7653467162643893526",
"views": 2477,
"argKey": "serlausnir",
"argTitle": "Sérlausnir raunhæfar — kvótinn íslenskur",
"argIcon": "🐟"
},
{
"id": "7671331211519757590",
"side": "ja",
"title": "Enginn Evrópuher er til",
"summary": "Fullyrðingar nei-hliðar um að aðild þvingi Ísland í evrópskan her sagðar ósannindi; enginn Evrópuher sé til og varnarmál séu á forræði hvers aðildarríkis.",
"account": "evropuhreyfingin",
"url": "https://www.tiktok.com/@evropuhreyfingin/video/7671331211519757590",
"views": 2381,
"argKey": "hraedslu",
"argTitle": "Svar við hræðsluáróðri",
"argIcon": "📢"
},
{
"id": "7649716156454030614",
"side": "ja",
"title": "Hverra hagsmuna gætir krónan?",
"summary": "Guðrún Johnsen prófessor bendir á að hávaxtaumhverfi krónunnar sé afar þægilegt fyrir fjármagnseigendur sem fái háa ávöxtun áhættulaust á innlánsreikningum.",
"account": "evropuhreyfingin",
"url": "https://www.tiktok.com/@evropuhreyfingin/video/7649716156454030614",
"views": 2356,
"argKey": "vextir",
"argTitle": "Lægri vextir og stöðugur gjaldmiðill",
"argIcon": "💶"
},
{
"id": "7673097854394584342",
"side": "ja",
"title": "Íhaldssemi eða frjálslyndi 29. ágúst",
"summary": "Umræðan greind sem klassísk átök íhaldssemi og frjálslyndis: frjálslynd öfl sjái tækifæri í aukinni samkeppni, evru og öryggistengslum við Evrópu.",
"account": "evropuhreyfingin",
"url": "https://www.tiktok.com/@evropuhreyfingin/video/7673097854394584342",
"views": 1961,
"argKey": "taekifaeri",
"argTitle": "Tækifæri unga fólksins",
"argIcon": "🎓"
},
{
"id": "7658941692287995158",
"side": "ja",
"title": "Guðni: fullveldi þróast og breytist",
"summary": "Guðni Th. Jóhannesson fyrrverandi forseti segir Ísland frjálst og fullvalda ríki, ekki þrátt fyrir alþjóðasamvinnu heldur vegna hennar.",
"account": "evropuhreyfingin",
"url": "https://www.tiktok.com/@evropuhreyfingin/video/7658941692287995158",
"views": 1786,
"argKey": "hraedslu",
"argTitle": "Svar við hræðsluáróðri",
"argIcon": "📢"
},
{
"id": "7676069567948688662",
"side": "ja",
"title": "Bull um flæði útlendinga",
"summary": "Fullyrðing um að útlendingar flæði til landsins við inngöngu sögð bull; frjáls för hafi gilt frá 1994 gegnum EES og Danir setji sér sjálfir ströngustu innflytjendareglur í ESB.",
"account": "sja",
"url": "https://www.tiktok.com/@jatiladsja/video/7676069567948688662",
"views": 1757,
"argKey": "hraedslu",
"argTitle": "Svar við hræðsluáróðri",
"argIcon": "📢"
},
{
"id": "7676068579187625238",
"side": "ja",
"title": "Bull að ekkert sé að semja um",
"summary": "Fullyrðingu um að allt um ESB megi lesa á netinu svarað: enginn viti hvaða íslensku sérlausnir fáist fyrr en sest er að samningaborðinu, t.d. um sjávarútveg og landbúnað.",
"account": "sja",
"url": "https://www.tiktok.com/@jatiladsja/video/7676068579187625238",
"views": 1742,
"argKey": "kikja",
"argTitle": "Kosið um viðræður — sjáum samninginn",
"argIcon": "📄"
},
{
"id": "7676070990455147778",
"side": "ja",
"title": "Bull að engar undanþágur fáist",
"summary": "Fullyrðing um að engar varanlegar undanþágur fáist sögð bull; Danmörk hafi varanlega undanþágu frá evrunni og Finnland í landbúnaðarmálum.",
"account": "sja",
"url": "https://www.tiktok.com/@jatiladsja/video/7676070990455147778",
"views": 675,
"argKey": "hraedslu",
"argTitle": "Svar við hræðsluáróðri",
"argIcon": "📢"
},
{
"id": "7677229491818728726",
"side": "ja",
"title": "Vaxtabyrði ríkissjóðs á við Grikkland",
"summary": "Ásgeir Brynjar, doktor í fjármálum, segir ríkissjóð greiða álíka hátt hlutfall útgjalda í vexti og Grikkland vegna hávaxtaumhverfis krónunnar; með umsókn og ERM-skjóli fengist stöðugleiki.",
"account": "evropuhreyfingin",
"url": "https://www.tiktok.com/@evropuhreyfingin/video/7677229491818728726",
"views": 322,
"argKey": "vextir",
"argTitle": "Lægri vextir og stöðugur gjaldmiðill",
"argIcon": "💶"
},
{
"id": "7662744196779887894",
"side": "nei",
"title": "Ungir gegn ESB: Lesið ykkur til",
"summary": "Formaður Ungra gegn ESB segir kosninguna snúast um hvort framselja eigi ákvörðunarvald sem fyrri kynslóðir börðust fyrir og hvetur ungt fólk til að kynna sér ferlið sjálft á heimasíðu ESB.",
"account": "aframisland",
"url": "https://www.tiktok.com/@afram.island/video/7662744196779887894",
"views": 3839,
"argKey": "fullveldi",
"argTitle": "Fullveldisframsal",
"argIcon": "🏛️"
},
{
"id": "7663468795310263574",
"side": "nei",
"title": "Ákvarðanir teknar á Íslandi",
"summary": "Valdís segir grundvallarspurninguna vera hvar ákvarðanir um framtíð Íslands eigi að vera teknar — af fólki sem þekki íslenskar aðstæður og beri ábyrgð gagnvart þjóðinni.",
"account": "aframisland",
"url": "https://www.tiktok.com/@afram.island/video/7663468795310263574",
"views": 8834,
"argKey": "fullveldi",
"argTitle": "Fullveldisframsal",
"argIcon": "🏛️"
},
{
"id": "7667922628727819542",
"side": "nei",
"title": "Framtíð Íslands í höndum Íslendinga",
"summary": "Anton Berg segir fyrri kynslóðir hafa barist fyrir rétti Íslands til að standa á eigin fótum; núverandi kynslóð eigi að varðveita frelsið en ekki afhenda það öðrum.",
"account": "aframisland",
"url": "https://www.tiktok.com/@afram.island/video/7667922628727819542",
"views": 4986,
"argKey": "fullveldi",
"argTitle": "Fullveldisframsal",
"argIcon": "🏛️"
},
{
"id": "7669776958820977942",
"side": "nei",
"title": "Sæti Íslands við borðið: 0,1%",
"summary": "Bent er á að atkvæðavægi í ráðherraráði ESB fari eftir íbúafjölda og að Ísland hefði um 0,1% vægi í langflestum ákvörðunum.",
"account": "aframisland",
"url": "https://www.tiktok.com/@afram.island/video/7669776958820977942",
"views": 8219,
"argKey": "ahrifaleysi",
"argTitle": "Hverfandi vægi smáríkis",
"argIcon": "🤏"
},
{
"id": "7670169347859516694",
"side": "nei",
"title": "Fótskemill, ekki sæti við borðið",
"summary": "Því er haldið fram að 6 þingmenn af 720 og um 0,1% vægi í ráðherraráðinu veiti Íslandi engin raunveruleg áhrif; nær væri að tala um fótskemil en sæti við borðið.",
"account": "aframisland",
"url": "https://www.tiktok.com/@afram.island/video/7670169347859516694",
"views": 3927,
"argKey": "ahrifaleysi",
"argTitle": "Hverfandi vægi smáríkis",
"argIcon": "🤏"
},
{
"id": "7670559634444520727",
"side": "nei",
"title": "Málskotsréttur forseta myndi þrengjast",
"summary": "Útskýrt er að reglugerðir ESB giltu beint á Íslandi og færu ekki til forseta til staðfestingar; málskotsréttur forsetans og lokaorð þjóðarinnar næðu því til færri ákvarðana en í dag.",
"account": "aframisland",
"url": "https://www.tiktok.com/@afram.island/video/7670559634444520727",
"views": 7978,
"argKey": "fullveldi",
"argTitle": "Fullveldisframsal",
"argIcon": "🏛️"
},
{
"id": "7672393555456937238",
"side": "nei",
"title": "Á okkar eigin forsendum",
"summary": "Stutt yfirlýsing: viðmælandi vill að Íslendingar haldi áfram að móta samfélagið á eigin forsendum út frá íslenskum aðstæðum og hagsmunum.",
"account": "aframisland",
"url": "https://www.tiktok.com/@afram.island/video/7672393555456937238",
"views": 4488,
"argKey": "fullveldi",
"argTitle": "Fullveldisframsal",
"argIcon": "🏛️"
},
{
"id": "7672558992828239126",
"side": "nei",
"title": "Stefán Pálsson: Breytingar innan frá",
"summary": "Stefán Pálsson segir hvorki gott fyrir einstaklinga né þjóðir að reikna með að breytingar komi utan frá; Íslendingar geti átt samskipti við umheiminn á eigin forsendum og breytt því sem þeir kjósa sjálfir.",
"account": "aframisland",
"url": "https://www.tiktok.com/@afram.island/video/7672558992828239126",
"views": 6969,
"argKey": "fullveldi",
"argTitle": "Fullveldisframsal",
"argIcon": "🏛️"
},
{
"id": "7672740991941610774",
"side": "nei",
"title": "Helga Kristín: Sjálfstætt land áfram",
"summary": "Helga Kristín vill búa áfram í sjálfstæðu landi þar sem Íslendingar taka ákvarðanir um innanlandsmál og náttúruauðlindir, fyrir sig og komandi kynslóðir.",
"account": "aframisland",
"url": "https://www.tiktok.com/@afram.island/video/7672740991941610774",
"views": 6744,
"argKey": "fullveldi",
"argTitle": "Fullveldisframsal",
"argIcon": "🏛️"
},
{
"id": "7674768418498759958",
"side": "nei",
"title": "Birkir: Framtíðin í okkar höndum",
"summary": "Birkir segir framtíð ungs fólks betur borgið í höndum Íslendinga en innan Evrópusambandsins.",
"account": "aframisland",
"url": "https://www.tiktok.com/@afram.island/video/7674768418498759958",
"views": 3179,
"argKey": "fullveldi",
"argTitle": "Fullveldisframsal",
"argIcon": "🏛️"
},
{
"id": "7674768508600782102",
"side": "nei",
"title": "Dóra: Stjórn auðlinda hér á landi",
"summary": "Dóra Tómasar segir gott fyrir ungt fólk að stjórn auðlindanna sé áfram hér á landi.",
"account": "aframisland",
"url": "https://www.tiktok.com/@afram.island/video/7674768508600782102",
"views": 3372,
"argKey": "fullveldi",
"argTitle": "Fullveldisframsal",
"argIcon": "🏛️"
},
{
"id": "7674939612749368598",
"side": "nei",
"title": "Árni Daníel: Lýðræðishefðin styrkt",
"summary": "Árni Daníel segist alinn upp við lýðræðishefð með djúpar rætur í íslenskri sögu og menningu og vill að sú hefð verði efld og styrkt.",
"account": "aframisland",
"url": "https://www.tiktok.com/@afram.island/video/7674939612749368598",
"views": 1620,
"argKey": "fullveldi",
"argTitle": "Fullveldisframsal",
"argIcon": "🏛️"
},
{
"id": "7674940390088215830",
"side": "nei",
"title": "Birgitta: Sjálfstætt land til barnanna",
"summary": "Birgitta segir foreldrana hafa skilað okkur sjálfstæðu landi; okkar ábyrgð sé að gera það sama fyrir börnin okkar.",
"account": "aframisland",
"url": "https://www.tiktok.com/@afram.island/video/7674940390088215830",
"views": 2191,
"argKey": "fullveldi",
"argTitle": "Fullveldisframsal",
"argIcon": "🏛️"
},
{
"id": "7675022361057316118",
"side": "nei",
"title": "Skipuritið stækkar við inngöngu",
"summary": "Ákvörðunarvaldi þjóða er líkt við skipurit sem stækkaði við inngöngu í ESB: stjórnmálamenn gætu falið sig á bak við reglur frá Brussel og almenningur missti möguleikann á að draga ákvörðunartökufólk til ábyrgðar í eigin nærumhverfi.",
"account": "aframisland",
"url": "https://www.tiktok.com/@afram.island/video/7675022361057316118",
"views": 4020,
"argKey": "fullveldi",
"argTitle": "Fullveldisframsal",
"argIcon": "🏛️"
},
{
"id": "7675272414401514774",
"side": "nei",
"title": "Ágústa: Gefum ekki auðlindirnar frá okkur",
"summary": "Ágústa segir náttúruauðlindirnar mikilvæga undirstöðu velmegunar og nýsköpunar á Íslandi sem ekki megi gefa frá sér.",
"account": "aframisland",
"url": "https://www.tiktok.com/@afram.island/video/7675272414401514774",
"views": 1312,
"argKey": "fullveldi",
"argTitle": "Fullveldisframsal",
"argIcon": "🏛️"
},
{
"id": "7675275788131814678",
"side": "nei",
"title": "Berglind: Leysum vandamálin sjálf",
"summary": "Berglind segist trúa á Ísland og að Íslendingar geti leyst eigin vandamál sjálfir eins og þeir hafi alltaf gert í gegnum tíðina.",
"account": "aframisland",
"url": "https://www.tiktok.com/@afram.island/video/7675275788131814678",
"views": 2019,
"argKey": "fullveldi",
"argTitle": "Fullveldisframsal",
"argIcon": "🏛️"
},
{
"id": "7675298733235522838",
"side": "nei",
"title": "Hvaðan koma 50 milljarðarnir?",
"summary": "Útskýrt er að aðildarríki greiði um 1% af þjóðartekjum til ESB, sem næmi um 50 milljörðum króna á ári fyrir Ísland — á við rekstur allra framhaldsskóla landsins; aðeins hluti komi til baka og þá með skilyrðum.",
"account": "aframisland",
"url": "https://www.tiktok.com/@afram.island/video/7675298733235522838",
"views": 8522,
"argKey": "kostnadur",
"argTitle": "Mikill beinn kostnaður",
"argIcon": "💸"
},
{
"id": "7675505073467706646",
"side": "nei",
"title": "50 milljarðar á ári — enginn giskaði rétt",
"summary": "Vegfarendur giska á árlegan kostnað við ESB-aðild; enginn hittir á töluna sem sögð er 50 milljarðar króna á ári og spurt er hvort peningarnir nýttust ekki betur til að efla landið inn á við.",
"account": "aframisland",
"url": "https://www.tiktok.com/@afram.island/video/7675505073467706646",
"views": 23400,
"argKey": "kostnadur",
"argTitle": "Mikill beinn kostnaður",
"argIcon": "💸"
},
{
"id": "7675644609577405718",
"side": "nei",
"title": "Daníel: Smæðin er styrkleiki",
"summary": "Daníel segir smæð íslensks samfélags helsta styrkleika þess: stutt sé í alla valdhafa, minna skrifræði og styttri boðleiðir.",
"account": "aframisland",
"url": "https://www.tiktok.com/@afram.island/video/7675644609577405718",
"views": 1530,
"argKey": "ahrifaleysi",
"argTitle": "Hverfandi vægi smáríkis",
"argIcon": "🤏"
},
{
"id": "7676422619972881686",
"side": "nei",
"title": "Selma: næstu kynslóðir ráði landinu",
"summary": "Selma segist trúa á framtíðartækifæri Íslands og vilja að næstu kynslóðir fái að ráða yfir landinu óheft.",
"account": "aframisland",
"url": "https://www.tiktok.com/@afram.island/video/7676422619972881686",
"views": 1231,
"argKey": "fullveldi",
"argTitle": "Fullveldisframsal",
"argIcon": "🏛️"
},
{
"id": "7676492643299298582",
"side": "nei",
"title": "Jóhann: engan erlendan húsbónda",
"summary": "Jóhann segist hvorki vilja né þurfa erlendan húsbónda og neiti að láta af hendi íslenska lögsögu, gjaldmiðil eða náttúruauðlindir.",
"account": "aframisland",
"url": "https://www.tiktok.com/@afram.island/video/7676492643299298582",
"views": 1375,
"argKey": "fullveldi",
"argTitle": "Fullveldisframsal",
"argIcon": "🏛️"
},
{
"id": "7676809312026643734",
"side": "nei",
"title": "Jóhann: lögum málin sjálf heima",
"summary": "Jóhann segir Ísland besta land í heimi og að öll mál sem þurfi að laga geti Íslendingar leyst sjálfir heima fyrir.",
"account": "aframisland",
"url": "https://www.tiktok.com/@afram.island/video/7676809312026643734",
"views": 2442,
"argKey": "fullveldi",
"argTitle": "Fullveldisframsal",
"argIcon": "🏛️"
},
{
"id": "7653064167200427286",
"side": "ja",
"title": "Já til að sjá 29. ágúst",
"summary": "Stutt kynningarmyndband án tals sem hvetur til að segja já í þjóðaratkvæðagreiðslunni 29. ágúst.",
"account": "sja",
"url": "https://www.tiktok.com/@jatiladsja/video/7653064167200427286",
"views": 6261,
"argKey": "",
"argTitle": "",
"argIcon": ""
},
{
"id": "7665371746249362710",
"side": "ja",
"title": "Jágúst eða neigúst?",
"summary": "Vegfarendur spurðir hvort þeir séu „jágúst eða neigúst“; stemningsmyndband án efnislegra röksemda.",
"account": "sja",
"url": "https://www.tiktok.com/@jatiladsja/video/7665371746249362710",
"views": 35000,
"argKey": "",
"argTitle": "",
"argIcon": ""
},
{
"id": "7666090501996825878",
"side": "ja",
"title": "Hver getur nefnt fleiri Evrópuborgir?",
"summary": "Leikur þar sem keppt er í að nefna borgir í Evrópu; stemningsefni án röksemda.",
"account": "sja",
"url": "https://www.tiktok.com/@jatiladsja/video/7666090501996825878",
"views": 14200,
"argKey": "",
"argTitle": "",
"argIcon": ""
},
{
"id": "7666435885315018006",
"side": "ja",
"title": "Borgaleikur: hver man fleiri borgir?",
"summary": "Vegfarendur keppa í að nefna borgir í Evrópu; stemningsefni án röksemda.",
"account": "sja",
"url": "https://www.tiktok.com/@jatiladsja/video/7666435885315018006",
"views": 10700,
"argKey": "",
"argTitle": "",
"argIcon": ""
},
{
"id": "7666436278195473686",
"side": "ja",
"title": "Álfarnir borga reikningana okkar",
"summary": "Grínviðtal þar sem álfar eru sagðir senda Íslendingum peninga svo þeir hafi efni á að búa á Íslandi.",
"account": "sja",
"url": "https://www.tiktok.com/@jatiladsja/video/7666436278195473686",
"views": 22900,
"argKey": "",
"argTitle": "",
"argIcon": ""
},
{
"id": "7668431037466430723",
"side": "ja",
"title": "Heitt eða kalt um Ísland og Evrópu",
"summary": "Stemningsleikur þar sem verðlag og veður á Íslandi fá „ískalt“ en evrópsk stemning „sjóðheitt“; engin efnisleg rök.",
"account": "sja",
"url": "https://www.tiktok.com/@jatiladsja/video/7668431037466430723",
"views": 13300,
"argKey": "",
"argTitle": "",
"argIcon": ""
},
{
"id": "7668646572112071958",
"side": "ja",
"title": "Bestu borgir Evrópu",
"summary": "Vegfarendur nefna uppáhaldsborgir sínar í Evrópu; stemningsefni án röksemda.",
"account": "sja",
"url": "https://www.tiktok.com/@jatiladsja/video/7668646572112071958",
"views": 11900,
"argKey": "",
"argTitle": "",
"argIcon": ""
},
{
"id": "7645002605969722646",
"side": "ja",
"title": "Er mig að dreyma?",
"summary": "Stemningsmyndband með tónlist í aðdraganda atkvæðagreiðslunnar; engin efnisleg rök.",
"account": "evropuhreyfingin",
"url": "https://www.tiktok.com/@evropuhreyfingin/video/7645002605969722646",
"views": 2327,
"argKey": "",
"argTitle": "",
"argIcon": ""
},
{
"id": "7667149661802663190",
"side": "ja",
"title": "Ekki bíða eftir kjördegi",
"summary": "Upplýsingar um utankjörfundaratkvæðagreiðslu fyrir þau sem verða erlendis 29. ágúst eða vilja kjósa snemma.",
"account": "evropuhreyfingin",
"url": "https://www.tiktok.com/@evropuhreyfingin/video/7667149661802663190",
"views": 1519,
"argKey": "",
"argTitle": "",
"argIcon": ""
},
{
"id": "7667987521795591446",
"side": "ja",
"title": "Sólveig æfir sig að segja JÁ",
"summary": "Sólveig Arnarsdóttir æfir sig að hrópa já fyrir 29. ágúst; stemningsmyndband án röksemda.",
"account": "evropuhreyfingin",
"url": "https://www.tiktok.com/@evropuhreyfingin/video/7667987521795591446",
"views": 8988,
"argKey": "",
"argTitle": "",
"argIcon": ""
},
{
"id": "7676066216246611222",
"side": "ja",
"title": "El Grande: keppni um Evrópulönd",
"summary": "Gamansöm keppni um hvor getur nefnt fleiri lönd í Evrópu; stemningsmyndband án málefnaraka.",
"account": "sja",
"url": "https://www.tiktok.com/@jatiladsja/video/7676066216246611222",
"views": 8421,
"argKey": "",
"argTitle": "",
"argIcon": ""
},
{
"id": "7676067587188395286",
"side": "ja",
"title": "Keppni: fleiri borgir í Evrópu",
"summary": "Gamansöm keppni um hvor getur nefnt fleiri borgir í Evrópu; stemningsmyndband án málefnaraka.",
"account": "sja",
"url": "https://www.tiktok.com/@jatiladsja/video/7676067587188395286",
"views": 8465,
"argKey": "",
"argTitle": "",
"argIcon": ""
},
{
"id": "7676067865451138306",
"side": "ja",
"title": "El Grande: Evrópulönd talin upp",
"summary": "Gamansöm keppni um hvor getur nefnt fleiri lönd í Evrópu; stemningsmyndband án málefnaraka.",
"account": "sja",
"url": "https://www.tiktok.com/@jatiladsja/video/7676067865451138306",
"views": 5275,
"argKey": "",
"argTitle": "",
"argIcon": ""
},
{
"id": "7677182391508667670",
"side": "ja",
"title": "Bændur segja já fyrir landbúnaðinn",
"summary": "Gamansamt myndband þar sem bændur í heyskap segjast ætla að kjósa já og vilja ekki vera afturhaldsseggir.",
"account": "sja",
"url": "https://www.tiktok.com/@jatiladsja/video/7677182391508667670",
"views": 4487,
"argKey": "",
"argTitle": "",
"argIcon": ""
},
{
"id": "7662743992592846102",
"side": "nei",
"title": "Fjölmenni á upphafsfundi",
"summary": "Rætt um metmætingu og góða stemningu á upphafsfundi Áfram Íslands og komandi fundaferð um landið; engin efnisleg rök flutt.",
"account": "aframisland",
"url": "https://www.tiktok.com/@afram.island/video/7662743992592846102",
"views": 4181,
"argKey": "",
"argTitle": "",
"argIcon": ""
},
{
"id": "7666128105068662038",
"side": "nei",
"title": "Tala fyrir Íslandi, ekki gegn Evrópu",
"summary": "Guðmundur Fertram segist bera virðingu fyrir Evrópu en telur það ekki þýða að framtíð Íslands eigi að liggja innan ESB.",
"account": "aframisland",
"url": "https://www.tiktok.com/@afram.island/video/7666128105068662038",
"views": 1459,
"argKey": "",
"argTitle": "",
"argIcon": ""
},
{
"id": "7666141449565588758",
"side": "nei",
"title": "Einar Bárðarson á opnum fundi",
"summary": "Einar Bárðarson lýsir góðum fundi á Suðurlandi og hvetur fólk til að skoða heildarmyndina og hagsmuni þjóðarbúsins; engin bein efnisrök flutt.",
"account": "aframisland",
"url": "https://www.tiktok.com/@afram.island/video/7666141449565588758",
"views": 1271,
"argKey": "",
"argTitle": "",
"argIcon": ""
},
{
"id": "7672547322168970518",
"side": "nei",
"title": "Fundarboð á Hvolsvelli",
"summary": "Kynning á opnum fundi Áfram Íslands á Hvolsvelli; vegfarendur segjast ætla að kjósa nei og vilja ekki inn í bákn og embættismannakerfi.",
"account": "aframisland",
"url": "https://www.tiktok.com/@afram.island/video/7672547322168970518",
"views": 5139,
"argKey": "",
"argTitle": "",
"argIcon": ""
},
{
"id": "7672814829899418902",
"side": "nei",
"title": "Vegfarendur spurðir: Já eða nei?",
"summary": "Fólk á förnum vegi er spurt hvað það ætli að kjósa; svörin eru blönduð — sumir segja nei vegna yfirþyrmandi regluverks, aðrir eru óákveðnir.",
"account": "aframisland",
"url": "https://www.tiktok.com/@afram.island/video/7672814829899418902",
"views": 45000,
"argKey": "",
"argTitle": "",
"argIcon": ""
},
{
"id": "7673292276814122262",
"side": "nei",
"title": "Fundarboð í Reykjanesbæ",
"summary": "Kynning á fundi Áfram Íslands í Reykjanesbæ; vegfarendur segjast ætla að kjósa nei og að Ísland sé ekki til sölu.",
"account": "aframisland",
"url": "https://www.tiktok.com/@afram.island/video/7673292276814122262",
"views": 5184,
"argKey": "",
"argTitle": "",
"argIcon": ""
},
{
"id": "7674599568532704534",
"side": "nei",
"title": "Nei-hreyfingin er þverskurður þjóðarinnar",
"summary": "Ungur ræðumaður hafnar því að andstæðingar aðildar séu málpípur auðvaldsins; í salnum séu kennarar, iðnaðarmenn, lögreglumenn og fólk á öllum aldri — þverskurður af íslensku samfélagi.",
"account": "aframisland",
"url": "https://www.tiktok.com/@afram.island/video/7674599568532704534",
"views": 24800,
"argKey": "",
"argTitle": "",
"argIcon": ""
},
{
"id": "7674967552468208899",
"side": "nei",
"title": "Brynhildur: Trú á íslensku þjóðinni",
"summary": "Brynhildur segist hafa óbilandi trú á íslensku þjóðinni og ætlar því að segja nei; engin frekari rök flutt.",
"account": "aframisland",
"url": "https://www.tiktok.com/@afram.island/video/7674967552468208899",
"views": 2129,
"argKey": "",
"argTitle": "",
"argIcon": ""
},
{
"id": "7675062406065802518",
"side": "nei",
"title": "Kappræður í Austurbæjarbíói",
"summary": "Kynning á kappræðum Áfram Íslands og já-hreyfingarinnar í Austurbæjarbíói; miðasala á vef hreyfingarinnar. Engin efnisrök flutt.",
"account": "aframisland",
"url": "https://www.tiktok.com/@afram.island/video/7675062406065802518",
"views": 2854,
"argKey": "",
"argTitle": "",
"argIcon": ""
},
{
"id": "7676809433921375510",
"side": "nei",
"title": "Magnús: fórnum ekki tækifærum Íslands",
"summary": "Magnús segist ekki vilja að Ísland fórni tækifærum sínum og segir því nei 29. ágúst.",
"account": "aframisland",
"url": "https://www.tiktok.com/@afram.island/video/7676809433921375510",
"views": 1422,
"argKey": "",
"argTitle": "",
"argIcon": ""
}
];
