# -*- coding: utf-8 -*-
import json, os

OUT = os.path.join(os.path.dirname(os.path.abspath(__file__)), 'sweep_final.json')

articles = [
{"side":"ja","title":"Fram og aftur blindgötuna","url":"https://www.dv.is/eyjan/2026/08/18/bjorgvin-g-sigurdsson-skrifar-fram-og-aftur-blindgotuna","source":"dv.is","author":"Björgvin G. Sigurðsson","date":"2026-08-18","summary":"Fyrrverandi þingflokksformaður Samfylkingarinnar rekur sögu alþjóðasamstarfs Íslands og segir EES-stoðina ekki standa til eilífðar, m.a. ef Noregur stígur skrefið til fullrar aðildar. Evran gæti lækkað vaxtabyrði almennings um allt að 30% og sparað hundruð milljarða í vaxtakostnað. Eina leiðin til að fá skorið úr álitaefnum sé að ljúka samningsferlinu.","args":["kikja","vextir","timagluggi"],"impact":2},
{"side":"ja","title":"Hversu miklu fórnar Ísland nú með skertu FRELSI?","url":"https://www.dv.is/eyjan/2026/08/18/thorvaldur-ingi-jonsson-skrifar-hversu-miklu-fornar-island-nu-med-skertu-frelsi","source":"dv.is","author":"Þorvaldur Ingi Jónsson","date":"2026-08-18","summary":"Höfundur spyr hversu frjálst Ísland sé í raun: utan tollabandalagsins, án atkvæðisréttar um reglur innri markaðarins og með örgjaldmiðil með gengisáhættu. Hann vill ljúka viðræðum, bera samninginn saman við EES og krónuna og hafna honum ef hann reynist verri. Já 29. ágúst sé skref til að semja og sjá samninginn.","args":["tollfrelsi","ahrif","kikja"],"impact":2},
{"side":"ja","title":"Orðið á götunni: Trump ætlar að innlima Grænland – Er svo Ísland næst?","url":"https://www.dv.is/eyjan/2026/08/18/ordid-a-gotunni-trump-aetlar-ad-innlima-graenland-er-svo-island-naest","source":"dv.is","author":None,"date":"2026-08-18","summary":"Pistillinn segir yfirlýsingar Trumps um innlimun Grænlands sýna að Ísland geti ekki setið aðgerðalaust. Ísland njóti ekki sömu verndar og Danmörk af hálfu ESB og því sé nánara samstarf við Evrópuríki, einnig um varnarmál, lífsnauðsyn. Fyrsta skrefið sé að segja já 29. ágúst.","args":["oryggi"],"impact":2},
{"side":"ja","title":"Önnur tók fyrst til máls – hin vill nú slá botn í málið","url":"https://www.dv.is/eyjan/2026/08/19/thorsteinn-palsson-skrifar-onnur-tok-fyrst-til-mals-hin-vill-nu-sla-botn-i-malid","source":"dv.is","author":"Þorsteinn Pálsson","date":"2026-08-19","summary":"Þorsteinn rifjar upp að Ragnhildur Helgadóttir hafi árið 1990 fyrst hreyft hugmyndinni um fulla aðild á Alþingi og segir Þorgerði Katrínu nú fylgja sömu grundvallarstefnu. Að breyta 75% aðild gegnum EES í fulla aðild byggi á sömu hugmyndafræði og utanríkisstefna Íslands í nær átta áratugi. Nei auki hættu á að Ísland ráði ekki sjálft í hvaða félagsskap þjóða það lendi.","args":["kikja","gildi"],"impact":2},
{"side":"ja","title":"Orðið á götunni: Hnífjafn slagur og nei-ið beitir blekkingum – samt vex já-sinnum fiskur um hrygg","url":"https://www.dv.is/eyjan/2026/08/19/ordid-a-gotunni-hnifjafn-slagur-og-nei-id-beitir-blekkingum-samt-vex-ja-sinnum","source":"dv.is","author":None,"date":"2026-08-19","summary":"Pistillinn segir nei-hreyfinguna betur fjármagnaða og auglýsingar hennar fullyrða án forsendna að aðild kosti 50 milljarða á ári; Morgunblaðið hafi svo nefnt 90 milljarða. Þrátt fyrir þessar blekkingar sé slagurinn hnífjafn og já-hliðin sæki á.","args":["hraedslu"],"impact":2},
{"side":"nei","title":"Sæti við borðið...","url":"https://www.dv.is/eyjan/2026/08/20/ari-kr-saemundsen-skrifar-saeti-vid-bordid","source":"dv.is","author":"Ari Kr. Sæmundsen","date":"2026-08-20","summary":"Höfundur segir fullyrðingu já-sinna um sæti við borðið beinlínis ranga; sætið gagnist lítið ef sá sem þar situr sofi á fundum, líkt og Íslendingar hafi gert gagnvart ESB-reglugerðum. Hann efast einnig um að Ísland fengi nokkurn tíma evru og bendir á að Rúmenía hafi ekki uppfyllt skilyrðin nítján árum eftir inngöngu.","args":["ahrifaleysi","evra"],"impact":1},
{"side":"ja","title":"Við erum ekki að kjósa um aðild 29. ágúst!","url":"https://www.dv.is/eyjan/2026/08/20/david-thor-bjorgvinsson-skrifar-vid-erum-ekki-ad-kjosa-um-adild-29-agust","source":"dv.is","author":"Davíð Þór Björgvinsson","date":"2026-08-20","summary":"Davíð Þór segir atkvæðagreiðsluna aðeins snúast um að hefja viðræður að nýju, ekki um aðild. Óákveðnir geti óhræddir sagt já því þeir geti sagt nei síðar þegar samningur liggur fyrir. Fullyrðingar um sjálfkrafa fullveldismissi og auðlindatöku við viðræður séu rangar eða villandi.","args":["kikja","hraedslu"],"impact":2},
{"side":"ja","title":"Sjálfstæðisflokkurinn er ekki lengur í alfaraleið","url":"https://www.dv.is/eyjan/2026/08/20/gudmundur-einarsson-skrifar-sjalfstaedisflokkurinn-er-ekki-lengur-i-alfaraleid","source":"dv.is","author":"Guðmundur Einarsson","date":"2026-08-20","summary":"Fyrrverandi alþingismaður gagnrýnir Sjálfstæðisflokkinn fyrir að tefla fram svissneska lögfræðingnum Carl Baudenbacher sem aðalræðumanni gegn viðræðum. Hann spyr hvers vegna flokkurinn sé svo hart á móti aðild að hann vilji ekki einu sinni leyfa þjóðinni að kanna hvað hún hefði upp á að bjóða.","args":["kikja"],"impact":1},
{"side":"ja","title":"Reikningurinn lendir alltaf einhvers staðar","url":"https://www.dv.is/eyjan/2026/08/20/sigvaldi-einarsson-skrifar-reikningurinn-lendir-alltaf-einhvers-stadar","source":"dv.is","author":"Sigvaldi Einarsson","date":"2026-08-20","summary":"Höfundur tengir þriðju stýrivaxtahækkun ársins í 8% við atkvæðagreiðsluna og segir vaxtastigið og ESB-málið sama vandann séðan frá tveimur hliðum. Hagkerfið kólni, vanskil vaxi og verðbólgan sé 5,3%; reikningur krónunnar lendi alltaf á almenningi.","args":["vextir"],"impact":2},
{"side":"ja","title":"Orðið á götunni: Bændasamtökin og bændur sýna kjósendum argasta dónaskap","url":"https://www.dv.is/eyjan/2026/08/20/ordid-a-gotunni-baendasamtokin-og-baendur-syna-kjosendum-argasta-donaskap","source":"dv.is","author":None,"date":"2026-08-20","summary":"Pistillinn sakar Bændasamtökin og bændur um ósannindi og falsfréttir í aðdraganda atkvæðagreiðslunnar. Stétt sem þiggi 30 milljarða króna á ári í opinbera styrki eigi frekar að sýna kjósendum kurteisi en lygaáróður.","args":["hraedslu"],"impact":1},
{"side":"ja","title":"Orðið á götunni: Hvaða hagsmuni er verið að verja og hvers vegna?","url":"https://www.dv.is/eyjan/2026/08/20/ordid-a-gotunni-hvada-hagsmuni-er-verid-ad-verja-og-hvers-vegna","source":"dv.is","author":None,"date":"2026-08-20","summary":"Pistillinn segir vaxtahækkun Seðlabankans draga áþreifanlega fram annmarka þess að halda úti sjálfstæðum gjaldmiðli í örhagkerfi. Vextir séu margfaldir á Íslandi miðað við evrusvæðið og hækkunin verði vatn á myllu já-sinna.","args":["vextir"],"impact":1},
{"side":"ja","title":"Svarthöfði skrifar: Lítt ritfærir birta gullaldartexta","url":"https://www.dv.is/eyjan/2026/08/20/svarthofdi-skrifar-litt-ritfaerir-birta-gullaldartexta","source":"dv.is","author":None,"date":"2026-08-20","summary":"Svarthöfði hæðist að nei-sinnum sem birti skyndilega fágaðan texta á samfélagsmiðlum og grunar að baráttusamtök hafi lagt þeim til tilbúnar færslur. Afbökun staðreynda og rangfærslur einkenni skrif nei-hliðarinnar.","args":["hraedslu"],"impact":1},
{"side":"ja","title":"29. ágúst er stærsti vaxtaákvörðunardagur Íslendinga","url":"https://www.dv.is/eyjan/2026/08/21/sigmundur-ernir-skrifar-29-agust-er-staersti-vaxtaakvordunardagur-islendinga","source":"dv.is","author":"Sigmundur Ernir Rúnarsson","date":"2026-08-21","summary":"Sigmundur Ernir tekur undir orð Guðmundar Andra Thorssonar um að kjördagurinn verði stærsti vaxtaákvörðunardagur Íslendinga. Krónan sé örmynt sem gagnist helst efnafólki en almenningur sitji eftir með okurvexti, hátt verðlag og verðbólguþrýsting.","args":["vextir"],"impact":2},
{"side":"ja","title":"Sjá þingmenn lengra en þjóðin – 30 ár fram í tímann?","url":"https://www.dv.is/eyjan/2026/08/21/thorvaldur-ingi-jonsson-skrifar-sja-thingmenn-lengra-en-thjodin-30-ar-fram-i","source":"dv.is","author":"Þorvaldur Ingi Jónsson","date":"2026-08-21","summary":"Höfundur telur upp tíu ástæður til að segja já fyrir börnin og barnabörnin og bendir á að enginn þingmaður sjái 30 ár fram í tímann. Já sé ekki samþykki fyrir aðild heldur fyrir því að kanna valkostinn, verja íslenska hagsmuni í samningum og leyfa þjóðinni að taka endanlega ákvörðun.","args":["kikja","taekifaeri"],"impact":2},
{"side":"ja","title":"Helvítis dallurinn má leka – bara ekki rugga honum","url":"https://www.dv.is/eyjan/2026/08/21/vilhelm-jonsson-skrifar-helvitis-dallurinn-ma-leka-bara-ekki-rugga-honum","source":"dv.is","author":"Vilhelm Jónsson","date":"2026-08-21","summary":"Athafnamaðurinn segir Íslendinga bölva verðbólgu, okurvöxtum, fákeppni og kvótakerfi en helga kerfið um leið og breytingar séu nefndar. Hann vill láta reyna á sjávarútveg, landbúnað, gjaldmiðilsmál og sérlausnir í viðræðum og bera niðurstöðuna saman við raunverulegt Ísland með krónu, verðtryggingu og skuldsettum heimilum.","args":["kikja","vextir"],"impact":2},
{"side":"ja","title":"Orðið á götunni: Þrumuræðan og ræðan sem hreyfði ekki við salnum","url":"https://www.dv.is/eyjan/2026/08/21/ordid-a-gotunni-thrumuraedan-og-raedan-sem-hreyfdi-ekki-vid-salnum","source":"dv.is","author":None,"date":"2026-08-21","summary":"Pistillinn rifjar upp ræðu Hilmars Veigars Péturssonar hjá CCP frá 2014 um að krónan skapaði fórnarlambshegðun hjá Íslendingum og að planið væri að ganga í ESB. Nú hafi stóreignastaða og ríkisstyrkir til CCP/Fenris breytt afstöðu hans, að mati pistilsins.","args":["vextir","taekifaeri"],"impact":1},
{"side":"ja","title":"Met stjórnarandstöðunnar","url":"https://www.dv.is/eyjan/2026/08/22/kolbrun-bergthorsdottir-skrifar-met-stjornarandstodunnar","source":"dv.is","author":"Kolbrún Bergþórsdóttir","date":"2026-08-22","summary":"Kolbrún segir kosningabaráttu nei-sinna einkennast af afbökunum og útúrsnúningum og líkir henni við málþófsmet stjórnarandstöðunnar í veiðigjaldaumræðunni. Hrakspár um eymd hafi ekki ræst þá og málflutningurinn nú sé af sama meiði.","args":["hraedslu"],"impact":1},
]

skipped_count = 4
possible_new_arguments = []
notes = ("Checkpoint 1: dv.is done (17 items). Skipped: Maria Rut Kristinsdottir 'Takk fyrir samtalid' (no clear argument), "
         "Bjorn Jon 'Thegar Islendingar urdu til sem thjod' (historical essay, implicit stance only), "
         "Ottar Gudmundsson 'Minningargreinar' and Nina Richter (not ESB). "
         "Remaining: mbl, heimssyn, evropa, jatiladsja, aframisland, tilvinstri, reddit.")

data = {"articles": articles, "skipped_count": skipped_count,
        "possible_new_arguments": possible_new_arguments, "notes": notes}
json.dump(data, open(OUT, 'w', encoding='utf-8'), ensure_ascii=False, indent=1)
print('written', len(articles))
