"""Apply bio batch 2: AKU, ARB, ARN"""
import re, sys
sys.stdout.reconfigure(encoding='utf-8')

BIOS = {
  # AKU - Akureyri
  'Karen Sigurbjörnsdóttir': ('Karen Sigurbjörnsdóttir er mannauðsfulltrúi við Sjúkrahúsið á Akureyri og er í 2. sæti á Akureyrarlistanum í sveitarstjórnarkosningum 2026. Hún leggur áherslu á heilbrigðismál og mannauðsmál í þágu íbúa Akureyrar.', 'https://www.akureyri.net/is/moya/news/thorhallur-karen-og-helgi-steinar'),
  'Helgi Steinar Halldórsson': ('Helgi Steinar Halldórsson er löggiltur fasteignasali hjá Kasafasteignum á Akureyri og ljósmyndari að áhuga. Hann er í 3. sæti á Akureyrarlistanum og tengir þekkingu á fasteignamarkaði saman við áhuga á samfélagsþróun Akureyrar.', 'https://www.akureyri.net/is/moya/news/akureyrarlistinn-birtir-nofn-sjo-efstu'),
  'Kristrún María Björnsdóttir': ('Kristrún María Björnsdóttir er doktorsnemandi í heilbrigðisvísindum við Háskólann á Akureyri og kennari að hluta, fædd 1991 og uppalin á Akureyri. Hún lauk meistaranámi í íþróttalífeðlisfræði og flutti aftur til Akureyrar árið 2024 eftir nám í Noregi og Reykjavík.', 'https://kaffid.is/efstu-sju-saetin-a-lista-akureyrarlistans-kynnt/'),
  'Darri Rafn Hólmarsson': ('Darri Rafn Hólmarsson er tölvunarfræðingur og plötusnúður og er í 5. sæti á Akureyrarlistanum í sveitarstjórnarkosningum 2026. Samkvæmt LinkedIn starfar hann sem gagnasérfræðingur.', 'https://kosningasaga.wordpress.com/2026/02/15/akureyrarlistinn-kynnir-frambjodendur/'),
  'Gunnar Már Gunnarsson': ('Gunnar Már Gunnarsson er verkefnastjóri þéttbýlismála hjá SSNE (Þróunarfélagi Norðausturlands) og varabæjarfulltrúi Framsóknar á Akureyri, með meistaragráðu í norðurslóðafræðum frá Cambridge. Hann hefur sérfræðiþekkingu á þróun dreifbýlissvæða og norðurslóðamálum.', 'https://www.akureyri.is/is/stjornkerfi/baejarstjorn/baejarfulltruar/gunnar-mar-gunnarsson'),
  'Sverre Andreas Jakobsson': ('Sverre Andreas Jakobsson er þjónustustjóri viðskiptaþjónustu Arion banka á Norðausturlandi og fyrrverandi landsliðsmaður í handbolta. Hann er í 3. sæti á lista Framsóknar á Akureyri og er einnig þjálfari í handbolta.', 'https://www.akureyri.net/is/frettir/sverre-andreas-saekist-eftir-fjorda-saetinu'),
  'Guðbjörg Anna Björnsdóttir': ('Guðbjörg Anna Björnsdóttir er í 4. sæti á lista Framsóknar á Akureyri í sveitarstjórnarkosningum 2026 og á sæti í velferðarráði sveitarfélagsins. Hún leggur áherslu á velferðarmál í starfi sínu.', 'https://www.framsoknakureyri.is/'),
  'Steinar Óli Sigfússon': ('Steinar Óli Sigfússon er námsmaður í iðnaðar- og orkutæknifræði í samstarfsnámsbraut Háskólans á Akureyri og Háskóla Íslands, uppruninn frá Skagafirði. Hann situr í stjórn ungmennafélags Framsóknar á Akureyri sem ritari og er í 5. sæti á lista flokksins.', 'https://www.akureyri.net/is/frettir/ungt-framsoknarfolk-stofnar-nytt-felag'),
  'Elías Gunnar Þorbjörnsson': ('Elías Gunnar Þorbjörnsson er skólastjóri Giljaskóla á Akureyri og er í 2. sæti á lista Viðreisnar í sveitarstjórnarkosningum 2026. Hann hefur skrifað um menntamál í Akureyri og leggur áherslu á gagnreyndar umbætur í skólastarfi.', 'https://kosningasaga.wordpress.com/2026/02/23/framsbodslisti-vidreisnar-a-akureyri/'),
  'Þóroddur Ingvarsson': ('Þóroddur Ingvarsson er læknir, sérfræðingur í svæfinga- og gjörgæslulækningum, og er í 3. sæti á lista Viðreisnar á Akureyri. Hann hefur ritað um mikilvægi þess að sveitarfélög skapin tækifæri fyrir börn og ungt fólk til þroska og vaxtar.', 'https://kosningasaga.wordpress.com/2026/02/23/framsbodslisti-vidreisnar-a-akureyri/'),
  'Elísabet Ögn Jóhannsdóttir': ('Elísabet Ögn Jóhannsdóttir er verkefnastjóri menningarmála og er í 4. sæti á lista Viðreisnar á Akureyri í sveitarstjórnarkosningum 2026. Hún leggur áherslu á menningarlíf og þróun Akureyrar sem miðstöðvar menningar á Norðurlandi.', 'https://kosningasaga.wordpress.com/2026/02/23/framsbodslisti-vidreisnar-a-akureyri/'),
  'Íunn Eir Gunnarsdóttir': ('Íunn Eir Gunnarsdóttir er með meistaragráðu í frístundafræðum og þróunarstarfi og er í 5. sæti á lista Viðreisnar á Akureyri. Hún hefur lagt til stofnun afreksakademíu fyrir nemendur á miðstigi til að efla íþróttir, listir og menningu jafnfætis.', 'https://kosningasaga.wordpress.com/2026/02/23/framsbodslisti-vidreisnar-a-akureyri/'),
  'Heimir Örn Árnason': ('Heimir Örn Árnason er formaður bæjarráðs á Akureyri og deildastjóri við Naustaskóla þar sem hann hefur kennt og starfað í skólastjórnun í yfir 16 ár. Hann er í 2. sæti á lista Sjálfstæðisflokksins á Akureyri.', 'https://xd.is/2026/02/26/fullskipadur-frambodislisti-sjalfstaedisflokksins-a-akureyri/'),
  'Arna Rut Gunnarsdóttir': ('Arna Rut Gunnarsdóttir er framkvæmdastjóri hjá Tengum fjarskiptafyrirtæki, 43 ára gömul, með bakgrunn sem svæfingahjúkrunarfræðingur og meistaragráðu í heilbrigðisstjórnun. Hún er í 3. sæti á lista Sjálfstæðisflokksins á Akureyri.', 'https://www.akureyri.net/is/frettir/arna-rut-gefur-kost-a-ser-i-3-4-saeti'),
  'Þórhallur Harðarson': ('Þórhallur Harðarson er framkvæmdastjóri fjármála og stoðsviða hjá Heilbrigðisstofnun Norðurlands og er í 4. sæti á lista Sjálfstæðisflokksins á Akureyri. Hann hefur gegnt þessu starfi um árabil og þjónað sem gjaldkeri og formaður í kjördæmisráði flokksins.', 'https://xd.is/2026/02/26/fullskipadur-frambodislisti-sjalfstaedisflokksins-a-akureyri/'),
  'Þorsteinn Kristjánsson': ('Þorsteinn Kristjánsson er frumkvöðull og er í 5. sæti á lista Sjálfstæðisflokksins á Akureyri í sveitarstjórnarkosningum 2026. Hann kemur með reynslu úr atvinnulífi til fjölbreytts framboðslista með sameiginlegar áherslur um þróun Akureyrar.', 'https://xd.is/2026/02/26/fullskipadur-frambodislisti-sjalfstaedisflokksins-a-akureyri/'),
  'Brynja Hlíf Þorsteinsdóttir': ('Brynja Hlíf Þorsteinsdóttir er lífeindafræðingur og sitjandi bæjarfulltrúi VG á Akureyri og er í 2. sæti á L-listanum í sveitarstjórnarkosningum 2026. Hún hefur áður gegnt trúnaðarstörfum fyrir flokkinn á sveitarstjórnarstigi.', 'https://www.visir.is/g/20262866820d/thau-skipa-l-listann-a-akureyri'),
  'Preben Jón Pétursson': ('Preben Jón Pétursson er mjólkurtæknifræðingur og er í 3. sæti á L-listanum á Akureyri í sveitarstjórnarkosningum 2026. Hann er hluti af fjölbreyttum L-lista sem samanstendur af fólki úr ólíkum áttum með sameiginleg markmið fyrir Akureyri.', 'https://www.visir.is/g/20262866820d/thau-skipa-l-listann-a-akureyri'),
  'María Pálsdóttir': ('María Pálsdóttir er leikkona og frumkvöðull og er í 4. sæti á L-listanum á Akureyri í sveitarstjórnarkosningum 2026. Hún tengir listaheim og frumkvöðlastarfsemi við þátttöku í sveitarstjórnarmálum.', 'https://www.visir.is/g/20262866820d/thau-skipa-l-listann-a-akureyri'),
  'Andri Teitsson': ('Andri Teitsson er verkfræðingur og sitjandi bæjarfulltrúi VG á Akureyri og er í 5. sæti á L-listanum í sveitarstjórnarkosningum 2026. Sem bæjarfulltrúi hefur hann komið að ákvörðunum um uppbyggingu og þróun Akureyrar.', 'https://www.visir.is/g/20262866820d/thau-skipa-l-listann-a-akureyri'),
  'Inga Dís Sigurðardóttir': ('Inga Dís Sigurðardóttir er náms- og starfsráðgjafi og er í 2. sæti á lista Miðflokksins á Akureyri í sveitarstjórnarkosningum 2026.', 'https://kaffid.is/hlynur-leidir-midflokkinn-a-akureyri-afram/'),
  'Egill Einarsson': ('Egill Einarsson er verslunarmaður og er í 3. sæti á lista Miðflokksins á Akureyri í sveitarstjórnarkosningum 2026. Hann kemur með reynslu úr verslunarlífi til framboðslistans.', 'https://kaffid.is/hlynur-leidir-midflokkinn-a-akureyri-afram/'),
  'Katrín Vilhjálmsdóttir': ('Katrín Vilhjálmsdóttir er snyrtifræðingur og sjúkraliði og er í 4. sæti á lista Miðflokksins á Akureyri í sveitarstjórnarkosningum 2026. Hún sameinar þekkingu á heilbrigðis- og þjónustugeiranum.', 'https://kaffid.is/hlynur-leidir-midflokkinn-a-akureyri-afram/'),
  'Hannes Karlsson': ('Hannes Karlsson er framkvæmdastjóri og er í 5. sæti á lista Miðflokksins á Akureyri og hefur verið virkur í Miðflokki Akureyrar, meðal annars sem framkvæmdastjóri flokksins. Hann er búsettur í Lerkilundi á Akureyri.', 'https://midflokkurinn.is/is/moya/news/frambodslisti-midflokksins-a-akureyri/'),
  'Hanna Dóra Markúsdóttir': ('Hanna Dóra Markúsdóttir er grunnskólakennari og er í 2. sæti á lista Samfylkingarinnar á Akureyri í sveitarstjórnarkosningum 2026. Hún styður framtíðarsýn flokksins um sterkari skólabæ og betra menntakerfi.', 'https://xs.is/frettir/2026/03/frambodslisti-samfylkingarinnar-a-akureyri'),
  'Sigrún Steinarsdóttir': ('Sigrún Steinarsdóttir er stofnandi Matargjafa Akureyrar og nágrennis, félags­legu úthlutunarverkefnis sem hefur safnað yfir 7 milljónum króna og aðstoðað yfir 200 fjölskyldur, og er í 3. sæti á lista Samfylkingarinnar. Með þessari hugmyndasemi hefur hún orðið þekkt persóna í baráttu gegn fátækt á Norðurlandi.', 'https://www.akureyri.net/is/frettir/sigrun-snyr-aftur-med-matargjafir-fyrir-jolin'),
  'Jóhannes Már Pétursson': ('Jóhannes Már Pétursson er háskólanemi í félagsvísindum við Háskólann á Akureyri og er í 4. sæti á lista Samfylkingarinnar, en hann hefur áður gegnt störfum sem formaður alþjóðanefndar og fulltrúi í ráði Stúdentafélags Háskólans á Akureyri.', 'https://xs.is/frettir/2026/03/frambodslisti-samfylkingarinnar-a-akureyri'),
  'Zane Brikovska': ('Zane Brikovska er starfsmaður hjá Bjargey meðferðarheimili á Akureyri og er í 5. sæti á lista Samfylkingarinnar í sveitarstjórnarkosningum 2026. Hún er af erlendum uppruna og hefur skrifað um samþættingu og þátttöku innflytjenda í samfélagsstarfi á Akureyri.', 'https://www.visir.is/g/20262874026d/ad-verda-akureyringur'),
  'Stefán Oddur Hrafnsson': ('Stefán Oddur Hrafnsson er í meistaranámi í kennslufræðum og er í 2. sæti á lista VG á Akureyri í sveitarstjórnarkosningum 2026. Hann hefur ritað um samfélagsmál og grunngildi vinstrimanna í sveitarstjórnarmálum.', 'https://kosningasaga.wordpress.com/2026/03/15/frambodslisti-vg-a-akureyri-2/'),
  'Ásrún Ýr Gestsdóttir': ('Ásrún Ýr Gestsdóttir er frumkvöðull og upprunin frá Hrísey og er í 3. sæti á lista VG á Akureyri í sveitarstjórnarkosningum 2026. Hún hefur áður verið á framboðslista VG á Akureyri.', 'https://kosningasaga.wordpress.com/2026/03/15/frambodslisti-vg-a-akureyri-2/'),
  'Sigtryggur Ellertsson': ('Sigtryggur Ellertsson er vistvænn verslunareigandi og er í 4. sæti á lista VG á Akureyri í sveitarstjórnarkosningum 2026. Hann hefur ritað um þróun miðbæjarins á Akureyri og leggur áherslu á umhverfismál í atvinnurekstri sínum.', 'https://www.kaffid.is/frambodslisti-vg-samthykktur-a-akureyri/'),
  'Herdís Júlía Júlíusdóttir': ('Herdís Júlía Júlíusdóttir er iðjuþjálfi í námi og er í 5. sæti á lista VG á Akureyri í sveitarstjórnarkosningum 2026. Hún hefur verið á framboðslista VG á Akureyri í fyrri kosningum og er hluti af nýrri kynslóð vinstrimanna á Norðurlandi.', 'https://kosningasaga.wordpress.com/2026/03/15/frambodslisti-vg-a-akureyri-2/'),

  # ARB - Árborg
  'Ellý Tómasdóttir': ('Ellý Tómasdóttir er stjórnandi og sitjandi bæjarfulltrúi Framsóknar í Árborg og er í 2. sæti á lista flokksins í sveitarstjórnarkosningum 2026. Hún hefur ritað um stöðu sveitarfélagsins og leggur áherslu á samfélagsþróun og framtíðarmál Árborgar.', 'https://www.sunnlenska.is/frettir/listi-framsoknar-i-arborg-samthykktur/'),
  'Arnar Freyr Ólafsson': ('Arnar Freyr Ólafsson er alþjóðafjármálafræðingur frá Eyrarbakka og leiðir lista Framsóknar í Árborg í sveitarstjórnarkosningum 2026 sem oddviti. Hann leggur áherslu á fjárhagslega sjálfbærni og þróun sveitarfélagsins á Suðurlandi.', 'https://www.sunnlenska.is/frettir/listi-framsoknar-i-arborg-samthykktur/'),
  'Guðrún Rakel Svandísardóttir': ('Guðrún Rakel Svandísardóttir er skólastjóri og umhverfisskipulagsfræðingur að menntun og er á lista Framsóknar í Árborg í sveitarstjórnarkosningum 2026. Hún sameinar reynslu úr skólastjórnun og umhverfismálum í kosningarbaráttu sinni.', 'https://www.sunnlenska.is/frettir/listi-framsoknar-i-arborg-samthykktur/'),
  'Magnús Benediktsson': ('Magnús Benediktsson er rekstrarstjóri og er í 5. sæti á lista Framsóknar í Árborg í sveitarstjórnarkosningum 2026. Hann kemur með rekstrarreynslu til framboðslistans sem leitast við að styrkja þróun Árborgar.', 'https://www.sunnlenska.is/frettir/frambodslisti-framsoknar-i-arborg-samthykktur/'),
  'Guðný Björk Pálmadóttir': ('Guðný Björk Pálmadóttir er hönnuður og nýsköpunarverkfræðingur og er í 2. sæti á lista Viðreisnar í Árborg í sveitarstjórnarkosningum 2026. Þetta er í fyrsta sinn sem Viðreisn gengur fram í bæjarstjórnarkosningum í Árborg.', 'https://vidreisn.is/2026/03/heidrun-leidir-lista-vidreisnar-i-arborg/'),
  'Þorsteinn Haukur Harðarson': ('Þorsteinn Haukur Harðarson er ráðgjafi og er í 3. sæti á lista Viðreisnar í Árborg í sveitarstjórnarkosningum 2026, þar sem flokkurinn gengur í bæjarstjórnarkosningar í fyrsta sinn.', 'https://vidreisn.is/2026/03/heidrun-leidir-lista-vidreisnar-i-arborg/'),
  'Birgir Marteinsson': ('Birgir Marteinsson er lögfræðingur og er í 4. sæti á lista Viðreisnar í Árborg í sveitarstjórnarkosningum 2026. Hann kemur með lögfræðilega þekkingu til framboðslistans og styður uppbyggileg markmið Viðreisnar í sveitarfélaginu.', 'https://vidreisn.is/2026/03/heidrun-leidir-lista-vidreisnar-i-arborg/'),
  'Ingunn Guðmundsdóttir': ('Ingunn Guðmundsdóttir er viðskiptafræðingur og er í 5. sæti á lista Viðreisnar í Árborg í sveitarstjórnarkosningum 2026. Hún kemur með þekkingu á viðskiptaleg og fjárhagsleg málefni í þágu sveitarfélagsins.', 'https://vidreisn.is/2026/03/heidrun-leidir-lista-vidreisnar-i-arborg/'),
  'Sveinn Ægir Birgisson': ('Sveinn Ægir Birgisson er formaður bæjarráðs í Árborg, 28 ára gamall frá Selfossi, og er í 2. sæti á lista Sjálfstæðisflokksins í Árborg. Hann hefur þjónað íbúum sveitarfélagsins sem bæjarfulltrúi og ráðsformaður í fjögur ár og var virkur í ungmennaráðinu áður.', 'https://www.sunnlenska.is/frettir/sveinn-aegir-saekist-eftir-3-saetinu/'),
  'Linda Björk Hilmarsdóttir': ('Linda Björk Hilmarsdóttir er framkvæmdastjóri og er í 3. sæti á lista Sjálfstæðisflokksins í Árborg í sveitarstjórnarkosningum 2026. Hún hefur kynnt framboð sitt með áherslu á þarfir íbúanna og óskefjanlegan vilja til að þróa sveitarfélagið.', 'https://xd.is/2026/03/30/fullskipadur-listi-i-arborg/'),
  'Brynhildur Jónsdóttir': ('Brynhildur Jónsdóttir er forstöðuþroskaþjálfi hjá Álftarima og Vallholti 27, búsetuþjónustu fyrir börn, og sitjandi bæjarfulltrúi Sjálfstæðisflokksins í Árborg, nú í 4. sæti á framboðslistanum. Hún hefur áður verið formaður fulltrúaráðs Sjálfstæðisflokksfélaga í Árborg.', 'https://xd.is/2026/03/30/fullskipadur-listi-i-arborg/'),
  'Þórhildur Ingvadóttir': ('Þórhildur Ingvadóttir er umsjónarmaður Lyfju og varabæjarfulltrúi Sjálfstæðisflokksins í Árborg og er í 5. sæti á framboðslistanum í sveitarstjórnarkosningum 2026. Hún tók þátt í afhendingu umhverfisverðlauna Árborgar 2024.', 'https://xd.is/2026/03/30/fullskipadur-listi-i-arborg/'),
  'Margrét Björk Ólafsdóttir': ('Margrét Björk Ólafsdóttir er hjúkrunarstjóri og er í 2. sæti á lista Samfylkingarinnar og óháðra í Árborg í sveitarstjórnarkosningum 2026. Hún kemur með víðtæka reynslu úr stjórnun heilbrigðisþjónustu til framboðslistans.', 'https://www.sunnlenska.is/frettir/frambodslisti-samfylkingar-og-ohadra-i-arborg-samthykktur/'),
  'Brynjar Þór Elvarsson': ('Brynjar Þór Elvarsson er stjórnsýslufræðingur og er í 3. sæti á lista Samfylkingarinnar og óháðra í Árborg í sveitarstjórnarkosningum 2026. Hann kemur með þekkingu á stjórnsýslu og opinberum málefnum til framboðslistans.', 'https://www.sunnlenska.is/frettir/frambodslisti-samfylkingar-og-ohadra-i-arborg-samthykktur/'),
  'Elísabet Björgvinsdóttir': ('Elísabet Björgvinsdóttir er skemmtanastjóri, samfélagsmiðlastjóri og þjálfari og er í 4. sæti á lista Samfylkingarinnar og óháðra í Árborg í sveitarstjórnarkosningum 2026. Hún sameinar reynslu úr menningarstarfi, samfélagsmiðlum og þjálfun í framboðsstarfi sínu.', 'https://www.sunnlenska.is/frettir/frambodslisti-samfylkingar-og-ohadra-i-arborg-samthykktur/'),
  'Árni Magnússon': ('Árni Magnússon er verkefnastjóri og er í 5. sæti á lista Samfylkingarinnar og óháðra í Árborg í sveitarstjórnarkosningum 2026. Hann kemur með reynslu úr verkefnastjórnun til fjölbreytts og reynslumikils framboðslista.', 'https://www.sunnlenska.is/frettir/frambodslisti-samfylkingar-og-ohadra-i-arborg-samthykktur/'),

  # ARN - Árneshreppur
  'Sigrún Sverrisdóttir': ('Sigrún Sverrisdóttir er á 1. sæti á framboðslista Framtíðar Árneshrepps í sveitarstjórnarkosningum 2026. Hún er frambjóðandi í Árneshreppi á Ströndum þar sem tveir listar buðu fram eftir að frestur var framlengdur.', 'https://kosningasaga.wordpress.com/2026/03/13/frambodslisti-framtidar-arneshrepps/'),
  'Þorgerður Lilja Björnsdóttir': ('Þorgerður Lilja Björnsdóttir er á 2. sæti á framboðslista Framtíðar Árneshrepps í sveitarstjórnarkosningum 2026 í Árneshreppi á Ströndum.', 'https://kosningasaga.wordpress.com/2026/03/13/frambodslisti-framtidar-arneshrepps/'),
  'Róbert Hlífar Ingólfsson': ('Róbert Hlífar Ingólfsson er á 3. sæti á framboðslista Framtíðar Árneshrepps í sveitarstjórnarkosningum 2026 í Árneshreppi á Ströndum.', 'https://kosningasaga.wordpress.com/2026/03/13/frambodslisti-framtidar-arneshrepps/'),
  'Davíð Már Bjarnason': ('Davíð Már Bjarnason er á 4. sæti á framboðslista Framtíðar Árneshrepps í sveitarstjórnarkosningum 2026 í Árneshreppi á Ströndum.', 'https://kosningasaga.wordpress.com/2026/03/13/frambodslisti-framtidar-arneshrepps/'),
  'Thomas Eleguezabal': ('Thomas Eleguezabal er á 5. sæti á framboðslista Framtíðar Árneshrepps í sveitarstjórnarkosningum 2026 í Árneshreppi á Ströndum.', 'https://kosningasaga.wordpress.com/2026/03/13/frambodslisti-framtidar-arneshrepps/'),
  'Arinbjörn Bernharðsson': ('Arinbjörn Bernharðsson er húsasmíðameistari frá Norðurfirði og leiðir framboðslistann Sólstöður í Árneshreppi í sveitarstjórnarkosningum 2026 sem oddviti. Hann situr í hreppsnefnd sveitarfélagsins og kom Sólstöðurlistinn fram eftir framlengdan frest.', 'https://kosningasaga.wordpress.com/2026/04/14/frambodslistinn-solstodur-i-arneshreppi/'),
  'Kristjana María S. Ásbjörnsdóttir': ('Kristjana María S. Ásbjörnsdóttir er á 2. sæti á framboðslistanum Sólstöður í Árneshreppi í sveitarstjórnarkosningum 2026. Hún er frambjóðandi í litlu dreifbýlissveitarfélagi á Ströndum í Vestfjörðum.', 'https://kosningasaga.wordpress.com/2026/04/14/frambodslistinn-solstodur-i-arneshreppi/'),
  'Héðinn Birnir Ásbjörnsson': ('Héðinn Birnir Ásbjörnsson er á 3. sæti á framboðslistanum Sólstöður í Árneshreppi í sveitarstjórnarkosningum 2026 í Árneshreppi á Ströndum.', 'https://kosningasaga.wordpress.com/2026/04/14/frambodslistinn-solstodur-i-arneshreppi/'),
  'Marta Gíslrún Ólafsdóttir': ('Marta Gíslrún Ólafsdóttir er á 4. sæti á framboðslistanum Sólstöður í Árneshreppi í sveitarstjórnarkosningum 2026 í Árneshreppi á Ströndum.', 'https://kosningasaga.wordpress.com/2026/04/14/frambodslistinn-solstodur-i-arneshreppi/'),
  'Axel Thorarensen Hraundal': ('Axel Thorarensen Hraundal er á 5. sæti á framboðslistanum Sólstöður í Árneshreppi í sveitarstjórnarkosningum 2026 í Árneshreppi á Ströndum.', 'https://kosningasaga.wordpress.com/2026/04/14/frambodslistinn-solstodur-i-arneshreppi/'),
}

with open('js/data/candidates.js', 'r', encoding='utf-8') as f:
    content = f.read()

updated = 0
skipped = 0
for name, (bio_text, source_url) in BIOS.items():
    bio_escaped = bio_text.replace("'", "\\'")
    pattern = re.compile(re.escape(name) + r"([^}]*?bio: )null", re.DOTALL)
    def replacer(m, be=bio_escaped): return name + m.group(1) + "'" + be + "'"
    new_content, n = pattern.subn(replacer, content, count=1)
    if n > 0:
        content = new_content
        updated += 1
    else:
        skipped += 1

with open('js/data/candidates.js', 'w', encoding='utf-8') as f:
    f.write(content)

print(f'Updated: {updated}, Skipped (already has bio or not found): {skipped}')
