"""Apply bio batch 3: GAR, GFJ(Grundarfjörður), GGR(Grímsnes), GRN(Grindavík), EJA, FHR, FJB, FJD"""
import re, sys
sys.stdout.reconfigure(encoding='utf-8')

BIOS = {
  # GAR - Garðabær
  'Anna Margrét Steingrímsdóttir': ('Anna Margrét Steingrímsdóttir er markaðs- og þjónustustjóri með meistaragráðu í þjónustufræðum og BSc í markaðssetningu og alþjóðaviðskiptum frá Háskóla Íslands. Hún er í 2. sæti á B-lista Framsóknar í Garðabæ í sveitarstjórnarkosningum 2026.', 'https://www.framsokn.is/blog/hlynur-baeringsson-leidir-framsokn-i-gardabae'),
  'Einar Þór Einarsson': ('Einar Þór Einarsson er framkvæmdastjóri og er í 3. sæti á B-lista Framsóknar í Garðabæ í sveitarstjórnarkosningum 2026.', 'https://www.framsokn.is/blog/hlynur-baeringsson-leidir-framsokn-i-gardabae'),
  'Einar Bárðarson': ('Einar Bárðarson er sjálfstætt starfandi ráðgjafi og framkvæmdastjóri og er í 4. sæti á B-lista Framsóknar í Garðabæ. Hann sat í öðru sæti á lista Framsóknar í Reykjavík í þingkosningum 2024.', 'https://www.ruv.is/frettir/innlent/2024-10-26-einar-bardarson-i-odru-saeti-hja-framsokn-425766'),
  'Inga Amal Hasan': ('Inga Amal Hasan er lögmaður og er í 5. sæti á B-lista Framsóknar í Garðabæ í sveitarstjórnarkosningum 2026.', 'https://www.framsokn.is/blog/hlynur-baeringsson-leidir-framsokn-i-gardabae'),
  'Harpa Þorsteinsdóttir': ('Harpa Þorsteinsdóttir er lýðheilsufræðingur og hefur þjónað sem varabæjarfulltrúi Viðreisnar í Garðabæ. Hún er í 2. sæti á C-lista Viðreisnar og hefur tekið þátt í bæjarstjórnarfundum um velferðarmál og heilsueflingu.', 'https://www.visir.is/g/20262851833d/thessi-leida-vid-reisn-i-garda-bae'),
  'Jón Bjarni Steinsson': ('Jón Bjarni Steinsson er lögmaður og viðburðarhaldsmaður, m.a. eigandi á veitingastöðunum Dillon og Pablo Discobar í Reykjavík. Hann er í 3. sæti á C-lista Viðreisnar í Garðabæ og hefur skrifað um þróun bæjarins árið 2026.', 'https://www.visir.is/g/20262851833d/thessi-leida-vid-reisn-i-garda-bae'),
  'Sigríður Þóra Ásgeirsdóttir': ('Sigríður Þóra Ásgeirsdóttir er kvikmyndagerðarmaður og frumkvöðull, stofnandi Úlfatíma. Hún vann sem framleiðslustjóri á Áramótaskaupinu hjá RÚV og er í 4. sæti á C-lista Viðreisnar í Garðabæ.', 'https://www.visir.is/g/20262851833d/thessi-leida-vid-reisn-i-garda-bae'),
  'Hreiðar Þór Jónsson': ('Hreiðar Þór Jónsson er framkvæmdastjóri og ráðgjafi, fyrrverandi forstjóri stafræna útgáfufyrirtækisins Datera. Hann er í 5. sæti á C-lista Viðreisnar í Garðabæ og hefur bakgrunn í sölu og markaðssetningu hjá Ölgerðinni og alþjóðlegum fyrirtækjum.', 'https://www.mbl.is/vidskipti/frettir/2020/02/10/hreidar_thor_framkvaemdastjori_datera/'),
  'Björg Fenger': ('Björg Fenger er lögfræðingur frá Háskóla Íslands og formaður bæjarráðs Garðabæjar frá 2022. Hún hefur einnig starfað hjá Fjármálaeftirlitinu og velferðarráðuneytinu og er í 2. sæti á D-lista Sjálfstæðisflokksins í Garðabæ.', 'https://xd.is/2026/02/17/almar-leidir-lista-sjalfstaedisflokksins-i-gardabae/'),
  'Margrét Bjarnadóttir': ('Margrét Bjarnadóttir er forseti bæjarstjórnar Garðabæjar frá 2024 og bæjarfulltrúi Sjálfstæðisflokksins frá 2022. Hún stundar lögfræðinám við HR og er dóttir Bjarna Benediktssonar forsætisráðherra; hún er í 3. sæti á D-lista Sjálfstæðisflokksins.', 'https://www.dv.is/frettir/2024/06/07/margret-bjarnadottir-kjorin-forseti-baejarstjornar-gardabaejar/'),
  'Hrannar Bragi Eyjólfsson': ('Hrannar Bragi Eyjólfsson er lögmaður hjá Almenna lífeyrissjóðnum, bæjarfulltrúi Sjálfstæðisflokksins í Garðabæ frá 2022 og formaður íþrótta- og tómstundaráðs. Hann er í 4. sæti á D-lista Sjálfstæðisflokksins og leikur með Stjörnuna í handknattleik.', 'https://www.gardabaer.is/stjornsysla/stjornsyslan/baejarstjorn/adalmenn/hrannar-bragi-eyjolfsson'),
  'Stella Stefánsdóttir': ('Stella Stefánsdóttir er framkvæmdastjóri og varabæjarfulltrúi Sjálfstæðisflokksins í Garðabæ. Hún er með meistaragráðu í nýsköpun og vörustjórnun og hefur starfað hjá Össuri, Deloitte og Robert Bosch í Þýskalandi.', 'https://stellaiframbodi.is/'),
  'Guðjón Pétur Lýðsson': ('Guðjón Pétur Lýðsson er athafnamaður og fyrrverandi fagfótboltamaður sem lék m.a. hjá Helsingborg í Svíþjóð og vann rómverska deildarmeistara. Hann hefur byggt upp fasteignaveldi og er í 2. sæti á GB-lista Garðabæjarlistans í sveitarstjórnarkosningum 2026.', 'https://gamla.mannlif.is/frettir/fotboltamadur-byggir-upp-fasteignaveldi-athafnamadurinn-gudjon-petur-skorar-innan-og-utan-vallar/'),
  'Joanna Marcinkowska': ('Joanna Marcinkowska er verkefnisstjóri sem hefur starfað við samþætting og fjölmenningarmál á Íslandi. Hún er í 3. sæti á GB-lista Garðabæjarlistans í sveitarstjórnarkosningum 2026.', 'https://gardabaejarlistinn.is/listinn/'),
  'Finnur Jónsson': ('Finnur Jónsson er frítímaráðgjafi og kennari og er í 4. sæti á GB-lista Garðabæjarlistans í sveitarstjórnarkosningum 2026.', 'https://gardabaejarlistinn.is/listinn/'),
  'Baldur Ó. Svavarsson': ('Baldur Ó. Svavarsson er arkitekt (FAÍ og FSSA) og meðeigandi Úti og inni arkitektar, ráðgjafafyrirtækis sem stofnað var 1989. Hann er í 5. sæti á GB-lista Garðabæjarlistans.', 'https://en.ja.is/utioginni/Wr775/'),
  'Laufey Gunnþórsdóttir': ('Laufey Gunnþórsdóttir er verkfræðingur og er í 2. sæti á M-lista Miðflokksins í Garðabæ í sveitarstjórnarkosningum 2026.', 'https://www.visir.is/g/20262854836d/midflokkur-kynnir-sex-efstu-i-garda-bae'),
  'Snorri Marteinsson': ('Snorri Marteinsson er fjármálastjóri og starfar sem yfirmaður hjá Wells Fargo Securities. Hann er í 3. sæti á M-lista Miðflokksins í Garðabæ og var einnig í 3. sæti á lista flokksins 2022.', 'https://www.linkedin.com/in/snorrimar/'),
  'Bessí Þóra Jónsdóttir': ('Bessí Þóra Jónsdóttir er hagfræðingur og er í 4. sæti á M-lista Miðflokksins í Garðabæ í sveitarstjórnarkosningum 2026.', 'https://www.visir.is/g/20262854836d/midflokkur-kynnir-sex-efstu-i-garda-bae'),
  'Unnur Ýr Jónsdóttir': ('Unnur Ýr Jónsdóttir er flugfreyja og er í 5. sæti á M-lista Miðflokksins í Garðabæ í sveitarstjórnarkosningum 2026.', 'https://www.visir.is/g/20262854836d/midflokkur-kynnir-sex-efstu-i-garda-bae'),
  'Vilborg Anna Strange Garðarsdóttir': ('Vilborg Anna Strange Garðarsdóttir er söfnunarráðgjafi UN Women Ísland, með BS-gráðu í viðskiptafræði frá HR og meistaragráðu í alþjóðaviðskiptum frá Bifröst. Hún er í 2. sæti á S-lista Samfylkingarinnar í Garðabæ og hefur skrifað um samkeppnishæfni Garðabæjar.', 'https://www.visir.is/g/20262871521d/sterkur-og-skapandi-gardabaer'),
  'Rakel Margrét Viggósdóttir': ('Rakel Margrét Viggósdóttir er í 3. sæti á S-lista Samfylkingarinnar í Garðabæ í sveitarstjórnarkosningum 2026.', 'https://xs.is/sveitarstjornarfolk'),
  'Vilmar Pétursson': ('Vilmar Pétursson er á 4. sæti á S-lista Samfylkingarinnar í Garðabæ í sveitarstjórnarkosningum 2026.', 'https://xs.is/sveitarstjornarfolk'),
  'Ögmundur Árni Sveinsson': ('Ögmundur Árni Sveinsson er á 5. sæti á S-lista Samfylkingarinnar í Garðabæ í sveitarstjórnarkosningum 2026.', 'https://xs.is/sveitarstjornarfolk'),

  # GFJ - Grundarfjarðarbær (coded as GFJ)
  'Fannar Þór Þorfinnsson': ('Fannar Þór Þorfinnsson er byggingarverkfræðingur með BS frá HR (2017) og reynslu sem verkefnastjóri hjá THG arkitektum. Hann er oddviti GFB-lista í Grundarfjarðarbæ og flutti til bæjarins haustið 2021.', 'https://www.grundarfjordur.is/is/frettir-og-tilkynningar/frambodslistar-i-grundarfjardarbae-1'),
  'Signý Gunnarsdóttir': ('Signý Gunnarsdóttir er bæjarfulltrúi í Grundarfjarðarbæ og hefur starfað sem nefndarmaður í bæjarstjórn á kjörtímabilinu 2022–2026. Hún er í 2. sæti á GFB-lista Framsóknar og félaga.', 'https://www.grundarfjordur.is/is/frettir-og-tilkynningar/frambodslistar-i-grundarfjardarbae-1'),
  'Aðalsteinn Jósepsson': ('Aðalsteinn Jósepsson er á 3. sæti á GFB-lista Framsóknar og félaga í Grundarfjarðarbæ í sveitarstjórnarkosningum 2026.', 'https://www.grundarfjordur.is/is/frettir-og-tilkynningar/frambodslistar-i-grundarfjardarbae-1'),
  'Þuríður Gía Jóhannesdóttir': ('Þuríður Gía Jóhannesdóttir er á 4. sæti á GFB-lista Framsóknar og félaga í Grundarfjarðarbæ í sveitarstjórnarkosningum 2026.', 'https://www.grundarfjordur.is/is/frettir-og-tilkynningar/frambodslistar-i-grundarfjardarbae-1'),
  'Eiríkur Þór Halldórsson': ('Eiríkur Þór Halldórsson er á 5. sæti á GFB-lista Framsóknar og félaga í Grundarfjarðarbæ í sveitarstjórnarkosningum 2026.', 'https://www.grundarfjordur.is/is/frettir-og-tilkynningar/frambodslistar-i-grundarfjardarbae-1'),
  'Jósef Kjartansson': ('Jósef Kjartansson er forseti bæjarstjórnar Grundarfjarðarbæjar og oddviti GFD-lista Sjálfstæðisflokks og óháðra í sveitarstjórnarkosningum 2026. Hann hefur setið í bæjarstjórn og hefur reynslu af stjórnsýslu sveitarfélagsins.', 'https://xd.is/josef-o-kjartansson/'),
  'Sigurhanna Ágústa Einarsdóttir': ('Sigurhanna Ágústa Einarsdóttir er framkvæmdastjóri og einka- og markþjálfari, og er formaður bæjarráðs í Grundarfjarðarbæ. Hún er í 2. sæti á GFD-lista Sjálfstæðisflokks og óháðra.', 'https://kosningasaga.wordpress.com/2026/03/27/frambodslisti-sjalfstaedisflokks-og-ohadra-i-grundarfirdi-2/'),
  'Bjarni Sigurbjörnsson': ('Bjarni Sigurbjörnsson er á 3. sæti á GFD-lista Sjálfstæðisflokks og óháðra í Grundarfjarðarbæ í sveitarstjórnarkosningum 2026.', 'https://www.grundarfjordur.is/is/frettir-og-tilkynningar/frambodslistar-i-grundarfjardarbae-1'),
  'Sigurður Gísli Guðjónsson': ('Sigurður Gísli Guðjónsson er á 4. sæti á GFD-lista Sjálfstæðisflokks og óháðra í Grundarfjarðarbæ í sveitarstjórnarkosningum 2026.', 'https://www.grundarfjordur.is/is/frettir-og-tilkynningar/frambodslistar-i-grundarfjardarbae-1'),
  'Davíð Magnússon': ('Davíð Magnússon er á 5. sæti á GFD-lista Sjálfstæðisflokks og óháðra í Grundarfjarðarbæ í sveitarstjórnarkosningum 2026.', 'https://www.grundarfjordur.is/is/frettir-og-tilkynningar/frambodslistar-i-grundarfjardarbae-1'),

  # GGR - Grímsnes- og Grafningshreppur
  'Guðmundur Finnbogason': ('Guðmundur Finnbogason er skólastjóri Þjórsárskóla og býr á Borg í Grímsnesi. Hann leiðir GGA-listann í Grímsnes- og Grafningshreppi í sveitarstjórnarkosningum 2026.', 'https://www.sunnlenska.is/frettir/gudmundur-leidir-nytt-frambod-i-gogg/'),
  'Rebekka Lind Guðmundsdóttir': ('Rebekka Lind Guðmundsdóttir er kennari á Kerhólsskóla og fulltrúi starfsmanna skólans. Hún er í 2. sæti á GGA-lista í Grímsnes- og Grafningshreppi.', 'https://www.sunnlenska.is/frettir/gudmundur-leidir-nytt-frambod-i-gogg/'),
  'Bergur Guðmundsson': ('Bergur Guðmundsson er þjónustutæknimaður hjá DeLaval og bóndi á Brjánsstöðum í Grímsnesi. Hann er í 3. sæti á GGA-lista í Grímsnes- og Grafningshreppi.', 'https://www.sunnlenska.is/frettir/gudmundur-leidir-nytt-frambod-i-gogg/'),
  'Ragnheiður Eggertsdóttir': ('Ragnheiður Eggertsdóttir er verslunarstjóri og rekstrarstjóri og er sveitarstjórnarfulltrúi í Grímsnes- og Grafningshreppi. Hún er í 4. sæti á GGA-lista.', 'https://www.sunnlenska.is/frettir/gudmundur-leidir-nytt-frambod-i-gogg/'),
  'Pétur Thomsen': ('Pétur Thomsen er ljósmyndari og myndlistarmaður sem hlaut viðurkenninguna Listamaður ársins 2025. Hann er með MFA-gráðu frá École nationale supérieure de la photographie í Arles í Frakklandi og búsett í Sólheimum.', 'https://peturthomsen.is/about/'),
  'Andrés Bertelsen': ('Andrés Bertelsen er rekstrarstjóri og starfar við hugbúnaðarþróun í alþjóðlegu nýsköpunarverkefni. Hann er uppruninn frá Skagafirði en búsettur í Grímsnesi og leiðir GGO-listann „Betri sveit – fyrir okkur öll".', 'https://www.sunnlenska.is/frettir/listi-betri-sveitar-tilbuinn/'),
  'Ragna Ívarsdóttir': ('Ragna Ívarsdóttir er kaupsýslumaður og er í 2. sæti á GGO-lista „Betri sveitar" í Grímsnes- og Grafningshreppi í sveitarstjórnarkosningum 2026.', 'https://www.sunnlenska.is/frettir/listi-betri-sveitar-tilbuinn/'),
  'Friðrik Guðmundsson': ('Friðrik Guðmundsson er aðstoðarvallarmeistari á golfvelli Öndverðarness og er í 3. sæti á GGO-lista í Grímsnes- og Grafningshreppi.', 'https://www.sunnlenska.is/frettir/listi-betri-sveitar-tilbuinn/'),
  'Viðar Marinósson': ('Viðar Marinósson er löggildur fasteignasali og er í 4. sæti á GGO-lista „Betri sveitar" í Grímsnes- og Grafningshreppi í sveitarstjórnarkosningum 2026.', 'https://www.sunnlenska.is/frettir/listi-betri-sveitar-tilbuinn/'),
  'Gunnlaugur I. Ingimarsson': ('Gunnlaugur I. Ingimarsson er rekstrarstjóri og er í 5. sæti á GGO-lista „Betri sveitar" í Grímsnes- og Grafningshreppi í sveitarstjórnarkosningum 2026.', 'https://www.sunnlenska.is/frettir/listi-betri-sveitar-tilbuinn/'),

  # GRN - Grindavík (coded as GRN)
  'Ásrún Helga Kristinsdóttir': ('Ásrún Helga Kristinsdóttir er bæjarforseti Grindavíkur og grunnskólakennari á Grunnskóla Grindavíkur þar sem hún hefur starfað frá 2001. Hún leiðir B-lista Framsóknar í Grindavík og hefur setið í bæjarstjórn frá 2014.', 'https://www.ruv.is/frettir/innlent/2022-03-31-asrun-helga-leidir-lista-framsoknar-i-grindavik'),
  'Þorleifur Ólafsson': ('Þorleifur Ólafsson er þjálfari og kennari og er í 2. sæti á B-lista Framsóknar í Grindavík í sveitarstjórnarkosningum 2026.', 'https://kosningasaga.wordpress.com/2026/03/18/frambodslisti-framsoknar-i-grindavik/'),
  'Inga Fanney Rúnarsdóttir': ('Inga Fanney Rúnarsdóttir er bæjarfulltrúi í Grindavík og ráðgjafi í velferðardeild. Hún er í 3. sæti á B-lista Framsóknar í Grindavík og hefur verið áheyrnarfulltrúi á nefndarfundum bæjarins.', 'https://www.grindavik.is/baejarstjorn/'),
  'Elínborg Ingvarsdóttir': ('Elínborg Ingvarsdóttir er á 4. sæti á B-lista Framsóknar í Grindavík í sveitarstjórnarkosningum 2026.', 'https://kosningasaga.wordpress.com/2026/03/18/frambodslisti-framsoknar-i-grindavik/'),
  'Benedikt Óskar Steingrímsson': ('Benedikt Óskar Steingrímsson er jarðfræðingur með BS frá Háskóla Íslands og starfar hjá Istaki í Noregi. Hann er uppvaxinn á Vestmannaeyjum en búsettur í Grindavík og er í 5. sæti á B-lista Framsóknar.', 'https://www.mbl.is/greinasafn/grein/1573819/'),
  'Guðbjörg Eyjólfsdóttir': ('Guðbjörg Eyjólfsdóttir er formaður Járngerðar, borgaralegs samtaka um endurreisn og framtíð Grindavíkur, kjörin í mars 2025. Hún er í 1. sæti á D-lista Sjálfstæðisflokksins í Grindavík.', 'https://kosningasaga.wordpress.com/2026/03/08/urslit-i-skodanakonnun-sjalfstaedisflokksins-i-grindavik/'),
  'Hjálmar Hallgrímsson': ('Hjálmar Hallgrímsson er lögreglumaður á Suðurnesjum og formaður bæjarráðs Grindavíkur, þar sem hann hefur verið bæjarfulltrúi Sjálfstæðisflokksins frá 2014. Hann leiðir D-lista og er oddviti flokksins í bænum.', 'https://xd.is/hjalmar-hallgrimsson/'),
  'Ómar Davíð Ólafsson': ('Ómar Davíð Ólafsson er bæjarfulltrúi á D-lista Sjálfstæðisflokksins í Grindavík og hefur setið í Innviðanefnd bæjarins. Hann er í 3. sæti á D-lista í sveitarstjórnarkosningum 2026.', 'https://xd.is/grindavik-7-saeti-omar-david-olafsson/'),
  'Ólöf Rún Óladóttir': ('Ólöf Rún Óladóttir er á 4. sæti á D-lista Sjálfstæðisflokksins í Grindavík í sveitarstjórnarkosningum 2026.', 'https://xd.is/sveitastjornir/grindavik/'),
  'Eva Lind Matthíasdóttir': ('Eva Lind Matthíasdóttir er á 5. sæti á D-lista Sjálfstæðisflokksins í Grindavík í sveitarstjórnarkosningum 2026.', 'https://xd.is/sveitastjornir/grindavik/'),
  'Magnús Már Jakobsson': ('Magnús Már Jakobsson er formaður Verkalýðsfélags Grindavíkur og leiðir M-lista Miðflokksins í Grindavík í sveitarstjórnarkosningum 2026.', 'https://www.grindavik.is/v/21241'),
  'Björn Steinar Brynjólfsson': ('Björn Steinar Brynjólfsson er á 2. sæti á M-lista Miðflokksins í Grindavík í sveitarstjórnarkosningum 2026.', 'https://www.grindavik.is/v/21241'),
  'Signý Lind Elíasdóttir': ('Signý Lind Elíasdóttir er á 4. sæti á M-lista Miðflokksins í Grindavík í sveitarstjórnarkosningum 2026.', 'https://www.grindavik.is/v/21241'),
  'Eydís Ármannsdóttir': ('Eydís Ármannsdóttir er á 5. sæti á M-lista Miðflokksins í Grindavík í sveitarstjórnarkosningum 2026.', 'https://www.grindavik.is/v/21241'),

  # EJA - Eyjafjarðarsveit
  'Hermann Ingi Gunnarsson': ('Hermann Ingi Gunnarsson er bóndi og oddviti sveitarstjórnar Eyjafjarðarsveitar sem leiðir F-listann til sveitarstjórnarkosninganna 2026. Hann hefur setið í sveitarstjórn og starfar á búi á svæðinu.', 'https://kaffid.is/tvo-frambod-i-eyjafjardarsveit/'),
  'Berglind Kristinsdóttir': ('Berglind Kristinsdóttir er bóndi og umönnunarfólk frá Hrafnagili sem skipar 2. sæti á F-listanum í Eyjafjarðarsveit 2026. Hún er hluti af fjölbreyttum lista sem leggur áherslu á landbúnað og sveitasamfélagið.', 'https://kaffid.is/tvo-frambod-i-eyjafjardarsveit/'),
  'Gestur Júlíusson': ('Gestur Júlíusson er dýralæknir og formaður Dýralæknaráðs hjá Matvælastofnun sem skipar 3. sæti á F-listanum í Eyjafjarðarsveit 2026. Hann rekur dýralæknastofu í Lögmannshlíð.', 'https://kaffid.is/tvo-frambod-i-eyjafjardarsveit/'),
  'Inga Vala Gísladóttir': ('Inga Vala Gísladóttir er deildarstjóri við leikskólann Krummakot í Eyjafjarðarsveit sem skipar 4. sæti á F-listanum 2026. Hún hefur starfað í leikskólaþjónustu sveitarfélagsins um árabil.', 'https://kaffid.is/tvo-frambod-i-eyjafjardarsveit/'),
  'Hákon B. Harðarson': ('Hákon B. Harðarson er bóndi í Eyjafjarðarsveit og formaður Sauðfjárræktarfélags Eyjafjarðar sem skipar 5. sæti á F-listanum 2026. Hann hefur lagt af mörkum til landbúnaðarsamfélagsins á svæðinu.', 'https://www.esveit.is/eyjafjardarsveit/frettir/tilkynning-fra-kjorstjorn-eyjafjardarsveitar-tveir-listar-samthykktir'),
  'Guðmundur Sigurbjörn Óskarsson': ('Guðmundur Sigurbjörn Óskarsson er bóndi í Eyjafjarðarsveit sem leiðir K-listann í sveitarstjórnarkosningum 2026. Hann sat í sveitarstjórn og skipulagsnefnd sveitarfélagsins á síðastliðnu kjörtímabili.', 'https://www.esveit.is/eyjafjardarsveit/frettir/tilkynning-fra-kjorstjorn-eyjafjardarsveitar-tveir-listar-samthykktir'),
  'Linda Lárusdóttir': ('Linda Lárusdóttir er þroskaþjálfi og sérkennslustjóri frá Bakkatröð sem skipar 2. sæti á K-listanum í Eyjafjarðarsveit 2026. Hún hefur sérfræðiþekkingu á menntamálum og þroskafræði.', 'https://kaffid.is/gudmundur-leidir-k-listann-i-eyjafjardarsveit/'),
  'Friðrik Karlsson': ('Friðrik Karlsson er vélfræðingur og sviðsstjóri frá Kambi í Eyjafjarðarsveit sem skipar 3. sæti á K-listanum 2026. Hann kemur með tæknilega sérfræðiþekkingu inn í sveitarstjórnina.', 'https://kosningasaga.wordpress.com/2026/04/06/frambodslisti-k-listans-i-eyjafjardarsveit-2/'),
  'Sóley Kjerúlf Svansdóttir': ('Sóley Kjerúlf Svansdóttir er sérkennslustjóri sem skipar 4. sæti á K-listanum í Eyjafjarðarsveit 2026. Hún hefur þekkingu á menntamálum og vill vanda til verks þegar kemur að þjónustu við íbúa.', 'https://kaffid.is/tvo-frambod-i-eyjafjardarsveit/'),
  'Ragnar Jónsson': ('Ragnar Jónsson er bóndi og bifvélavirki í Eyjafjarðarsveit sem skipar 5. sæti á K-listanum í sveitarstjórnarkosningum 2026. Hann kemur með bæði landbúnaðar- og verkþekkingu inn í sveitarstjórnina.', 'https://kaffid.is/tvo-frambod-i-eyjafjardarsveit/'),

  # FHR - Flóahreppur
  'Árni Eiríksson': ('Árni Eiríksson er oddviti Flóahrepps og leiðir Framfaralistann (I-lista) í sveitarstjórnarkosningum 2026. Hann situr í sveitarstjórn og er búsettur á Skúfslæk Norðurbæ.', 'https://www.sunnlenska.is/frettir/arni-leidir-framfaralistann-afram/'),
  'Hulda Kristjánsdóttir': ('Hulda Kristjánsdóttir er sveitarstjóri Flóahrepps og er í 2. sæti á I-listanum 2026. Hún starfar á Forsæti 2 og hefur umsjón með daglegum rekstri sveitarfélagsins.', 'https://www.sunnlenska.is/frettir/arni-leidir-framfaralistann-afram/'),
  'Walter Fannar Kristjánsson': ('Walter Fannar Kristjánsson er laganemar og sveitarstjórnarmaður frá Litlu-Reykjum sem skipar 3. sæti á I-listanum í Flóahreppi 2026. Hann er hluti af yngri kynslóð sem kemur til sögunnar í sveitarstjórnarmálum.', 'https://www.sunnlenska.is/frettir/arni-leidir-framfaralistann-afram/'),
  'Hrafnhildur Helga Guðmundsdóttir': ('Hrafnhildur Helga Guðmundsdóttir er ríðkennari og sérfræðingur frá Hólshúsum sem skipar 4. sæti á I-listanum í Flóahreppi 2026. Hún kemur með menntun og reynslu á sviði hestamennsku.', 'https://www.sunnlenska.is/frettir/arni-leidir-framfaralistann-afram/'),
  'Hjalti Guðmundsson': ('Hjalti Guðmundsson er meistarasmiður og kennari sem skipar 5. sæti á I-listanum í Flóahreppi 2026. Hann kemur með iðnþekkingu sína inn í Framfaralistann.', 'https://www.sunnlenska.is/frettir/arni-leidir-framfaralistann-afram/'),
  'Almar Sigurðsson': ('Almar Sigurðsson er ferðaþjónustubóndi frá Lambastöðum sem leiðir T-listann í Flóahreppi í sveitarstjórnarkosningum 2026. Hann kemur með reynslu á sviði ferðaþjónustu og landbúnaðar.', 'https://kosningasaga.wordpress.com/2026/04/10/frambodslisti-t-listans-i-floahreppi-2/'),
  'Ágúst Hjálmarsson': ('Ágúst Hjálmarsson er verkamaður og áhugabóndi frá Dalsmynni sem skipar 2. sæti á T-listanum í Flóahreppi 2026. Hann kemur með fjölbreytta reynslu úr vinnu og landbúnaði.', 'https://kosningasaga.wordpress.com/2026/04/10/frambodslisti-t-listans-i-floahreppi-2/'),
  'Halla Kjartansdóttir': ('Halla Kjartansdóttir er múrari og bóndi frá Ölvisholti sem skipar 3. sæti á T-listanum í Flóahreppi 2026. Hún kemur með handverks- og landbúnaðarþekkingu inn í sveitarstjórnina.', 'https://kosningasaga.wordpress.com/2026/04/10/frambodslisti-t-listans-i-floahreppi-2/'),
  'Ólafur Sveinn Gíslason': ('Ólafur Sveinn Gíslason er myndlistarmaður frá Þúfugörðum sem skipar 4. sæti á T-listanum í Flóahreppi 2026. Hann kemur með skapandi sjónarmiðum inn í sveitarstjórnarmál.', 'https://kosningasaga.wordpress.com/2026/04/10/frambodslisti-t-listans-i-floahreppi-2/'),
  'Anný Ingimarsdóttir': ('Anný Ingimarsdóttir er félagsráðgjafi frá Vorsabæjarhjáleigu sem skipar 5. sæti á T-listanum í Flóahreppi 2026. Hún kemur með sérfræðiþekkingu á sviði félagsmála inn í sveitarstjórnarstarfið.', 'https://kosningasaga.wordpress.com/2026/04/10/frambodslisti-t-listans-i-floahreppi-2/'),

  # FJB - Fjallabyggð
  'Kristín Ágústa Eiðsdóttir': ('Kristín Ágústa Eiðsdóttir er leikskólakennaranemi og starfsmaður leikskóla sem skipar 2. sæti á D-lista Sjálfstæðisflokksins í Fjallabyggð 2026. Hún kemur með menntun og reynslu í leikskólastarfi.', 'https://kaffid.is/thrir-frambodslistar-i-fjallabyggd/'),
  'Guðrún Sif Guðbrandsdóttir': ('Guðrún Sif Guðbrandsdóttir er fjármálastjóri sem skipar 3. sæti á D-lista Sjálfstæðisflokksins í Fjallabyggð 2026. Hún kemur með fjármálaþekkingu og stjórnunarreynslu inn í sveitarstjórnina.', 'https://kaffid.is/thrir-frambodslistar-i-fjallabyggd/'),
  'Viktor Freyr Elísson': ('Viktor Freyr Elísson er fjármálasérfræðingur sem skipar 4. sæti á D-lista Sjálfstæðisflokksins í Fjallabyggð 2026. Hann kemur með sérfræðiþekkingu á sviði fjármála og hagstjórnar.', 'https://kaffid.is/thrir-frambodslistar-i-fjallabyggd/'),
  'Stefán Júlíusson': ('Stefán Júlíusson er hótelráðgjafi sem skipar 5. sæti á D-lista Sjálfstæðisflokksins í Fjallabyggð 2026. Hann kemur með reynslu úr ferðaþjónustu og rekstrarmálum.', 'https://kaffid.is/thrir-frambodslistar-i-fjallabyggd/'),
  'Kristinn Kristjánsson': ('Kristinn Kristjánsson er verslunarstjóri sem skipar 2. sæti á H-listanum í Fjallabyggð í sveitarstjórnarkosningum 2026. Hann kemur með reynslu úr verslun og þjónustu.', 'https://kaffid.is/thrir-frambodslistar-i-fjallabyggd/'),
  'Ásgeir Logi Ásgeirsson': ('Ásgeir Logi Ásgeirsson er framkvæmdastjóri sem skipar 3. sæti á H-listanum í Fjallabyggð 2026. Hann kemur með stjórnunarreynslu og þekkingu á rekstri fyrirtækja.', 'https://kaffid.is/thrir-frambodslistar-i-fjallabyggd/'),
  'Auður Ösp H. Magnúsdóttir': ('Auður Ösp H. Magnúsdóttir er hjúkrunarfræðinemi sem skipar 4. sæti á H-listanum í Fjallabyggð 2026. Hún kemur með ungar faglegar sjónarmiðir á heilbrigðismál og velferð.', 'https://kaffid.is/thrir-frambodslistar-i-fjallabyggd/'),
  'Guðlaugur Magnús Ingason': ('Guðlaugur Magnús Ingason er ökukennari sem skipar 5. sæti á H-listanum í Fjallabyggð í sveitarstjórnarkosningum 2026. Hann kemur með kennslureynslu og þekkingu á samgöngumálum.', 'https://kaffid.is/thrir-frambodslistar-i-fjallabyggd/'),
  'Pálmi Blængsson': ('Pálmi Blængsson er verkefnastjóri sem skipar 2. sæti á S-lista Jafnaðarmanna og óháðra í Fjallabyggð 2026. Hann kemur með skipulagsþekkingu og reynslu í verkefnastjórnun.', 'https://kaffid.is/thrir-frambodslistar-i-fjallabyggd/'),
  'Sæunn Gísladóttir': ('Sæunn Gísladóttir er verkefnastjóri við Rannsóknamiðstöð Háskólans á Akureyri (RHA) og sérfræðingur í svæðaþróun og jafnréttismálum sem skipar 3. sæti á S-listanum í Fjallabyggð 2026. Hún lauk meistaragráðu í þróunarfræðum og hefur starfað að norrænum rannsóknarverkefnum.', 'https://www.rha.is/en/moya/ugla/staff/saeunn-gisladottir'),
  'Guðjón M. Ólafsson': ('Guðjón M. Ólafsson er ráðgjafi og sveitarstjórnarmaður sem skipar 4. sæti á S-listanum í Fjallabyggð 2026. Hann hefur áður setið í sveitarstjórn og kemur með reynslu úr ráðgjafafyrirtæki.', 'https://kaffid.is/thrir-frambodslistar-i-fjallabyggd/'),
  'Kristín M. Halldórsdóttir': ('Kristín M. Halldórsdóttir er gæðastjóri sem skipar 5. sæti á S-lista Jafnaðarmanna og óháðra í Fjallabyggð 2026. Hún kemur með gæðastjórnunarþekkingu inn í sveitarstjórnarmál.', 'https://kaffid.is/thrir-frambodslistar-i-fjallabyggd/'),

  # FJD - Fjarðabyggð
  'Birgir Jónsson': ('Birgir Jónsson er framhaldsskólakennari og hefur setið í bæjarstjórn Fjarðabyggðar. Hann er í 2. sæti á B-lista Framsóknar í Fjarðabyggð 2026 og hefur þekkingu á skólakerfinu.', 'https://www.fjardabyggd.is/stjornsysla/baejarstjorn/sveitarstjornarkosningar-2026'),
  'Helga Rakel Arnardóttir': ('Helga Rakel Arnardóttir er skrifstofustjóri og sjúkraflutningamaður sem skipar 3. sæti á B-lista Framsóknar í Fjarðabyggð 2026. Hún sameinar stjórnunarreynslu og heilbrigðisþekkingu.', 'https://www.fjardabyggd.is/stjornsysla/baejarstjorn/sveitarstjornarkosningar-2026'),
  'Sigurjón Andrés Jónasson': ('Sigurjón Andrés Jónasson er á 4. sæti á B-lista Framsóknar í Fjarðabyggð í sveitarstjórnarkosningum 2026. Listinn leggur áherslu á þróun sveitarfélagsins og framfarir á landsbyggðinni.', 'https://www.fjardabyggd.is/stjornsysla/baejarstjorn/sveitarstjornarkosningar-2026'),
  'Bjarney Birta Bergsdóttir': ('Bjarney Birta Bergsdóttir er á 5. sæti á B-lista Framsóknar í Fjarðabyggð í sveitarstjórnarkosningum 2026. Framsókn í Fjarðabyggð lagði listann fram á fundi í Þórðarbúð á Reyðarfirði.', 'https://www.fjardabyggd.is/stjornsysla/baejarstjorn/sveitarstjornarkosningar-2026'),
  'Kristinn Þór Jónasson': ('Kristinn Þór Jónasson er þjónustomsstjóri og bæjarfulltrúi Sjálfstæðisflokksins í Fjarðabyggð sem skipar 2. sæti á D-listanum 2026. Hann hefur setið í bæjarstjórn Fjarðabyggðar á yfirstandandi kjörtímabili.', 'https://xd.is/2026/02/23/frambodslisti-sjalfstaedisflokksins-i-fjardabyggd-samthykktur-2/'),
  'Þórdís Mjöll Benediktsdóttir': ('Þórdís Mjöll Benediktsdóttir er leikskólastjóri Dalborgar á Eskifirði og bæjarfulltrúi Sjálfstæðisflokksins í Fjarðabyggð sem skipar 3. sæti á D-listanum 2026. Hún er móðir tveggja barna og hefur lagt sig fram um menntun og uppeldi.', 'https://xd.is/2026/02/23/frambodslisti-sjalfstaedisflokksins-i-fjardabyggd-samthykktur-2/'),
  'Húnbogi Sólon Gunnþórsson': ('Húnbogi Sólon Gunnþórsson er verkefnastjóri sem skipar 4. sæti á D-lista Sjálfstæðisflokksins í Fjarðabyggð 2026. Hann starfar hjá SVN og kemur með reynslu í verkefnastjórnun.', 'https://xd.is/2026/02/23/frambodslisti-sjalfstaedisflokksins-i-fjardabyggd-samthykktur-2/'),
  'Tanja Tómasdóttir': ('Tanja Tómasdóttir er aðstoðarmaður gæðastjóra sem skipar 5. sæti á D-lista Sjálfstæðisflokksins í Fjarðabyggð 2026. Hún kemur með þekkingu á gæðastjórnun inn í sveitarstjórnina.', 'https://xd.is/2026/02/23/frambodslisti-sjalfstaedisflokksins-i-fjardabyggd-samthykktur-2/'),
  'Alma Sigurbjörnsdóttir': ('Alma Sigurbjörnsdóttir er yfirsálfræðingur hjá Fjarðabyggð og skipar 2. sæti á M-lista Miðflokksins í sveitarstjórnarkosningum 2026. Hún kemur með sérfræðiþekkingu á sálfræðiþjónustu og velferðarmálum.', 'https://www.fjardabyggd.is/stjornsysla/vinnustadurinn/starfsmenn'),
  'Baldur Marteinn Einarsson': ('Baldur Marteinn Einarsson er útgerðarstjóri Eskju og meðlimur í Hinu Íslenska Sjávarútvegsfræðafélagi sem skipar 3. sæti á M-lista Miðflokksins í Fjarðabyggð 2026. Hann kemur með sérfræðiþekkingu á sjávarútvegi og rekstri.', 'https://www.fjardabyggd.is/stjornsysla/baejarstjorn/sveitarstjornarkosningar-2026'),
  'Hafþór Eiríksson': ('Hafþór Eiríksson er á 4. sæti á M-lista Miðflokksins í Fjarðabyggð í sveitarstjórnarkosningum 2026. Miðflokkur í Fjarðabyggð lagði framboðslista sinn fram í mars 2026.', 'https://www.fjardabyggd.is/stjornsysla/baejarstjorn/sveitarstjornarkosningar-2026'),
  'Anna Guðný Gunnarsdóttir': ('Anna Guðný Gunnarsdóttir er á 5. sæti á M-lista Miðflokksins í Fjarðabyggð í sveitarstjórnarkosningum 2026. Listinn leggur áherslu á fjölbreytta faglega þekkingu í þágu sveitarfélagsins.', 'https://www.fjardabyggd.is/stjornsysla/baejarstjorn/sveitarstjornarkosningar-2026'),
  'Hjördís Helga Seljan': ('Hjördís Helga Seljan er menntaráðgjafi og bæjarfulltrúi Fjarðalistans frá Reyðarfirði sem leiðir S-listann í Fjarðabyggð 2026. Hún hefur setið í bæjarstjórn síðan 2018 og þjónaði sem forseti bæjarstjórnar.', 'https://austurfrett.is/component/tags/tag/sveitarstjornarkosningar-2026'),
  'Valborg Ösp Á. Warén': ('Valborg Ösp Á. Warén er verkefnastjóri sem skipar 3. sæti á S-lista Fjarðalistans í Fjarðabyggð 2026. Hún kemur með reynslu í verkefnastjórnun og skipulagi.', 'https://www.fjardabyggd.is/stjornsysla/baejarstjorn/sveitarstjornarkosningar-2026'),
  'Adam Ingi Guðlaugsson': ('Adam Ingi Guðlaugsson er á 4. sæti á S-lista Fjarðalistans í Fjarðabyggð í sveitarstjórnarkosningum 2026. Listinn samanstendur af meðlimum Fjarðalistans og Samfylkingar sem hafa starfað saman í bæjarstjórn.', 'https://www.fjardabyggd.is/stjornsysla/baejarstjorn/sveitarstjornarkosningar-2026'),
  'Arndís Bára Pétursdóttir': ('Arndís Bára Pétursdóttir er á 5. sæti á S-lista Fjarðalistans í Fjarðabyggð í sveitarstjórnarkosningum 2026. Fjarðalistinn hefur boðið fram lista í sveitarstjórnarkosningum frá 1998.', 'https://www.fjardabyggd.is/stjornsysla/baejarstjorn/sveitarstjornarkosningar-2026'),
}

with open('js/data/candidates.js', 'r', encoding='utf-8') as f:
    content = f.read()

updated = 0
skipped = 0
for name, (bio_text, source_url) in BIOS.items():
    bio_escaped = bio_text.replace("'", "\\'")
    pattern = re.compile(re.escape(name) + r"([^}]*?bio: )null", re.DOTALL)
    def replacer(m, be=bio_escaped): return name + m.group(1) + "'" + be + "'"
    new_content, n = pattern.subn(replacer, content, count=1)
    if n > 0:
        content = new_content
        updated += 1
    else:
        skipped += 1

with open('js/data/candidates.js', 'w', encoding='utf-8') as f:
    f.write(content)

print(f'Updated: {updated}, Skipped (already has bio or not found): {skipped}')
