"""Apply bio batch 1: AKR, HAF, RNB, KOP, NPG"""
import re, sys
sys.stdout.reconfigure(encoding='utf-8')

BIOS = {
  # AKR - Akranes
  'Ragnar Baldvin Sæmundsson': ('Ragnar Baldvin Sæmundsson er verslunarmaður og bæjarfulltrúi á Akranesi. Hann leiddi lista Framsóknar og frjálsra á Akranesi sem oddviti í sveitarstjórnarkosningum 2018 og 2022 og gegndi stöðu annars varaforseta bæjarstjórnar Akraness á kjörtímabilinu 2022–2026.', 'https://skessuhorn.is/2022/03/09/framsokn-med-frjalsum-kynna-frambodslista-a-akranesi/'),
  'Liv Åse Skarstad': ('Liv Åse Skarstad er verkefnastjóri og bæjarfulltrúi á Akranesi fyrir Framsókn og frjálsa á kjörtímabilinu 2022–2026. Hún skrifaði grein í apríl 2026 þar sem hún fjallaði um samband Akraneskaupstaðar og Hvalfjarðarsveitar og tók afstöðu gegn umræðum um sameiningu sveitarfélaganna.', 'https://www.visir.is/g/20262872381d/haettum-ad-tala-um-sameiningu-'),
  'Sædís Alexía Sigurmundsdóttir': ('Sædís Alexía Sigurmundsdóttir er skrifstofustjóri á skrifstofu bæjarstjóra Akraneskaupstaðar og bæjarfulltrúi fyrir Framsókn á kjörtímabilinu 2022–2026. Hún hefur starfað hjá Akraneskaupstað í um áratug, meðal annars sem deildastjóri stjórnsýslu- og fjármáladeildar, og er með próf í viðskiptafræðirétti og meistaragráðu í forystu og stjórnun með áherslu á verkefnastjórnun.', 'https://skagafrettir.is/2021/01/19/saedis-alexia-nyr-skrifstofustjori-hja-akraneskaupstad/'),
  'Karl Jóhann Haagensen': ('Karl Jóhann Haagensen er sérfræðingur og starfaði sem verkefnastjóri í skipulags- og umhverfisdeild Akraneskaupstaðar og tók síðan tímabundið að sér starf byggingarfulltrúa hjá sveitarfélaginu. Hann útskrifaðist meðal annars frá slökkvilið Akraness og Hvalfjarðarsveitar árið 2022.', 'https://skessuhorn.is/2022/05/11/tiu-slokkvilidsmenn-utskrifadir-hja-slokkvilidi-akraness-og-hvalfjardarsveitar'),
  'Aníta Eir Einarsdóttir': ('Aníta Eir Einarsdóttir er yfirhjúkrunarfræðingur á heilsugæslu Akraness (HVE). Hún gegnir yfirstjórnunarhlutverki hjúkrunarfræðinga á heilsugæslustöðinni á Akranesi.', 'https://island.is/s/hve/hve-akranes'),
  'Jón Guðni Guðmundsson': ('Jón Guðni Guðmundsson er burðarþolssérfræðingur og brúahönnuður að mennt. Hann leiðir lista Viðreisnar á Akranesi í sveitarstjórnarkosningum 2026, sem eru í fyrsta skipti sem flokkurinn sækist eftir konum og körlum til bæjarstjórnar á Akranesi.', 'https://www.visir.is/g/20262865133d/vid-reisn-bydur-fram-sinn-fyrsta-lista-a-akra-nesi'),
  'Helga Björg Þrastardóttir': ('Helga Björg Þrastardóttir er matreiðslumeistari að mennt og starfi. Hún er á öðru sæti á framboðslista Viðreisnar á Akranesi í sveitarstjórnarkosningum 2026.', 'https://www.visir.is/g/20262865133d/vid-reisn-bydur-fram-sinn-fyrsta-lista-a-akra-nesi'),
  'Ingvar Örn Ákason': ('Ingvar Örn Ákason er verkefnastjóri að starfi. Hann er á þriðja sæti á framboðslista Viðreisnar á Akranesi í sveitarstjórnarkosningum 2026, sem eru í fyrsta skipti sem flokkurinn gefur kost á sér á Akranesi.', 'https://www.visir.is/g/20262865133d/vid-reisn-bydur-fram-sinn-fyrsta-lista-a-akra-nesi'),
  'Guðný Sara Birgisdóttir': ('Guðný Sara Birgisdóttir er fjáröflunarstjóri hjá Krafti, stuðningsmiðstöð á Akranesi, og listakona. Hún er á fjórða sæti á framboðslista Viðreisnar á Akranesi í sveitarstjórnarkosningum 2026.', 'https://www.visir.is/g/20262865133d/vid-reisn-bydur-fram-sinn-fyrsta-lista-a-akra-nesi'),
  'Guðmundur Claxton': ('Guðmundur Claxton hefur starfað í gagnafræði og tæknigreinum, meðal annars sem yfirverkfræðingur gagna hjá Icelandair. Hann er á fimmta sæti á framboðslista Viðreisnar á Akranesi í sveitarstjórnarkosningum 2026.', 'https://theorg.com/org/icelandair/org-chart/gumundur-claxton'),
  'Líf Lárusdóttir': ('Líf Lárusdóttir er verkefnastjóri og bæjarfulltrúi á Akranesi fyrir Sjálfstæðisflokkinn á kjörtímabilinu 2022–2026, þar sem hún gegndi stöðu forseta bæjarstjórnar. Áður hefur hún starfað hjá SSV – samtökum sveitarfélaga á Vesturlandi, Terra umhverfisþjónustu, Fenúr og Íþróttabandlagi Akraness.', 'https://xd.is/2026/02/27/lif-leidir-afram-frambod-sjalfstaedisflokksins-a-akranesi/'),
  'Bjarnheiður Hallsdóttir': ('Bjarnheiður Hallsdóttir er framkvæmdastjóri Kötlu DMI ehf., ferðaþjónustufyrirtækis á Akranesi, og var formaður Samtaka ferðaþjónustunnar (SAF) á árunum 2018–2023. Hún hefur einnig setið í stjórn Samtaka atvinnulífsins og gegnt stöðu varaformanns þar frá 2021.', 'https://saf.is/2018/03/21/bjarnheidur-hallsdottir-nyr-formadur-saf/'),
  'Guðmundur Ingþór Guðjónsson': ('Guðmundur Ingþór Guðjónsson er lögreglumaður og bæjarfulltrúi á Akranesi fyrir Sjálfstæðisflokkinn á kjörtímabilinu 2022–2026. Hann er á þriðja sæti á framboðslista Sjálfstæðisflokksins á Akranesi í sveitarstjórnarkosningum 2026.', 'https://xd.is/2026/02/27/lif-leidir-afram-frambod-sjalfstaedisflokksins-a-akranesi/'),
  'Viktor Elvar Viktorsson': ('Viktor Elvar Viktorsson er húsasmiður og rekstrarstjóri útibús Askju bílaumboðsins á Akranesi, sem opnaði þar árið 2024. Hann á djúpar rætur á Akranessvæðinu og hefur tekið þátt í íþróttastarfi í héraðinu.', 'https://skagafrettir.is/2024/03/22/bilaumbodid-askja-opnar-a-akranesi-med-viktor-elvar-i-brunni/'),
  'Ragnheiður Helgadóttir': ('Ragnheiður Helgadóttir er hjúkrunarfræðingur með BS-gráðu frá Háskólanum á Akureyri og deildastjóri heimahjúkrunar á Akranesi. Hún hefur einnig setið í skólaráði Fjölbrautaskóla Vesturlands á Akranesi.', 'https://xd.is/2026/02/27/lif-leidir-afram-frambod-sjalfstaedisflokksins-a-akranesi/'),
  'Hrafn Ágúst Björnsson': ('Hrafn Ágúst Björnsson er öryggisráðgjafi að starfi og leiðir lista Miðflokksins á Akranesi í sveitarstjórnarkosningum 2026, í fyrsta skipti sem flokkurinn gefur kost á sér á Akranesi. Hann tók þátt í oddvitaumræðum á Akranesi í apríl 2026.', 'https://skessuhorn.is/2026/04/14/midflokkurinn-bydur-i-fyrsta-sinn-fram-a-akranesi'),
  'Guðríður Þorbjörnsdóttir': ('Guðríður Þorbjörnsdóttir er sérfræðingur í stjórnsýslufræði. Hún er á öðru sæti á framboðslista Miðflokksins á Akranesi í sveitarstjórnarkosningum 2026.', 'https://skessuhorn.is/2026/04/14/midflokkurinn-bydur-i-fyrsta-sinn-fram-a-akranesi'),
  'Ólafur Rúnar Sigurðsson': ('Ólafur Rúnar Sigurðsson starfar í sölu og innkaupum. Hann er á þriðja sæti á framboðslista Miðflokksins á Akranesi í sveitarstjórnarkosningum 2026.', 'https://skessuhorn.is/2026/04/14/midflokkurinn-bydur-i-fyrsta-sinn-fram-a-akranesi'),
  'Hörður Svavarsson': ('Hörður Svavarsson er rafvirkjameistari að mennt og starfi. Hann er á fjórða sæti á framboðslista Miðflokksins á Akranesi í sveitarstjórnarkosningum 2026.', 'https://skessuhorn.is/2026/04/14/midflokkurinn-bydur-i-fyrsta-sinn-fram-a-akranesi'),
  'Aníta Hauksdóttir': ('Aníta Hauksdóttir starfar í framleiðniáætlanagerð hjá Norðuráli, álveri á Grundartanga nærri Akranesi. Hún er á fimmta sæti á framboðslista Miðflokksins á Akranesi í sveitarstjórnarkosningum 2026.', 'https://skessuhorn.is/2026/04/14/midflokkurinn-bydur-i-fyrsta-sinn-fram-a-akranesi'),
  'Sigurður Vopni Vatnsdal': ('Sigurður Vopni Vatnsdal er ráðgjafi hjá Sjóvá-Almennum tryggingum á Akranesi. Hann leiðir lista Samfylkingarinnar á Akranesi í sveitarstjórnarkosningum 2026 og er í fyrsta skipti á framboðslista flokksins á Akranesi.', 'https://kratinn.is/2026/03/26/sigurdur-vopni-leidir-samfylkinguna-a-akranesi/'),
  'Jónína Margrét Sigmundsdóttir': ('Jónína Margrét Sigmundsdóttir er bæjarfulltrúi fyrir Samfylkinguna á Akranesi á kjörtímabilinu 2022–2026 og starfsmaður sem veitir stuðning fólki með áfengis- og fíknivanda. Hún er á öðru sæti á framboðslista flokksins á Akranesi í sveitarstjórnarkosningum 2026.', 'https://xs.is/frambjoendur-a-akranesi'),
  'Kristinn Hallur Sveinsson': ('Kristinn Hallur Sveinsson er bæjarfulltrúi fyrir Samfylkinguna á Akranesi á kjörtímabilinu 2022–2026 og sérfræðingur hjá Loftmyndum ehf., sem sérhæfir sig í loftljósmyndun og kortagerð. Hann hefur einnig gegnt trúnaðarmannahlutverki í Heilbrigðisnefnd Vesturlands.', 'https://xs.is/frambjoendur-a-akranesi'),
  'Anna Sólveig Smáradóttir': ('Anna Sólveig Smáradóttir er sjúkraþjálfari og varabæjarfulltrúi Samfylkingarinnar á Akranesi. Hún er með BS-gráðu í sjúkraþjálfun frá University of Alabama í Birmingham (2003) og meistaragráðu í hreyfingarvísindum frá Háskóla Íslands (2015) og hlaut sérfræðiviðurkenningu í taugasjúkraþjálfun árið 2018.', 'https://www.sjak.is/anna-solveig'),
  'Jón Hjörvar Valgarðsson': ('Jón Hjörvar Valgarðsson er forstöðumaður Arnardals á Akranesi og háskólanemi við Háskóla Íslands. Hann var kjörinn formaður Snæfríðar, ungra félaga Samfylkingarinnar á Akranesi, árið 2021.', 'https://skagafrettir.is/2021/03/25/snaefridur-vaknar-til-lifsins-a-akranesi-jon-hjorvar-nyr-formadur/'),

  # HAF - Hafnarfjörður
  'Svenný Kristins': ('Svenný Kristins er tónskáld og aðstoðarmaður við tónlistarkennslu í Hafnarfirði. Hann er á framboðslista Vinstrisins í Hafnarfirði fyrir sveitarstjórnarkosningarnar 2026.', 'https://www.fjardarfrettir.is/frettir/politik/ester-bibi-leidir-lista-vinstrisins-i-hafnarfirdi'),
  'Davíð Arnar Stefánsson': ('Davíð Arnar Stefánsson er landfræðingur og fjallaleiðsögumaður sem starfar hjá Landgræðslunni á sviði sjálfbærni og loftslags. Hann er einnig menntaður garðyrkjufræðingur og húsasmiður, er fæddur og uppalinn í Hafnarfirði og hefur um árabil tekið þátt í þjóðfélagsumræðu um þróun bæjarins.', 'https://www.fjardarfrettir.is/frettir/david-arnar-stefansson-vill-leida-lista-vg-i-hafnarfirdi'),
  'Guðrún Lína Thoroddsen': ('Guðrún Lína Thoroddsen er kvikmyndagerðarmaður. Hún er á framboðslista Vinstrisins í Hafnarfirði fyrir sveitarstjórnarkosningarnar 2026.', 'https://www.midjan.is/vinstrid-er-komid-til-hafnarfjardar/'),
  'Margrét Pétursdóttir': ('Margrét Pétursdóttir er leiðsögumaður. Hún er á framboðslista Vinstrisins í Hafnarfirði fyrir sveitarstjórnarkosningarnar 2026.', 'https://www.midjan.is/vinstrid-er-komid-til-hafnarfjardar/'),
  'Kolbrún Magnúsdóttir': ('Kolbrún Magnúsdóttir er sjálfstætt starfandi mannauðsráðgjafi. Hún hefur starfað sem varabæjarfulltrúi Samfylkingarinnar í Hafnarfirði og setið í fræðsluráði bæjarins áður en hún gekk til liðs við Framsóknarflokkinn árið 2026.', 'https://www.visir.is/g/20262841275d/haettir-i-sam-fylkingunni-og-gengur-til-lids-vid-nyjan-flokk-fyrir-kosningar'),
  'Jóhanna Erla Guðjónsdóttir': ('Jóhanna Erla Guðjónsdóttir er félagsráðgjafi með leyfi útgefið árið 2007. Hún er á framboðslista Framsóknarflokksins í Hafnarfirði og hefur skrifað greinar um réttindi barna.', 'https://felagsradgjof.is/felagsradgjof/felagsradgjafar-med-leyfi/'),
  'Guðmundur Fylkisson': ('Guðmundur Fylkisson er lögreglumaður sem sérhæfir sig í leit að týndum börnum og hefur sinnt þeim verkefnum í rúmlega tíu ár. Hann var valinn manneskja ársins 2025 af RÚV, Vísir og lesendum Smartland fyrir frábærar mannúðlegar og faglegar dygðir í störfum sínum.', 'https://www.ruv.is/frettir/menning-og-daegurmal/2025-12-30-gudmundur-fylkisson-er-manneskja-arsins-2025-462515'),
  'Árni Stefán Guðjónsson': ('Árni Stefán Guðjónsson er 39 ára kennari og áfangastjóri við Flensborgarskólann í Hafnarfirði. Hann hlaut annað sæti á framboðslista Viðreisnar í Hafnarfirði eftir prófkjör þar sem hann fékk 59% atkvæða.', 'https://www.visir.is/g/20262830451d/karo-lina-helga-skakadi-sitjandi-odd-vita-i-hafnar-firdi'),
  'Kristín Thoroddsen': ('Kristín María Thoroddsen er fædd og uppalin í Hafnarfirði og lauk BS-gráðu í ferðamálafræði og MBA-gráðu frá Háskóla Íslands. Hún hefur starfað sem bæjarfulltrúi hjá Sjálfstæðisflokknum í Hafnarfirði í átta ár og setið sem formaður fræðsluráðs, hafnarstjórnar og innkauparáðs.', 'https://xd.is/kristin-maria-thoroddsen-2/'),
  'Viktor Pétur Finnsson': ('Viktor Pétur Finnsson, fæddur 2000, er viðskiptafræðinemi við Háskóla Íslands og fyrrverandi formaður Sambands ungra sjálfstæðismanna (SUS) á árunum 2023–2025. Hann er varaþingmaður Sjálfstæðisflokksins í Suðvesturkjördæmi og hefur setið sem varamaður í skipulags- og byggingarráði Hafnarfjarðar frá 2022.', 'https://www.mbl.is/frettir/innlent/2023/09/17/viktor_petur_nyr_formadur_sus/'),
  'Guðbjörg Oddný Jónasdóttir': ('Guðbjörg Oddný Jónasdóttir er samskiptastjóri hjá Benchmark Genetics og lauk MA-gráðu í alþjóðlegum samskiptum og BA-gráðu í heimspeki, hagfræði og stjórnmálafræði frá Háskóla Íslands. Hún hefur verið bæjarfulltrúi í Hafnarfirði og formaður umhverfis- og framkvæmdaráðs og menningar- og ferðamálanefndar bæjarins.', 'https://www.gudbjorg.is/um'),
  'Kristinn Andersen': ('Kristinn Andersen er prófessor í rafmagns- og tölvuverkfræði við Háskóla Íslands og sviðsstjóri kennslusviðs háskólans. Hann lauk BS-gráðu í rafmagnsverkfræði frá Háskóla Íslands 1982 og doktorsgráðu frá Vanderbilt-háskóla í Bandaríkjunum 1993, og starfaði hjá Marel í rúma tvo áratugi í rannsóknarstjórnarstöðu. Hann hefur setið sem forseti bæjarstjórnar Hafnarfjarðar.', 'https://xd.is/kristinn-andersen-4/'),
  'Böðvar Ingi Guðbjartsson': ('Böðvar Ingi Guðbjartsson er kennari og pípulagningameistari og formaður Félags pípulagningameistara. Hann er í þriðja sæti á framboðslista Miðflokksins í Hafnarfirði.', 'https://www.fjardarfrettir.is/frettir/politik/midflokkurinn-hefur-kynnt-frambodslista-sinn'),
  'Hildur Rós Guðbjargardóttir': ('Hildur Rós Guðbjargardóttir er bæjarfulltrúi Samfylkingarinnar í Hafnarfirði og starfar á hjúkrunarheimili samhliða námi til að verða grunnskólakennari. Hún gekk til liðs við Samfylkinguna árið 2016 og hefur búið í Hafnarfirði í rúmlega átta ár.', 'https://xs.is/hildurros'),
  'Árni Rúnar Þorvaldsson': ('Árni Rúnar Þorvaldsson, fæddur 1976, er grunnskólakennari við Smáraskóla í Kópavogi og lauk kennaranámi frá Kennaraháskóla Íslands árið 2005. Hann starfaði sem bæjarfulltrúi og formaður bæjarstjórnar í Hornafirði í yfir sjö ár og er nú bæjarfulltrúi Samfylkingarinnar í Hafnarfirði; hann var einnig varaþingmaður flokksins í Suðvesturkjördæmi árið 2025.', 'https://arnirunar.is/'),
  'Elín Anna Baldursdóttir': ('Elín Anna Baldursdóttir er sálfræðingur og á framboðslista Samfylkingarinnar í Hafnarfirði. Hún birti grein í apríl 2026 um þjónustu skóla án greininga.', 'https://www.visir.is/g/20262873937d/skoli-an-adgreiningar-krefst-raunverulegrar-thjonustu'),
  'Stefán Már Gunnlaugsson': ('Stefán Már Gunnlaugsson er héraðsprestur Kjalarnesprófastsdæmis og bæjarfulltrúi Samfylkingarinnar í Hafnarfirði. Hann hefur fjallað um húsnæðismál aldraðra í bæjarstjórnarstarfi sínu og tekið þátt í opinberri umræðu um samfélagsmál.', 'https://xshafnarfjordur.is/folkid/4-stefan-mar-gunnlaugsson/'),
  # HAF - Signý Jóna - just occupation found
  'Signý Jóna Tryggvadóttir': ('Signý Jóna Tryggvadóttir er mannauðssérfræðingur. Hún er í öðru sæti á framboðslista Miðflokksins í Hafnarfirði fyrir sveitarstjórnarkosningarnar 2026.', 'https://www.fjardarfrettir.is/frettir/politik/midflokkurinn-hefur-kynnt-frambodslista-sinn'),

  # RNB - Reykjanesbær
  'Róbert Jóhann Guðmundsson': ('Róbert Jóhann Guðmundsson er málarameistari og meðeigandi Málningarþjónustu JRJ ehf., sem hann stofnaði árið 2004. Hann er fæddur og uppalinn á Keflavík og hefur búið í Njarðvík síðan 2001. Hann þjónaði sem fulltrúi Framsóknar í umhverfis- og skipulagsráði Reykjanesbæjar í fjögur ár og situr í stjórn Húsasmíðameistara Suðurnesja.', 'https://www.framsoknrnb.is/robert.html'),
  'Díana Hilmarsdóttir': ('Díana Hilmarsdóttir er forstöðukona Bjargarinnar, geðræktarmiðstöðvar Suðurnesja í Reykjanesbæ. Hún er með BA-gráðu í félagsráðgjöf frá Háskóla Íslands og situr sem bæjarfulltrúi Framsóknar í bæjarstjórn Reykjanesbæjar.', 'https://bjorgin.is/starfsfolk'),
  'Birgir Már Bragasson': ('Birgir Már Bragasson er framkvæmdastjóri Keflavíkur, íþrótta- og ungmennafélags (ÍUK). Hann er í fjórða sæti á framboðslista Framsóknar í Reykjanesbæ fyrir sveitarstjórnarkosningarnar 2026.', 'https://www.keflavik.is/starfsemi/starfsfolk'),
  'Davíð Skarphéðinsson': ('Davíð Skarphéðinsson er byggingafræðingur hjá Verkís ráðgjafarverkfræðistofu og starfar á Suðurnesjum. Hann er í öðru sæti á framboðslista Viðreisnar í Reykjanesbæ við sveitarstjórnarkosningarnar 2026.', 'https://www.linkedin.com/in/dav%C3%AD%C3%B0-skarph%C3%A9%C3%B0insson-a48139b5/'),
  'Ásta Kristín Guðmundsdóttir': ('Ásta Kristín Guðmundsdóttir er kennari og verkefnastjóri hjá Reykjanesbæ þar sem hún hefur sérhæft sig í samhæfingu og þjónustu við flóttafólk og umsækjendur um hæli. Hún er í þriðja sæti á framboðslista Viðreisnar í Reykjanesbæ 2026.', 'https://www.visir.is/g/20262854297d/fyrsti-listi-vidreisnar-i-reykjanesbae-kynntur'),
  'Aðalheiður Júlírós Óskarsdóttir': ('Aðalheiður Júlírós Óskarsdóttir er gæðastjóri og var kjörin formaður Viðreisnarfélags á Suðurnesjum á stofnfundi félagsins. Hún er í fjórða sæti á framboðslista Viðreisnar í Reykjanesbæ 2026.', 'https://www.visir.is/g/20262854297d/fyrsti-listi-vidreisnar-i-reykjanesbae-kynntur'),
  'Sveinn Enok Jóhannsson': ('Sveinn Enok Jóhannsson er bóndi í Höfnum á Reykjanesi. Hann er í fimmta sæti á framboðslista Viðreisnar í Reykjanesbæ 2026 og tók sæti í stjórn Viðreisnarfélagsins á Suðurnesjum.', 'https://www.visir.is/g/20262854297d/fyrsti-listi-vidreisnar-i-reykjanesbae-kynntur'),
  'Margrét Þórarinsdóttir': ('Margrét Þórarinsdóttir er yfirflugfreyja og bæjarfulltrúi í bæjarstjórn Reykjanesbæjar. Hún leiddi lista Umbóts í sveitarstjórnarkosningum 2022 og sat áður í bæjarstjórn fyrir Miðflokkinn 2018–2022; í febrúar 2026 sameinaðist Umbót Sjálfstæðisflokknum og er hún í öðru sæti á lista flokksins.', 'https://xd.is/2026/02/27/umbot-sameinast-sjalfstaedisflokknum-i-reykjanesbae/'),
  'Kristján Pétur Kristjánsson': ('Kristján Pétur Kristjánsson er framkvæmdastjóri Konvin hótels við Keflavíkurflugvöll í Reykjanesbæ. Hann er í þriðja sæti á framboðslista Sjálfstæðisflokksins í Reykjanesbæ 2026.', 'https://xd.is/2026/03/01/frambodslisti-sjalfstaedisflokksins-i-reykjanesbae/'),
  'Alexander Ragnarsson': ('Alexander Ragnarsson er húsasmíðameistari og umsjónarmaður fasteigna hjá Aðaltorgi í Reykjanesbæ. Hann er bæjarfulltrúi Sjálfstæðisflokksins og er í fjórða sæti á framboðslista flokksins 2026.', 'https://xd.is/2026/03/01/frambodslisti-sjalfstaedisflokksins-i-reykjanesbae/'),
  'Guðbergur Reynisson': ('Guðbergur Reynisson er framkvæmdastjóri Cargoflutningar ehf., flutningafyrirtækis milli Reykjavíkur og Suðurnesja sem hann stofnaði árið 2009. Hann er bæjarfulltrúi Sjálfstæðisflokksins í Reykjanesbæ og hefur verið formaður flokksfélags Sjálfstæðisflokksins í Reykjanesbæ frá árinu 2016.', 'https://xd.is/folkid/midstjorn/gudbergur-reynisson/'),
  'Rúnar Fossádal': ('Rúnar Fossádal Árnason er rannsóknarlögreglumaður við lögreglu á Suðurnesjum. Hann er í öðru sæti á framboðslista Miðflokksins í Reykjanesbæ við sveitarstjórnarkosningarnar 2026.', 'https://www.vf.is/frettir/frambodslisti-midflokksins-i-reykjanesbae-stadfestur'),
  'Sigrún Þorsteinsdóttir': ('Sigrún Þorsteinsdóttir er þjónustufulltrúi og félagsliði. Hún er í þriðja sæti á framboðslista Miðflokksins í Reykjanesbæ 2026.', 'https://www.vf.is/frettir/frambodslisti-midflokksins-i-reykjanesbae-stadfestur'),
  'Bjarni Gunnólfsson': ('Bjarni Gunnólfsson er matreiðslumaður að mennt. Hann er í fjórða sæti á framboðslista Miðflokksins í Reykjanesbæ 2026.', 'https://www.vf.is/frettir/frambodslisti-midflokksins-i-reykjanesbae-stadfestur'),
  'Matthildur Júlía Matthíasdóttir': ('Matthildur Júlía Matthíasdóttir er umönnunaraðili og er í fimmta sæti á framboðslista Miðflokksins í Reykjanesbæ 2026.', 'https://www.visir.is/g/20262860793d/thau-skipa-lista-midflokksins-i-reykjanesbae'),
  'Hjörtur Magnús Guðbjartsson': ('Hjörtur Magnús Guðbjartsson er kerfisstjóri að starfi. Hann hefur verið bæjarfulltrúi Samfylkingarinnar í Reykjanesbæ og gegnir stöðu formanns í stjórn Reykjaneshafnar.', 'https://xs.is/sveitarstjornarfolk'),
  'Aðalheiður Hilmarsdóttir': ('Aðalheiður Hilmarsdóttir er atvinnu- og virkniráðgjafi hjá Reykjavíkurborg. Hún hefur gegnt hlutverki varabæjarfulltrúa Samfylkingarinnar í Reykjanesbæ og hefur sérþekkingu á atvinnu- og velferðarmálum.', 'https://is.linkedin.com/in/a%C3%B0alhei%C3%B0ur-hilmarsd%C3%B3ttir-0150311b8'),
  'Bjarni Halldór Heiðuson Janusson': ('Bjarni Halldór Heiðuson Janusson er stjórnmálafræðingur og var árið 2017 yngsti varaþingmaður í sögu Íslands þegar hann tók sæti á Alþingi fyrir hönd Viðreisnar, 21 árs og 142 daga gamall. Hann var meðal stofnenda Viðreisnar árið 2014 og fyrsti formaður ungliðahreyfingar flokksins; í janúar 2026 gekk hann til liðs við Samfylkinguna og er í fjórða sæti á lista hennar í Reykjanesbæ.', 'https://www.althingi.is/altext/cv/is/?nfaerslunr=1303'),
  'Hámundur Örn Helgason': ('Hámundur Örn Helgason er framkvæmdastjóri Ungmennafélagsins Njarðvík (UMFN), íþróttafélags í Reykjanesbæ. Hann hefur einnig gegnt hlutverki íþrótta- og framkvæmdastjóra og komið fram á fundum bæjarstjórnar Reykjanesbæjar í tengslum við íþróttamál.', 'https://www.reykjanesbaer.is/is/stjornsysla/stjornkerfi/fundargerdir/ithrotta-og-tomstundarad/172-fundur-2'),

  # KOP - Kópavogur
  'Svava Halldóra Friðgeirsdóttir': ('Svava Halldóra Friðgeirsdóttir er skjalastjóri hjá Arion banka og hefur gegnt þeirri stöðu frá 2004. Hún starfaði áður sem upplýsingatæknisráðgjafi hjá ANZA hf. frá 2000 til 2004 og er formaður Freyju, kvenfélagssamtaka tengdum Framsóknarflokki í Kópavogi.', 'https://www.fka.is/felagatal/svava-halldora-fridgeirsdottir'),
  'Heiðdís Geirsdóttir': ('Heiðdís Geirsdóttir er félagsfræðingur og formaður Jafnréttis- og mannréttindaráðs Kópavogs. Hún er einnig varamaður í Notendaráði í málefnum fatlaðs fólks í Kópavogi.', 'https://www.kopavogur.is/is/stjornsysla/fundargerdir/jafnrettis-og-mannrettindarad/3888'),
  'Pétur Björgvin Sveinsson': ('Pétur Björgvin Sveinsson er aðstoðarmaður þingflokks Viðreisnar á Alþingi og varaþingmaður flokksins. Hann hefur tekið þátt í þingstarfi og flutt ræður á Alþingi um fjölda mála.', 'https://www.althingi.is/altext/raeda/157/rad20251119T182551.html'),
  'Arnar Grétarsson': ('Arnar Grétarsson er knattspyrnuþjálfari og fyrrverandi landsliðsmaður í knattspyrnu. Hann lék hjá Breiðabliki, AEK Athens og Lokeren, meðal annars, og hefur síðar þjálfað Breiðablik og KA Akureyri.', 'https://en.wikipedia.org/wiki/Arnar_Gr%C3%A9tarsson'),
  'Sigrún Ólöf Ingólfsdóttir': ('Sigrún Ólöf Ingólfsdóttir er skólastjóri Hörðuvallaskóla í Kópavogi. Hún hefur vakið athygli með áréttingu á þörfum kennara og vandkvæðum við stjórnun skóla, meðal annars gagnvart vaxandi ofbeldi nemenda.', 'https://www.dv.is/frettir/2025/01/21/skolastjori-horduvallaskola-segir-ad-kennarar-verdi-ad-fa-valdid-til-baka-ljott-ordbragd-og-vaxandi-ofbeldi-nemenda/'),
  'Elvar Bjarki Helgason': ('Elvar Bjarki Helgason er sölu- og þjónustustjóri og formaður Viðreisnar í Kópavogi. Hann var á meðal þeirra sem samþykktu framboðslista Viðreisnar í Kópavogi á fundi í mars 2026.', 'https://vidreisn.is/2026/03/listi-vidreisnar-i-kopavogi/'),
  'Elísabet Berglind Sveinsdóttir': ('Elísabet Berglind Sveinsdóttir er markaðsstjóri og hefur búið í Kópavogi í þrjá áratugi. Hún er bæjarfulltrúi Sjálfstæðisflokksins í Kópavogi og formaður Forsætisnefndar bæjarins; árið 2008 stofnaði hún góðgerðasamtökin Á allra vörum ásamt vinum sínum.', 'https://www.kopavogur.is/is/stjornsysla/fundargerdir/forsaetisnefnd/4057'),
  'Anna Ceridwen Auðnudóttir': ('Anna Ceridwen Auðnudóttir er stuðningsfulltrúi og listfræðinemi, 26 ára að aldri. Hún er í öðru sæti á framboðslista Sósíalistaflokks Íslands í Kópavogi við sveitarstjórnarkosningarnar 2026.', 'https://www.sosialistaflokkurinn.is/frettir/3-efstu-saeti-i-kopavogsbae'),
  'Marzuk Ingi Lamsiah Svanlaugar': ('Marzuk Ingi Lamsiah Svanlaugar er tölvunarfræðingur og forritari, 29 ára að aldri. Hann starfaði sem aðstoðarkennari í vefforritun við Háskóla Íslands og var á framboðslista Sósíalistaflokks Íslands í Suðvesturkjördæmi við alþingiskosningar 2024.', 'https://heimildin.is/kosningar/althingiskosningar-2024/frambjodandi/J/marzuk-ingi-lamsiah-svanlaugar/'),
  'Nína Berglind Sigurgeirsdóttir': ('Nína Berglind Sigurgeirsdóttir er leikskólastjóri og hlaupaþjálfari. Hún er í öðru sæti á framboðslista Miðflokksins í Kópavogi og hefur skrifað um menntamál, meðal annars greinar um námsárangur og stefnumál í skólakerfi.', 'https://www.kopavogsbladid.is/efstu-fimm-hja-midflokki/'),
  'Beitir Ólafsson': ('Beitir Ólafsson er byggingarverktaki og fyrrverandi atvinnuknattspyrnumaður. Hann lék með KR, HK og Keflavík á æskuárum og er 39 ára. Hann er í þriðja sæti á framboðslista Miðflokksins í Kópavogi.', 'https://www.dv.is/433/2026/02/17/beitir-ut-stjornmalin-midflokkurinn-hefur-skapad-ser-sess-med-ordraedu-sem-eg-tengi-vid/'),
  'Thelma Bergmann Árnadóttir': ('Thelma Bergmann Árnadóttir rekur eigin fyrirtæki og hefur setið í Íþróttaráði Kópavogs. Hún er í fjórða sæti á framboðslista Miðflokksins í Kópavogi 2026.', 'https://utvarpsaga.is/midflokkurinn-kynnir-frambodslista-i-kopavogi/'),
  'Trausti Örn Þórðarson': ('Trausti Örn Þórðarson er lögfræðingur og er í fimmta sæti á framboðslista Miðflokksins í Kópavogi við sveitarstjórnarkosningarnar 2026.', 'https://utvarpsaga.is/midflokkurinn-kynnir-frambodslista-i-kopavogi/'),
  'Eydís Inga Valsdóttir': ('Eydís Inga Valsdóttir er sérfræðingur og liðsstjóri á menningar- og menntasviði Rannís. Hún er með meistaragráður í norrænum fræðum frá Uppsalaháskóla og í stafrænum upplýsingastjórnun frá Högskolan í Borås í Svíþjóð, og starfaði áður sem fulltrúi Íslands við sendiráðið í Stokkhólmi.', 'https://eydisinga.is'),
  'Hákon Gunnarsson': ('Hákon Gunnarsson er sérfræðingur í jarðskorpurannsóknum og umhverfisráðgjafi hjá Resource International í Kópavogi. Hann stofnaði Íslenska jarðhitasamtökin árið 2009 og stjórnaði þeim í sjö ár. Hákon er varabæjarfulltrúi Samfylkingarinnar í Kópavogi og formaður skipulags- og umhverfisnefndar bæjarins.', 'https://www.midjan.is/hakon-fer-i-frambod-i-kopavogi/'),
  'Sólveig Skaftadóttir': ('Sólveig Skaftadóttir er fasteignasali og hefur yfir tíu ára reynslu sem verkefnastjóri í stjórnsýslu Reykjavíkurborgar. Hún er í fjórða sæti á framboðslista Samfylkingarinnar í Kópavogi 2026.', 'https://www.linkedin.com/in/solvska/'),
  'Orri Thor Eggertsson': ('Orri Thor Eggertsson er nemi í rekstrarverkfræði og formaður Taekwondosambands Kópavogs. Hann er í fimmta sæti á framboðslista Samfylkingarinnar í Kópavogi 2026.', 'https://xs.is/frambjodendur-i-kopavogi-2026-'),
  'Bjarki Valberg': ('Bjarki Valberg er skipulagsfræðingur og starfsmaður umhverfissviðs Kópavogsbæjar. Hann er í öðru sæti á framboðslista Vinstri grænna og óháðra í Kópavogi 2026.', 'https://www.mbl.is/frettir/innlent/2026/04/09/anna_sigridur_leidir_lista_vinstri_graenna_og_ohadr/'),
  'Kjartan Sveinn Guðmundsson': ('Kjartan Sveinn Guðmundsson er laganemi og barþjónn. Hann hefur skrifað greinar í Heimildin um ýmis málefni, meðal annars skólakerfið og skipulagsmál, og er þekktur sem greinarhöfundur hjá Nemendum fyrir Palestínu við Háskóla Íslands.', 'https://heimildin.is/heimildin/folk/kjartan-sveinn-gudmundsson/'),
  'Víðís Einarsdóttir': ('Víðís Einarsdóttir er iðjuþjálfi og er í fjórða sæti á framboðslista Vinstri grænna og óháðra í Kópavogi 2026.', 'https://kosningasaga.wordpress.com/2026/04/09/frambodslisti-vinstri-graenna-og-ohadra-i-kopavogi/'),

  # NPG - Norðurþing
  'Eysteinn Heiðar Kristjánsson': ('Eysteinn Heiðar Kristjánsson er verkefnastjóri sjúkraflutninga við Heilbrigðisstofnun Norðurlands (HSN) á Húsavík. Hann leiðir B-lista Framsóknarflokks í Norðurþingi í sveitarstjórnarkosningum 2026 og er formaður Framsóknarfélags Þingeyinga.', 'https://www.vikubladid.is/is/moya/news/b-listi-framsoknarflokks-i-nordurthingi-samthykktur-a-fjolmennum-fundi'),
  'Bylgja Steingrímsdóttir': ('Bylgja Steingrímsdóttir er sjúkraliði og starfsmaður í íbúakjarna á Húsavík. Hún er í öðru sæti á B-lista Framsóknarflokks í Norðurþingi og er varamaður í sveitarstjórn.', 'https://www.vikubladid.is/is/moya/news/b-listi-framsoknarflokks-i-nordurthingi-samthykktur-a-fjolmennum-fundi'),
  'Kristinn Rúnar Tryggvason': ('Kristinn Rúnar Tryggvason er bóndi og atvinnurekandi. Hann er í þriðja sæti á B-lista Framsóknarflokks í Norðurþingi í sveitarstjórnarkosningum 2026.', 'https://www.vikubladid.is/is/moya/news/b-listi-framsoknarflokks-i-nordurthingi-samthykktur-a-fjolmennum-fundi'),
  'Elísabet Anna Helgadóttir': ('Elísabet Anna Helgadóttir er geislafræðingur að mennt. Hún er í fjórða sæti á B-lista Framsóknarflokks í Norðurþingi í sveitarstjórnarkosningum 2026.', 'https://www.vikubladid.is/is/moya/news/b-listi-framsoknarflokks-i-nordurthingi-samthykktur-a-fjolmennum-fundi'),
  'Eiður Pétursson': ('Eiður Pétursson er vélfræðingur og núverandi sveitarstjórnarfulltrúi Framsóknarflokks í Norðurþingi. Hann hefur setið í sveitarstjórn og tekur þátt í ýmsum nefndum og ráðum sveitarfélagsins.', 'https://www.vikubladid.is/is/moya/news/b-listi-framsoknarflokks-i-nordurthingi-samthykktur-a-fjolmennum-fundi'),
  'Helena Eydís Ingólfsdóttir': ('Helena Eydís Ingólfsdóttir er verkefnastjóri hjá Þekkingarnet Þingeyinga og hefur BA-gráðu í kennaramenntun og meistaragráðu í opinberri stjórnsýslu (MPA) frá Háskóla Íslands. Hún er núverandi sveitarstjórnarfulltrúi Sjálfstæðisflokks og 2. varaforseti sveitarstjórnar Norðurþings, og leiðir D-lista Sjálfstæðisflokksins í sveitarstjórnarkosningum 2026.', 'https://xd.is/2026/03/06/frambodslisti-sjalfstaedisflokksins-i-nordurthingi/'),
  'Þorsteinn Snævar Benediktsson': ('Þorsteinn Snævar Benediktsson er bruggmeistari og stofnandi Húsavík Öls, eins af skapandi handverksbrugghúsa á Íslandi. Hann er fæddur og uppalinn á Húsavík og á börn í skólum sveitarfélagsins.', 'https://xd.is/2026/03/06/frambodslisti-sjalfstaedisflokksins-i-nordurthingi/'),
  'Kristján Friðrik Sigurðsson': ('Kristján Friðrik Sigurðsson er fiskeldi- og fiskvísindamaður. Hann er í þriðja sæti á D-lista Sjálfstæðisflokksins í Norðurþingi í sveitarstjórnarkosningum 2026.', 'https://xd.is/2026/03/06/frambodslisti-sjalfstaedisflokksins-i-nordurthingi/'),
  'Guðrún Þóra Hallgrímsdóttir': ('Guðrún Þóra Hallgrímsdóttir er þjónustustjóri. Hún er í fjórða sæti á D-lista Sjálfstæðisflokksins í Norðurþingi í sveitarstjórnarkosningum 2026.', 'https://xd.is/2026/03/06/frambodslisti-sjalfstaedisflokksins-i-nordurthingi/'),
  'Guðni Már Kjartansson': ('Guðni Már Kjartansson er viðskiptamaður og atvinnurekandi. Hann er í fimmta sæti á D-lista Sjálfstæðisflokksins í Norðurþingi í sveitarstjórnarkosningum 2026.', 'https://xd.is/2026/03/06/frambodslisti-sjalfstaedisflokksins-i-nordurthingi/'),
  'Rúnar Traustason': ('Rúnar Traustason er rekstrarstjóri Íslandspósts á Húsavík og sjúkraflutningamaður við HSN, auk þess að starfa sem slökkviliðsmaður hjá Norðurþingi og vera iðnmeistari í kjötiðn. Hann er fæddur og uppalinn á Húsavík.', 'https://www.vikubladid.is/is/frettir/runar-traustason-leidir-lista-samfelagsins-i-nordurthingi-x-m'),
  'Ágúst Sigurður Óskarsson': ('Ágúst Sigurður Óskarsson er ráðgjafi og atvinnulífstengill hjá endurhæfingarsjóðnum Virk, auk þess að vera sjúkraflutningamaður við HSN. Hann var heiðraður af Framsýn árið 2024 fyrir langt og gott starf í þágu stéttarfélaga frá árinu 1988.', 'https://www.vikubladid.is/is/moya/news/m-listi-samfelagsins-i-nordurthingi-lagdur-fram'),
  'Elín Guðmundsdóttir': ('Elín Guðmundsdóttir er bókari hjá endurskoðunarfyrirtækinu Enor ehf. á Húsavík. Hún er í þriðja sæti á M-lista Samfélagsins í Norðurþingi í sveitarstjórnarkosningum 2026.', 'https://www.vikubladid.is/is/moya/news/m-listi-samfelagsins-i-nordurthingi-lagdur-fram'),
  'Brynjar Baldursson': ('Brynjar Baldursson er framkvæmdastjóri Heimamanna ehf., byggingavöruverslunar á Húsavík sem stofnuð var árið 2022. Hann er einnig sjúkraflutningamaður við HSN.', 'https://www.vikubladid.is/is/moya/news/m-listi-samfelagsins-i-nordurthingi-lagdur-fram'),
  'Hilda Rós Pálsdóttir': ('Hilda Rós Pálsdóttir er umsjónarkennari við Borgarhólsskóla á Húsavík. Hún er í fimmta sæti á M-lista Samfélagsins í Norðurþingi í sveitarstjórnarkosningum 2026.', 'https://www.vikubladid.is/is/moya/news/m-listi-samfelagsins-i-nordurthingi-lagdur-fram'),
  'Ómar Gunnarsson': ('Ómar Gunnarsson er sjálfstæður atvinnurekandi og leiðir Óskalistann í sveitarstjórnarkosningum 2026 í Norðurþingi. Hann hefur þekkingu á íbúum og landeignarhöfum um allt sveitarfélagið.', 'https://www.husavik.com/2026/04/thrystingurinn-i-loftinu/'),
  'Gísli Þór Briem': ('Gísli Þór Briem er heilsuverndarsérfræðingur og rekstraraðili íþróttamiðstöðvarinnar á Raufarhöfn í samstarfi við Norðurþing. Hann er í öðru sæti á Óskalistanum í sveitarstjórnarkosningum 2026.', 'https://www.husavik.com/2026/04/thrystingurinn-i-loftinu/'),
  'Einar Sigurðsson': ('Einar Sigurðsson er skipstjóri og sjómaður á Raufarhöfn. Hann er í þriðja sæti á Óskalistanum í Norðurþingi í sveitarstjórnarkosningum 2026.', 'https://www.husavik.com/2026/04/thrystingurinn-i-loftinu/'),
  'Ann-Charlotte Fernholm': ('Ann-Charlotte Fernholm er sænskur uppruni og rekur ásamt maka sínum sauðfjárbú á Gilsbakka í Öxarfirði. Hjónin reka einnig heimaslátrun undir heitinu Sparifé og hafa lagt af mörkum til íbúafjölda á svæðinu.', 'https://www.visir.is/g/20222234576d/saenskar-konur-uppgotvudu-oxarfjord-og-foru-svo-hvergi'),
  'Kjartan Páll Þórarinsson': ('Kjartan Páll Þórarinsson er lögreglumaður og húsasmiður. Hann leiðir S-lista Samfylkingarinnar í sveitarstjórnarkosningum 2026 í Norðurþingi og hefur áður starfað sem íþrótta- og tómstundafulltrúi sveitarfélagsins.', 'https://www.vikubladid.is/is/moya/news/frambodslisti-samfylkingar-i-nordurthingi-samthykktur'),
  'Rebekka Ásgeirsdóttir': ('Rebekka Ásgeirsdóttir er hjúkrunarfræðingur. Hún er varaformaður nefndar um málefni fatlaðra hjá Norðurþingi og er í öðru sæti á S-lista Samfylkingarinnar í sveitarstjórnarkosningum 2026.', 'https://www.vikubladid.is/is/moya/news/frambodslisti-samfylkingar-i-nordurthingi-samthykktur'),
  'Ísak Már Aðalsteinsson': ('Ísak Már Aðalsteinsson er framkvæmdastjóri og verkefnastjóri. Hann er í þriðja sæti á S-lista Samfylkingarinnar í Norðurþingi í sveitarstjórnarkosningum 2026.', 'https://www.vikubladid.is/is/moya/news/frambodslisti-samfylkingar-i-nordurthingi-samthykktur'),
  'Agnieszka Szczodrowska': ('Agnieszka Szczodrowska er þjónustufulltrúi og túlkur hjá stéttarfélögum á Þingeyjarsýslu. Hún tók þátt í málstofu á Húsavík í tilefni baráttudags kvenna árið 2025 og er í fjórða sæti á S-lista Samfylkingarinnar í Norðurþingi.', 'https://www.vikubladid.is/is/moya/news/frambodslisti-samfylkingar-i-nordurthingi-samthykktur'),
  'Reynir Ingi Reinhardsson': ('Reynir Ingi Reinhardsson er lögfræðingur. Hann hefur átt sæti sem áheyrnarfulltrúi í Skipulags- og framkvæmdaráði Norðurþings og er í fimmta sæti á S-lista Samfylkingarinnar í sveitarstjórnarkosningum 2026.', 'https://www.vikubladid.is/is/moya/news/frambodslisti-samfylkingar-i-nordurthingi-samthykktur'),
  'Aldey Unnar Traustadóttir': ('Aldey Unnar Traustadóttir er hjúkrunarfræðingur og hefur setið í sveitarstjórn Norðurþings fyrir hönd V-listans frá 2022, þar sem hún gegnir stöðu 1. varaforseta. Hún hefur verið virkur talsmaður uppbyggingar þjónustu í sveitarfélaginu, m.a. varðandi skóla- og íþróttamál.', 'https://www.nordurthing.is/is/stjornsysla/stjornkerfi/sveitarstjorn'),
  'Salbjörg Matthíasdóttir': ('Salbjörg Matthíasdóttir er flutningastjóri og bóndi á Kelduhverfi. Hún er formaður hverfisráðs Kelduhverfis og er í öðru sæti á V-lista velferðar í sveitarstjórnarkosningum 2026 í Norðurþingi.', 'https://www.nordurthing.is/is/stjornsysla/stjornkerfi/nefndir-og-rad'),
  'Halldór Jón Gíslason': ('Halldór Jón Gíslason er skólameistari Framhaldsskólans á Húsavík, skipaður í embættið frá 1. ágúst 2025 til fimm ára. Hann hefur starfað við skólann frá 2017 sem aðstoðarskólameistari og áfangastjóri, auk þess að hafa unnið í verkefnastjórnun hjá Hvalasafninu á Húsavík. Hann hefur meistaragráðu í mannauðsstjórnun frá Háskóla Íslands.', 'https://www.stjornarradid.is/efst-a-baugi/frettir/stok-frett/2025/06/24/Halldor-Jon-Gislason-skipadur-skolameistari-Framhaldsskolans-a-Husavik/'),
  'Guðmundur H. Halldórsson': ('Guðmundur H. Halldórsson er málárameistari á Húsavík. Hann hefur áður verið á V-lista í Norðurþingi og er í fjórða sæti á V-lista velferðar í sveitarstjórnarkosningum 2026.', 'https://kaffid.is/sex-frambodslistar-i-nordurthingi/'),
  'Guðrún Einarsdóttir': ('Guðrún Einarsdóttir er hjúkrunarfræðingur. Hún er í fimmta sæti á V-lista velferðar í sveitarstjórnarkosningum 2026 í Norðurþingi.', 'https://kaffid.is/sex-frambodslistar-i-nordurthingi/'),
}

with open('js/data/candidates.js', 'r', encoding='utf-8') as f:
    content = f.read()

updated = 0
skipped = 0
for name, (bio_text, source_url) in BIOS.items():
    bio_escaped = bio_text.replace("'", "\\'")
    pattern = re.compile(re.escape(name) + r"([^}]*?bio: )null", re.DOTALL)
    def replacer(m, be=bio_escaped): return name + m.group(1) + "'" + be + "'"
    new_content, n = pattern.subn(replacer, content, count=1)
    if n > 0:
        content = new_content
        updated += 1
    else:
        skipped += 1

with open('js/data/candidates.js', 'w', encoding='utf-8') as f:
    f.write(content)

print(f'Updated: {updated}, Skipped (already has bio or not found): {skipped}')
